### ISSUE TITLE
linuxArm64 target support

### ISSUE THREAD

**Issue by petertrr** [square/okio#1006]
Build for target `linuxArm64` is currently not configured. Would be great to publish okio for this target too, maybe with other `linux*` targets too.
I can try to prepare a PR and see if it builds.

Edit: found a related issue in kotlinx.datetime https://github.com/Kotlin/kotlinx-datetime/issues/75, which is blocking okio from supporting these targets.

**Comment by swankjesse** [comment]
This is now available with Okio 3.6.0.
