### ISSUE TITLE
BufferedSink.write(Source, long) hides bugs

### ISSUE THREAD

**Issue by JakeWharton** [square/okio#105]
It calls `source.read(buffer, byteCount)` which might not read `byteCount` bytes and also might return -1 (which is ignored).

Our API should make it hard to write buggy code, and this one tripped me up forcing use of the inverse API which correctly reported read count.

**Comment by akhilc1** [comment]
Yeah, I got this issue regardless of whatever I give for byteCount only 2kb of data gets written/read
