### ISSUE TITLE
Watchdog clean shut down

### ISSUE THREAD

**Issue by johan-miller** [square/okio#107]
Okio version 1.2.0.

Currently there does not seem to be a way to cleanly shut down the watchdog thread "Okio Watchdog" created by Okio AsyncTimeout. This results in the following warning when shutting down an application.
```
org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
WARNING: The web application [/] appears to have started a thread named [Okio Watchdog] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:460)
 okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:309)
 okio.AsyncTimeout.access$000(AsyncTimeout.java:40)
 okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:272)
```

**Comment by lukiano** [comment]
I'm facing the same issue. I'm using OkHttp in a component that gets reloaded in a live system, and the WatchDog thread continues living, and holding references to the previous ClassLoader, resulting in the inability to GC the old classes.

**Comment by swankjesse** [comment]
I'm looking for a signal:
http://stackoverflow.com/questions/28403240/exit-a-thread-upon-app-unload

**Comment by lukiano** [comment]
:+1: For the record, our case does not involve standard j2ee application reloading, but a custom one (which is quite similar in the result).
Also, I believe that the fact that a thread is started, even though it's an implementation detail, it's an important one, because it makes the concept of life-cycling needed. For instance, OkHttp's dispatcher uses an ExecutorService, that must be shut down.

**Comment by scottharmon** [comment]
This also makes it hard to use in a web container like tomcat, as it will leak every time it is redeployed.

**Comment by CatPlanet** [comment]
I would be more than happy to see this issue resolved. Watchdog prevents classloader to be taken care of GC and causes memory leaks.

**Comment by supertinou** [comment]
👍

**Comment by QwertGold** [comment]
I have created a quick fix for this issue. It adds a public static shutdown() method that you can call when you get the event that the servlet context is being destroyed.
https://github.com/square/okio/pull/243

Lets hope they are quick to merge it.
