### ISSUE TITLE
How can get the current position of Source/Sink

### ISSUE THREAD

**Issue by wu162** [square/okio#1071]
I want to copy some bytes from specific postion relative to current position, but I can't find any method like getPosition()

**Comment by JakeWharton** [comment]
If you want to consume the source: skip(n). readWhatever()

If you don't want to consume the source: peek().skip(n).readWhatever()

**Comment by swankjesse** [comment]
If you happen to be using an Okio FileSystem and FileHandle, you can use this:
https://square.github.io/okio/3.x/okio/okio/okio/-file-handle/position.html

Otherwise you’ll need to write a stream that keeps a count of the number of bytes processed.
