### ISSUE TITLE
FakeFileSystem.appendingSink overrides final method in FileSystem (allegedly)

### ISSUE THREAD

**Issue by occultus73** [square/okio#1074]
Got what appears to be a pretty straightforward bug here:
```
java.lang.LinkageError: Method okio.Sink okio.fakefilesystem.FakeFileSystem.appendingSink(okio.Path) overrides final method in class Lokio/FileSystem; (declaration of 'okio.fakefilesystem.FakeFileSystem' appears in /data/app/~~_8dfbmwlkDFiL8CydKyNdA==/com.foobar.sdk.test-plTS75jHTGSV8vvujArg9w==/base.apk!classes18.dex)
```
Except of course, appendingSink isn't final at all:
```
  @Throws(IOException::class)
  actual abstract fun appendingSink(file: Path, mustExist: Boolean): Sink
```
Bug in the multiplatform compiler? (perish the thought!)
[Baring in mind this code was working fine a few weeks ago, I'm thinking this is probably a bug in the compiler]

**Comment by JakeWharton** [comment]
Do your versions match?

**Comment by occultus73** [comment]
Both dependencies are 3.0.0, yes. This error originally cropped up with alpha 6, so I upgraded to full release, hoping that would fix it; it did not.

**Comment by swankjesse** [comment]
I suspect the default parameter is interfering here somehow.

**Comment by occultus73** [comment]
I tweaked some build scripts around on my end, updated some dependencies, and now the thing seems to be working again. The issue may have had something to do with conflicting transitive dependencies.
