### ISSUE TITLE
TimeUnit abstraction

### ISSUE THREAD

**Issue by yschimke** [square/okio#1084]
Related to OkHttp https://github.com/square/okhttp/pull/7002/files - there should be a coordinated approach to time units in Okio and OkHttp.  

Timeout isn't complete in commonMain because it doesn't specify the timeout durations.

https://github.com/square/okio/blob/5086d945ab5eebbe63d45a15ea9cc69197140d0a/okio/src/jvmMain/kotlin/okio/Timeout.kt

Options?

a) Agree on kotlin DurationUnit being the cross platform representation - unfortunately java TimeUnit is an implementation detail, hidden by the API.
b) Define an expect API like in  https://github.com/square/okhttp/pull/7002/files, with TimeUnit on JVM and DurationUnit on nonJVM.
c) Use primitives?

**Comment by swankjesse** [comment]
Support both on JVM, DurationUnit only on non-JVM

**Comment by yschimke** [comment]
No API change needed here.
