### ISSUE TITLE
OkHttp vs okio

### ISSUE THREAD

**Issue by chjan** [square/okio#109]
Installing with much effort the Spotify WEB API, using OkHttp, again using implicitly okio, I am trying to grasp the interrelation or overlap between these two APIs. I was halted for a day because I had not included the okio 1.2.0. jar in the build, and there were no build warning, and there were no sensible runtime error messages except this: "Retrofit.error: okio.Buffer". And then the Spotify WEB API went awry. 

Hopefully, an improved error reporting system is on its way, but from where, okio or OkHttp or Retrofit?

Could anyone please explain this in 5 sentences? Many thanks.

(Spotify WEB API is now working, so all is fine)

**Comment by JakeWharton** [comment]
It throws a ClassNotFoundException which is standard for anything in Java.
It just got wrapped in a RetrofitError. If you looked in the caused by it
would have been clearer.

**Comment by chjan** [comment]
A ClassNotFoundexception would have lead me to discover the missing jar in a few minutes instead of what happened; a long working day. Java exception handling is an effective tool so why replace it? I have asked in the Retrofit "issues" about that. 

The said error "report" is received through a call back, and there is no more information, nowhere to study any exception. Hence, to look in the "caused by" would require to build the chain of libraries instead of just including them. To build the whole chain like that is bordering on meaninglessness from my point of view. I am chasing to retrieve information from the Spotify Web API, not to understand all underlying mechanisms used.

The problem with the chain of all the wrappers used in the Spotify web api (retrofit, OkHttp, okio, etc), is that there seem to be a general lack of documentation on each library. And so, a newcomer is stuck when things go awry. 

Maybe you could update the readme with those 5 sentences, see above?

**Comment by JakeWharton** [comment]
If you look at the caused by throwable on the RetofitError you would see
ClassNotFoundException. It's wrapped because there's a lot of extra
information to propagate from Retrofit.

**Comment by swankjesse** [comment]
On OkHttp's site it says what it is, and on Okio's site it says what it is. What else?

**Comment by venkateshappea** [comment]
Hey chjan! I am running into the same problem as you had earlier, I included the:
    compile 'com.spotify.sdk:spotify-auth:1.0.0-beta10@aar'

    // This library handles music playback
    compile 'com.spotify.sdk:spotify-player:1.0.0-beta10@aar'

    compile 'com.android.support:appcompat-v7:22.1.1'
    compile 'com.squareup.okio:okio:1.2.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp:2.2.0'
in my gradle file in my android studio project and included all the .jar files but it still seems to crash and i keep getting an Unexpected retrofit error. do you have any suggestions what else I can do? I'm at a road block now.

**Comment by chjan** [comment]
venkateshappea, what I experienced was that the library okio-1.2.0 jar file was not present, and then the strange thing that this was not reported when compiling. I picked up this library from the okio git webpage, and included it. Then everything was ok.

I believe this has been described in the readme section at the Spotify WEB api?

Please note that I am using Netbeans using JAR files, not yet gradle with AAR files. Therefore, it is probably better to ask kaaes or others over at Spotify regarding your problem.
