### ISSUE TITLE
Assets filesystem for Android platform

### ISSUE THREAD

**Issue by JakeWharton** [square/okio#1097]
I _think_ this should be possible, but I'm curious what APIs won't work. I suspect the fact that the zip filesystem exists means we can pull this off, though.

**Comment by JakeWharton** [comment]
This is a pain in the ass because in order to add an Android variant we need to remove `withJava()` from the JVM variant. It's only needed for tests, so can probably create our own `JavaCompile` task to handle that, but it also is used for the OSGi ~crap~ crap.

We could ship it separately, but that sucks. I'll play around with it.

**Comment by vanniktech** [comment]
Thinking broader about this, another use case might be an implementation for Amazon's S3. Although, also here there might be some APIs that might not work.

**Comment by JakeWharton** [comment]
Yet another need for this came up, but now somewhere in open source land.

I'm going to put this into a sibling module. Putting it in the core is too much work, and we can always do it in the future if we want.
