### ISSUE TITLE
ByteStrings that cheat by marking segments as immutable

### ISSUE THREAD

**Issue by swankjesse** [square/okio#111]
I'm tempted to build a ByteString that uses a linked list of segments behind-the-scenes. You'd get it by calling Buffer.readByteString(), but no copy would happen if certain size thresholds were met: the segments would just be reassigned to the ByteString.

We could go even further in efficiency & complexity by supporting Buffers composed of a mix of readonly and immutable segments.

**Comment by swankjesse** [comment]
I have a branch that implements this! PR coming soon.

**Comment by adriancole** [comment]
Interesting idea. So copies would be limited to the last segment, or would
the ByteString include a final partially full segment?

**Comment by swankjesse** [comment]
Shared segments can be completely partial. This is where the performance model gets difficult: it's probably always a win to share a 2 KiB segment. But do we share when it's just 100 bytes?

**Comment by swankjesse** [comment]
https://github.com/square/okio/pull/116
