### ISSUE TITLE
String.toPath() replaces back slashes in file names with a forward slash

### ISSUE THREAD

**Issue by colinrtwhite** [square/okio#1116]
`String.toPath()` replaces consecutive back slash characters with `Path.DIRECTORY_SEPARATOR` (a single forward slash on android). This can cause issues if attempting to read a file with back slashes in its name using the `FileSystem` API. Here's a failing test case:

```kotlin
assertEquals(
    expected = "/absolute/path/to/file\\\\\\_with_slash_in_name.txt",
    actual = "/absolute/path/to/file\\\\\\_with_slash_in_name.txt".toPath().toString()
)

// actual returns "/absolute/path/to/file/_with_slash_in_name.txt"
```

Reproduced in Okio 3.0.0 and 3.1.0.

More context: https://github.com/coil-kt/coil/issues/1274

**Comment by swankjesse** [comment]
Yep. This is working as intended. I made the design decision to treat `/` and `\` characters as path separators always. You may be able to create file names in certain file systems with these characters in their names, but it is problematic at best. In particular the file name is ambiguous.

I recommend avoiding using slash characters in file names. If that's not possible you won't be able to use Okio's Path class.
