### ISSUE TITLE
Enable compatibility mode for projects that don't use hierarchical structure

### ISSUE THREAD

**Issue by joffrey-bion** [square/okio#1117]
Okio 3.1.0 upgraded to Kotlin 1.6.20 and automatically introduced the hierarchical project structure.
As per [the documentation for library authors](https://kotlinlang.org/docs/multiplatform-hierarchy.html#for-library-authors):

> Libraries published with the new hierarchical project structure are only compatible with projects that already have a hierarchical project structure. To enable compatibility with non-hierarchical projects, add the following to the gradle.properties file in your library project:
> `kotlin.mpp.enableCompatibilityMetadataVariant=true`

I'm using this flag myself in one of my own multiplatform libraries. However, because Okio doesn't use it, I get the following error:
```
> Error while evaluating property 'filteredArgumentsMap' of task ':krossbow-websocket-core:compileKotlinMetadata'
   > Could not resolve all files for configuration ':krossbow-websocket-core:metadataCompileClasspath'.
      > Could not resolve com.squareup.okio:okio:3.1.0.
        Required by:
            project :krossbow-websocket-core
         > The consumer was configured to find a usage of 'kotlin-api' of a library, preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common'. However we cannot choose between the following variants of com.squareup.okio:okio:3.1.0:
             - iosArm64ApiElements-published
             - iosSimulatorArm64ApiElements-published
             - iosX64ApiElements-published
             - jsIrApiElements-published
             - jsLegacyApiElements-published
             - jvmApiElements-published
             - jvmRuntimeElements-published
             - linuxX64ApiElements-published
             - macosArm64ApiElements-published
             - macosX64ApiElements-published
             - mingwX64ApiElements-published
             - tvosArm64ApiElements-published
             - tvosSimulatorArm64ApiElements-published
             - tvosX64ApiElements-published
             - watchosArm32ApiElements-published
             - watchosArm64ApiElements-published
             - watchosSimulatorArm64ApiElements-published
             - watchosX64ApiElements-published
             - watchosX86ApiElements-published
```

Is it possible for you to enable this flag? Currently users that are running Kotlin versions older than 1.6.20 in their Gradle builds won't be able to use Okio 3.1.0 - or my library if I also give up this flag.

We can also decide that this is a non-issue and that users will upgrade eventually.

**Comment by joffrey-bion** [comment]
I don't think that's it. It can only be done if the common source set is not using platform specific code (meaning, it's really just common). I think this limitation only applies if your project only has a limited subset of targets that share some APIs, but this should not be the case here

**Comment by oldergod** [comment]
Probably July
