### ISSUE TITLE
iOS path usage with FileManager.default.urls

### ISSUE THREAD

**Issue by vanniktech** [square/okio#1128]
I've got a wrapper aound `FileSystem` as I want to support other systems (mainly Amazon S3) as well:
 
 ```kotlin
 class FileSystemFileHandler(
  root: String,
  private val fileSystem: FileSystem,
) : FileHandler {
  private val root = root.toPath()

  override fun write(path: String, source: Source) {
    val okioPath = root / path
    okioPath.parent?.let { fileSystem.createDirectories(it) }

    source.buffer().use { input ->
      fileSystem.sink(okioPath).buffer().use { output ->
        output.writeAll(input)
      }
    }
  }
}
```

On Android, I do:

```kotlin
FileSystemFileHandler(filesDir.absolutePath, FileSystem.SYSTEM)
```

On iOS, I do:

```
FileSystemFileHandler(
  root: FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0].absoluteString,
  fileSystem: OkioFileSystem.Companion().SYSTEM
)
```

The problem with iOS is though that: 

```swift
FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0].absoluteString
```

returns

```
file:///Users/niklas/Library/Developer/CoreSimulator/Devices/A4BE2A42-D3FB-48D7-8D3B-C5C154A0F214/data/Containers/Data/Application/E095BAD5-33A5-499C-93A9-E10530F8A041/Documents/
```

Which isn't handled. When trying to write a file I get an error message saying that the file system is read only.

The fix is:

```diff
-FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0].absoluteString
+FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0].absoluteString.removePrefix("file://")
```

Is `Path` just not handling `file://` prefix correctly? Should it be lenient and automatically remove the prefix or is it a valid case to distinguish between `/Users/niklas/` and `file:///Users/niklas/`?

**Comment by swankjesse** [comment]
`Path` expects a path and not a URL so your fix is correct. I don't think we should remove this prefix automatically; it's possible you actually want the literal interpretation of the string `file:///foo` which is a surprising but not impossible file path equivalent to `file:/foo`.

We could was also build behavior to convert `file:`-schemed URLs to paths. Removing the prefix is completely sufficient in your situation but not on Windows and not in general.
https://datatracker.ietf.org/doc/html/rfc8089#appendix-E

**Comment by vanniktech** [comment]
There's a simpler solution, `URL` has a `path` property which returns what okio wants 🤦 .

```diff
+FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0].absoluteString.removePrefix("file://")
-FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0].path
```
