### ISSUE TITLE
Is it normal that the pos greater than limit in Buffer?

### ISSUE THREAD

**Issue by TeslaCN** [square/okio#1133]
Apache ShardingSphere uses testcontainers for integration tests. Sometimes the test process consumes 100% CPU. I dumped heap and flamegraph, and found that there was a Buffer whose size was -2.

Related issue: https://github.com/apache/shardingsphere/issues/19648

![image](https://user-images.githubusercontent.com/20503072/181665410-159e6612-6c3c-4b9b-9311-0819039a428b.png)

And the thread was stuck in dead loop in the following method.

![image](https://user-images.githubusercontent.com/20503072/181665605-23e13396-2901-45ed-8b63-4a434b969adc.png)

![image](https://user-images.githubusercontent.com/20503072/181665523-7e233155-6aaf-454d-b07b-ee9bddcb9b05.png)

**Comment by swankjesse** [comment]
No, this is very bad. Typically the only way to get into trouble like this is to share a Buffer between multiple threads, which is definitely unsafe.

**Comment by TeslaCN** [comment]
> No, this is very bad. Typically the only way to get into trouble like this is to share a Buffer between multiple threads, which is definitely unsafe.

Thank you.
