### ISSUE TITLE
Conversion of relative Paths to absolute Paths

### ISSUE THREAD

**Issue by sellmair** [square/okio#1153]
Currently the `FileSystem.canonicalize` API only works for paths that are actually present in the current FileSystem. |
It would be great to have a `FileSystem.currentWorkingDir` or `FileSystem.absolute(path: Path)` API to convert relative paths to absolute ones.

**Comment by swankjesse** [comment]
You can get the current working dir by canonicalizing `".".toPath()`

**Comment by sellmair** [comment]
Hmm, this however leads to strange behaviour in the FakeFileSystem: See
https://github.com/sellmair/delete/blob/master/src/commonTest/kotlin/fileSystemUtils/createFakeFilesystem.kt

**Comment by linkjam** [comment]
> You can get the current working dir by canonicalizing `".".toPath()`

not work, still "."

**Comment by 0x6675636b796f75676974687562** [comment]
Apologies for necro-posting, but if you want a library routine, you can use [`Path.absolute()`](https://saveourtool.github.io/okio-extras/okio-extras/com.saveourtool.okio/absolute.html) from [okio-extras](https://github.com/saveourtool/okio-extras).
