### ISSUE TITLE
Benchmark compared to what?

### ISSUE THREAD

**Issue by brettwooldridge** [square/okio#117]
Benchmarks are great, in that they measure the inherent performance of something, but more useful is comparison to the same "something" implemented in what okio is meant to replace.

For example, how does okio compare to Apache commons-io's IOUtils for reading a file, or parsing an XML or JSON file, or some other common I/O code pattern?

For example, see the [HikariCP Connection Pool](https://github.com/brettwooldridge/HikariCP-benchmark) benchmarks or the [Boon JSON Parser](https://github.com/RichardHightower/json-parsers-benchmark) benchmarks.

**Comment by swankjesse** [comment]
Not sure what action for us to take here. Do you want to write us a benchmark?

**Comment by brettwooldridge** [comment]
You already have a [benchmark](https://github.com/square/okio/tree/master/benchmarks), I've run it.  Is the purpose just to measure one *okio* release compared to another?  My feedback was, if that is the case that is cool, but it would be nice to see how *okio* performs compared to alternatives.

Obviously you are free to close this issue as you see fit.  My preference would be that this be considered an enhancement request (again feel free to *label* it as such), and be left open.  Unless of course *okio* has no plans to ever implement a comparative benchmark.

**Comment by swankjesse** [comment]
Ahh, gotcha. Yeah, that benchmark exists to measure segment recycling for tuning our implementation. It's not intended for marketing or comparison.
