### ISSUE TITLE
Issues with case sensitivity on iOS simulator

### ISSUE THREAD

**Issue by LandryNorris** [square/okio#1170]
While iOS filesystems are case-insensitive, iOS simulators are case-sensitive. Because of this, the following will work on iOS devices, but fail on simulators

```
        val subfolder1 = path.resolve("Test")
        val subfolder2 = path.resolve("test")
        
        if(!fileSystem.exists(subfolder1)) fileSystem.createDirectory(subfolder1, true)
        if(!fileSystem.exists(subfolder2)) fileSystem.createDirectory(subfolder2, true)
```

fileSystem.exists(subfolder2) will return false, but fileSystem.createDirectory(subfolder2, true) will throw an IOException, since it cannot create the 'test' folder due to case-sensitivity.

https://apple.stackexchange.com/questions/284847/is-there-a-known-reason-why-the-filesystem-in-ios-is-case-sensitive

**Comment by swankjesse** [comment]
We’re using `lstat()` to check whether the file exists, and `mkdir()` to create the directory. If the iOS simulator is case-sensitive sometimes and case-insensitive other times, Okio can’t do much. I assume using the iOS file system APIs directly would yield the same results.

A good-enough workaround is to just make one call, and assume that if it doesn‘t throw you got the directory you wanted.

```
 fileSystem.createDirectory(subfolder1)
```
