### ISSUE TITLE
Please add linuxArm64 and Arm32 variants

### ISSUE THREAD

**Issue by mvysny** [square/okio#1171]
At the moment okio does not offer a library variant for the ARM processor, which is a pity since `kotlin.io` is pretty much non-existent on native, and there is no other library offering any kind of io for kotlin native other than okio. In other words, at the moment there is no support for working with files and streams on native/arm. Would it be possible to build okio for arm as well please?

**Comment by mvysny** [comment]
Unofficial okio port to arm: https://github.com/Kotlin/kotlinx.coroutines/issues/855#issuecomment-1242878799

Unfortunately it's not clear how to use it.

**Comment by luca992** [comment]
`linuxArm64` was added to kotlinx.coroutines

**Comment by danbrough** [comment]
> Unofficial okio port to arm: [Kotlin/kotlinx.coroutines#855 (comment)](https://github.com/Kotlin/kotlinx.coroutines/issues/855#issuecomment-1242878799)
> 
> Unfortunately it's not clear how to use it.

I've put together a demo for okio here: 
https://github.com/danbrough/kotlinxtras/tree/main/demos/repos/okio
That's working on my linuxArm32Hfp RPI.

**Comment by mvysny** [comment]
Probably also blocked by https://github.com/Kotlin/kotlinx-datetime/issues/165

**Comment by luca992** [comment]
> Probably also blocked by [Kotlin/kotlinx-datetime#165](https://github.com/Kotlin/kotlinx-datetime/issues/165)

Looks like there's a pr https://github.com/Kotlin/kotlinx-datetime/pull/261 

Not merged yet though.

**Comment by Siedlerchr** [comment]
The version from @danbrough  works for me 
 https://github.com/danbrough/okio

**Comment by bcmedeiros** [comment]
https://github.com/Kotlin/kotlinx-datetime/pull/261 is now merged
