### ISSUE TITLE
Watchdog's run method - synchronized block inside a try catch causing a runtime crash

### ISSUE THREAD

**Issue by randmaayan** [square/okio#1175]
AsyncTimout's Watchdog's method run has a synchronized block inside a try catch.

https://github.com/square/okio/blob/master/okio/src/jvmMain/kotlin/okio/AsyncTimeout.kt

This is causing apps to crash when using **Android Gradle Plugin 7.2.0** and above and **testCoverageEnabled flag** enabled. 

taking out the synchronized of the try catch should solve the issue?

**Comment by swankjesse** [comment]
What’s the crash? I suspect this is a bug in the coverage tool?

**Comment by eleventigers** [comment]
I believe the crash (which I observed too) looks like this:
```
java.lang.VerifyError: Verifier rejected class okio.AsyncTimeout$Watchdog: void okio.AsyncTimeout$Watchdog.run() failed to verify: void okio.AsyncTimeout$Watchdog.run(): [0x38] expected to be within a catch-all for an instruction where a monitor is held 
```
I am wondering if https://github.com/square/okio/commit/f8434f575787198928a26334758ddbca9726b11c "fixes" it by replacing synchronized with explicit locks.

**Comment by swankjesse** [comment]
Yeah good point! No further action on this.
