### ISSUE TITLE
FakeFileSystem.canonicalize doesn't resolve symlinks

### ISSUE THREAD

**Issue by kropp** [square/okio#1229]
It does resolve them internally, but returns unresolved (original) path.

**Comment by swankjesse** [comment]
# Thanks for sending this!

Having this been broken so severely and for so long is a giant problem. Thanks for the clear defect report and this fix. Unfortunately I found our implementation is more severely broken than this fix will cover, so I created another PR (#1270) which I believe should cover everything.

I also added tests to all the file systems that support symlinks in an attempt to confirm this is consistent with real file systems.

I’m closing this PR but I sincerely appreciate the work and apologize for sitting on it for so long.
