### ISSUE TITLE
Use official nodejs bindings

### ISSUE THREAD

**Issue by DRSchlaubi** [square/okio#1253]
https://github.com/square/okio/blob/d9178afd41b728d463e1907cf2957401e2b86985/okio-nodefilesystem/src/main/kotlin/okio/FsJs.kt#L21-L46

After reading this, I wonder whether the official kotlin-wrappers repository was ever considered. Unlike kotlinx-nodejs it doesn't wrap the entire nodejs API, however, it wraps the `fs` and `os` APIs which are used by okio.

Also, unlike kotlinx-nodejs it is actually maintained and doesn't use Dukat but the special [types-kotlin](https://github.com/karakum-team/types-kotlin) generator.

Might want to check it out here: https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-node

**Comment by swankjesse** [comment]
We didn’t consider it. It might not have existed at the time this was written.
