### ISSUE TITLE
when exhausted throw io exception

### ISSUE THREAD

**Issue by beckyxu** [square/okio#1262]
I use k8s client meet a problem, issue:https://github.com/kubernetes-client/java/issues/2678
In short:http long connection ,when the server is down, same code of client ,it can throw exception on windows, but macos and linux can't. 
the  k8s code is:
`  public boolean hasNext() {
    try {
      return !response.source().exhausted();
    } catch (IOException e) {
      throw new RuntimeException("IO Exception during hasNext method.", e);
    }
  }`

response.source() is  okio.BufferedSource 。
I want to know when exhausted can throw IOException.
Thanks.

**Comment by swankjesse** [comment]
Unclear what action to take here. Could you create a failing test that demonstrates the problem?
