### ISSUE TITLE
ArrayIndexOutOfBoundsException from Buffer#readByte()

### ISSUE THREAD

**Issue by benjamin-bader** [square/okio#128]
Observed in okio 1.0.1; haven't upgraded to 1.2.0 yet.  I didn't see any open or closed issues like this, but if this is already fixed then sorry to have missed it.  Regrettably I can't reliably reproduce this, but at least here is a stacktrace:

```
java.lang.ArrayIndexOutOfBoundsException: length=2048; index=2048
        at okio.Buffer.readByte(Buffer.java:237)
        at okio.Buffer.readShort(Buffer.java:269)
        at okio.Buffer.readShortLe(Buffer.java:356)
        at okio.RealBufferedSource.readShortLe(RealBufferedSource.java:203)
```

I see this regularly in our analytics, and today for the first time it happened to me.  It's entirely possible that I'm doing something incorrectly.  The crash appears to be a bookkeeping error - in `readByte()`, where `size` is non-zero but `head.pos` is equal to `head.data.length`.

If this is fixed already, great.  If I can offer more info, please let me know.  Thanks!

**Comment by swankjesse** [comment]
Do me a favor? Do you have any idea what the call immediately preceding the `readByte()` call was? It looks like _that_ call could be leaving the buffer in an inconsistent state. I just did a full scan through the codebase and it looks like everything is legit, but it could be that I'm missing something.

Also please upgrade to 1.2! It's a shame if you're running into problems we've already fixed when you could be running into problems we don't know about yet!

**Comment by benjamin-bader** [comment]
Well, `readByte()` here happens inside of a call to `readShortLe()`, but in our code it's actually hard to say what might have corrupted the state.  We have a long-lived socket connection, and this particular source just sits and reads pulls frames out of it forever; the app had been running for a little while, and I don't know how the state of the buffer changed.  I'll add some diagnostics, and if it happens again will update this issue.

There are two places where we call `readShortLe()`, though; the immediately-preceding things that *could* have happened are `BufferedSource#readByteArray(int)` and `BufferedSource#readUtf8(int)`.

I would certainly like to update - I'm on okhttp-2.1.0 still as 2.2.0 caused our unit tests using mockwebserver to fail, and just haven't yet spent the time to dig in to that.

**Comment by swankjesse** [comment]
Cool. I'm guessing that when you update, this will go away. The UTF8 and bye array-reading code have both changed in the interim.

Sorry about the MockWebServer churn; we've been sloppier-than-usual about being good stewards of its API. Mostly in the interest of moving forward and fixing bugs, but churn does make upgrading painful.

**Comment by benjamin-bader** [comment]
Thanks, glad to hear; I'll prioritize this and see what I can see.  Let's close this for now; I'll re-open if there are still problems.

No worries re: the churn.  If I had to choose between churn and not having awesome libraries, I *definitely* know which one I'd pick!

**Comment by JakeWharton** [comment]
And I'll note that Okio 1.2.0 should work fine with OkHttp 2.1 if you want
to just upgrade it first.
