### ISSUE TITLE
publish-windows action fails during clean

### ISSUE THREAD

**Issue by swankjesse** [square/okio#1286]
Our [publish task for Okio 3.4.0 on Windows](https://github.com/square/okio/actions/runs/5486897376/jobs/9999698180#logs) failed like so:

```
> Task :okio:clean FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':okio:clean'.
> java.io.IOException: Unable to delete directory 'D:\a\okio\okio\okio\build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - D:\a\okio\okio\okio\build\tmp\.cache\expanded\expanded.lock
    - D:\a\okio\okio\okio\build\tmp\.cache\expanded
    - D:\a\okio\okio\okio\build\tmp\.cache
    - D:\a\okio\okio\okio\build\tmp
```

I worked around it for 3.4.0 by skipping the `clean` task. But we should do something better here.

**Comment by JakeWharton** [comment]
Can probably delete the whole job. Mac OS and Linux can both cross-compile for Windows targets for at least a year now.

If you look at the `publish` job it built and uploaded the mingw artifacts: https://github.com/square/okio/actions/runs/5486897376/jobs/9999698018

**Comment by swankjesse** [comment]
... and now I’m curious how both publishes succeeded. Don’t love that.

```
> Task :okio-fakefilesystem:signMingwX64Publication
> Task :okio-fakefilesystem:publishMingwX64PublicationToMavenCentralRepository
Closing repository: comsquareup-1278

? waiting for close...
? waiting for close...
? waiting for close...Repository comsquareup-1278 closed
Releasing repository: comsquareup-1278
Repository comsquareup-1278 released
```

**Comment by oldergod** [comment]
Don't we wanna keep CI on windows to confirm environment related bugs, like the separator?
