### ISSUE TITLE
Proguard config file 'okio.pro' referenced in index.md does not exist

### ISSUE THREAD

**Issue by Zhuinden** [square/okio#1302]
https://github.com/square/okio/blob/master/okio/src/jvmMain/resources/META-INF/proguard/okio.pro

See https://github.com/square/okio/blob/2a050ec4f9222a5d58a1f3a8a432c0fa14da1955/docs/index.md?plain=1#L156

**Comment by swankjesse** [comment]
(Introduced by https://github.com/square/okio/pull/1290)
