### ISSUE TITLE
ByteString.random(int size, Random random)

### ISSUE THREAD

**Issue by swankjesse** [square/okio#132]
Seems like this could be handy.

**Comment by swankjesse** [comment]
After a short investigation, this is currently difficult to do right. In particular we’d probably want to do a `SecureRandom`, and that means we’d need to carry a lot of baggage to do secure randoms securely on old Android versions.

**Comment by JakeWharton** [comment]
Borrowing a mutable byte[] is a good solution in lieu of native randomness.
