### ISSUE TITLE
Wasm readUtf8CodePoint returns invalid code

### ISSUE THREAD

**Issue by igoriakovlev** [square/okio#1333]
okio version: 3.5.0
Kotlin version: 1.9.0

Consider this code:
```
import okio.Buffer
import kotlin.test.*

class TestCase {
    @Test
    internal fun sss() {
        val buffer = Buffer()
        val tree = "\uD83C\uDF34"
        buffer.writeUtf8(tree)
        val codePoint = buffer.readUtf8CodePoint()
        val expect = 127796
        assertEquals(codePoint, expect)
    }
}
```

Expect: This test should be passed for JS and Wasm targets
Actual: Fails for Wasm target with: `AssertionError: Expected <65533>, actual <127796>.`

**Comment by swankjesse** [comment]
Fixed in Kotlin 1.9.10.
https://youtrack.jetbrains.com/issue/KT-60212
