### ISSUE TITLE
Do I need manually call close()?

### ISSUE THREAD

**Issue by xxxifan** [square/okio#136]
Do I need manually call close() like this?

        // Read inputStream and output to temFile path
        Source source = Okio.source(inputStream); 
        BufferedSource buffer = Okio.buffer(source);
        Sink sink = Okio.sink(tmpFile);
        buffer.readAll(sink); 

        sink.close();
        buffer.close();
        source.close();

**Comment by JakeWharton** [comment]
Calling `buffer.close()` will automatically call `source.close()`. Otherwise, yes, you should close both the source and sink to ensure any resources are released when you are done with the objects.
