### ISSUE TITLE
Potential file leak in `FileSystem.read()` method

### ISSUE THREAD

**Issue by pablobaxter** [square/okio#1364]
Continued investigation in file descriptor leaks led to this stack trace:
```
#1 /Users/pablobaxter/.gradle/caches/modules-2/files-2.1/com.squareup.wire/wire-schema-jvm/4.7.0/4f9c99c8217fc7d53fd11fa3e885559c62280227/wire-schema-jvm-4.7.0.jar by thread:main on Tue Oct 10 12:47:57 PDT 2023
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:173)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
        at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
        at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
        at java.base/sun.net.www.protocol.jar.JarFileFactory.getOrCreate(JarFileFactory.java:106)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:132)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:175)
        at java.base/java.net.URL.openStream(URL.java:1161)
        at java.base/java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1735)
        at okio.internal.ResourceFileSystem.source(ResourceFileSystem.kt:129)
        at com.squareup.wire.schema.CoreLoader.load(CoreLoader.kt:54)
        at com.squareup.wire.schema.internal.CommonSchemaLoader.load(CommonSchemaLoader.kt:148)
        at com.squareup.wire.schema.Linker.getFileLinker$wire_schema(Linker.kt:74)
        at com.squareup.wire.schema.Linker.link(Linker.kt:95)
        at com.squareup.wire.schema.internal.CommonSchemaLoader.loadSchema(CommonSchemaLoader.kt:103)
        at com.squareup.wire.schema.SchemaLoader.loadSchema(SchemaLoader.kt:71)
        at com.squareup.wire.schema.WireRun.execute(WireRun.kt:219)
        at com.squareup.wire.schema.WireRun.execute(WireRun.kt:211)
```

From what I've been able to gather, this is the [culprit code](https://github.com/square/okio/blob/5e2580e0ad001b13d0f8efd7fccc2ffa43a3f882/okio/src/jvmMain/kotlin/okio/FileSystem.kt#L67):
```kotlin
@Throws(IOException::class)
@JvmName("-read")
actual inline fun <T> read(file: Path, readerAction: BufferedSource.() -> T): T {
  return source(file).buffer().use {
    it.readerAction()
  }
}
```

From what I can tell, the `use {}` lambda is not closing the `source` property of the `RealBufferedSource` object, but it's unclear why.

**Comment by swankjesse** [comment]
Any chance you could reproduce this with a FakeFileSystem and its ability to check for unexpected open files?

Looking at the stack trace here I don’t see the leak, though perhaps it’s in JarURLConnection or similar.

**Comment by pablobaxter** [comment]
@swankjesse, I believe you are right. Using the `FakeFileSystem`, it shows the `Source` object generated under the covers of the `read()` function is closed properly. However, this wouldn't detect open streams within the standard Java library, which I believe is what we are seeing here. Looking at the trace, I'm seeing that calling `getResourceAsStream()` forces the stream to stay open even when `close()` is called due to a caching flag. Tracing the code:

https://github.com/openjdk/jdk17/blob/4afbcaf55383ec2f5da53282a1547bac3d099e9d/src/java.base/share/classes/java/lang/ClassLoader.java#L1731
```java
public InputStream getResourceAsStream(String name) {
    Objects.requireNonNull(name);
    URL url = getResource(name);
    try {
        return url != null ? url.openStream() : null;
    } catch (IOException e) {
        return null;
    }
}
```

Here, the focus is on the `openStream()` function, which calls `openConnection().getInputStream()` to create a new `JarURLConnection` object and a new `JarURLInputStream` object:
https://github.com/openjdk/jdk17/blob/4afbcaf55383ec2f5da53282a1547bac3d099e9d/src/java.base/share/classes/sun/net/www/protocol/jar/Handler.java#L38C46-L38C46
```java
protected java.net.URLConnection openConnection(URL u)
throws IOException {
    return new JarURLConnection(u, this);
}
```

https://github.com/openjdk/jdk17/blob/4afbcaf55383ec2f5da53282a1547bac3d099e9d/src/java.base/share/classes/sun/net/www/protocol/jar/JarURLConnection.java#L105
```java
class JarURLInputStream extends java.io.FilterInputStream {
    JarURLInputStream (InputStream src) {
        super (src);
    }
    public void close () throws IOException {
        try {
            super.close();
        } finally {
            if (!getUseCaches()) {
                jarFile.close();
            }
        }
    }
}
```

What's interesting here is that the `InputStream` created here will not close so long as the the cache flag is enabled, which is `true` by default: https://github.com/openjdk/jdk17/blob/4afbcaf55383ec2f5da53282a1547bac3d099e9d/src/java.base/share/classes/java/net/URLConnection.java#L226

I believe there is a workaround for this (by calling `setUseCaches(false)` on the `URLConnection`), but I'd have to verify this on a test project. I still need to find a way to unit test this as well.

**Comment by swankjesse** [comment]
Great investion!

**Comment by swankjesse** [comment]
Great investigation’

**Comment by Lisi-Chen** [comment]
Hello @pablobaxter and @swankjesse 

I've also encountered this issue and I'd like to help with the file leak in `FileSystem.read()`. I'm considering exploring the `setUseCaches(false)` workaround and its effects. 

I'm interested in working on this issue for an assignment. If it's unassigned, could it be assigned to me? 

Thanks!

**Comment by pablobaxter** [comment]
I'm not actively working on a solution for this yet. My idea was to approach this similarly to how [Gradle approached](https://github.com/gradle/gradle/blob/f3c0ec523c02411cc4d5683295f82f39f01a7ba0/platforms/core-runtime/base-services/src/main/java/org/gradle/internal/service/DefaultServiceLocator.java#L151) what I believe was a similar issue with the Java API.

If you intend to take this on, feel free to ping me on a PR for it.

**Comment by Lisi-Chen** [comment]
I tried a few attempts to resolve the file descriptor leak in FileSystem.read() method. 

1. Close InputStream in read() Method
I tried to explicitly close the InputStream after converting it to a BufferedSource and before its subsequent use.

2. Disable URL Connection Caching
Disabled URL connection caching in an attempt to prevent resources from being retained.

3. Use a Custom Resource Stream Wrapper with Caching Control
Implemented a custom resource stream wrapper to provide direct control over the useCaches flag of JarURLConnection, and ensured that the InputStream is explicitly closed.

Preliminary tests indicate a successful resolution of the file descriptor leak issue for the third method, but I am still working on testing to validate the stability of this solution.

**Comment by Lisi-Chen** [comment]
I tried to devise a custom resource stream wrapper to gain better control over the useCaches flag of JarURLConnection. This is implemented to ensure that the InputStream is closed explicitly.
`object CustomResourceLoader {

    fun getResourceAsStream(classLoader: ClassLoader, resourceName: String): InputStream? {
        val resourceURL = classLoader.getResource(resourceName) ?: return null
        val connection = resourceURL.openConnection()

        // Explicitly disable caching
        connection.useCaches = false

        return connection.getInputStream().let { CustomResourceInputStream(it) }
    }
}

private class CustomResourceInputStream(inputStream: InputStream) : FilterInputStream(inputStream) {

    override fun close() {
        try {
            super.close()
        } finally {
            // Ensure the underlying jar file is closed
            (this.`in` as? JarURLConnection)?.jarFile?.close()
        }
    }
}

// Usage:
val stream = CustomResourceLoader.getResourceAsStream(
    ClassLoader.getSystemClassLoader(), "path/to/resource"
)
stream?.use { /* process the stream */ }
`

**Comment by pablobaxter** [comment]
@Lisi-Chen I'm surprised that just setting `connection.useCaches = false` wasn't enough. From what I was seeing, this flag alone was preventing the underlying jar file from being closed.

**Comment by pablobaxter** [comment]
I decided to take a stab at this. Unit test took some effort, but it is able to confirm whether the file is cached by the `URLConnection` or not.
