### ISSUE TITLE
Invalid java classname in GzipSource.kt

### ISSUE THREAD

**Issue by nasrajan** [square/okio#1368]
Hi,

Some of our java class name validation tests are flagging the jvmName "-GzipSourceExtensions" in GzipSource.kt. Can this be changed to a valid class name?

Thanks.

**Comment by JakeWharton** [comment]
It's meant to be invalid in Java as it's for Kotlin users only.

**Comment by JakeWharton** [comment]
If the class has the synthetic bit set does the tool still complain?

**Comment by nasrajan** [comment]
Mine is a gradle project. Okio is brought in by okhttp with: 
`manage 'com.squareup.okhttp3:okhttp', '4.11.0'`

The resulting  java classpath has the above discussed classes starting with "-". Is there a way I can exclude them?

**Comment by JakeWharton** [comment]
No, because they contain methods that OkHttp or other libraries written in Kotlin may link to in their bytecode.

**Comment by swankjesse** [comment]
No action to take on this.
