### ISSUE TITLE
large memory usage while IO

### ISSUE THREAD

**Issue by xxxifan** [square/okio#137]
I'm downloading using okhttp with okio.
code:

                InputStream stream = response.body().byteStream();
                BufferedSource source = Okio.buffer(Okio.source(stream));
                BufferedSink sink = Okio.buffer(Okio.sink(new File(path)));
                long readBytes, downloaded = 0l;
                int bufferSize = 8 * 1024;
                while ((readBytes = source.read(sink.buffer(), bufferSize)) > 0) {
                    downloaded += readBytes;
                    if (downloaded > 0) {
                        // publishProgress
                    }
                }
                sink.flush();
                sink.close();
                source.close();

and memeory usage:
![okio](http://i.imgur.com/Ca10A11.png)

and I write like this, the issue's gone

                InputStream stream = response.body().byteStream();
                FileOutputStream fileOutputStream = new FileOutputStream(new File(path));
                byte[] buffer = new byte[8 * 1024];
                int count;
                long downloaded = 0;
                while ((count = stream.read(buffer)) > 0) {
                    fileOutputStream.write(buffer, 0, count);
                    downloaded += count;
                    if (downloaded > 0) {
                       // publishProgress
                    }
                }
                fileOutputStream.flush();
                fileOutputStream.close();
                stream.close();

is there any problem of my code or is that a bug happened to me? thanks

**Comment by swankjesse** [comment]
You're accumulating data into a buffer, but not pushing it down into the file. Adding a call to `sink.emit();` in the body of the loop will fix things.

You can simplify your code by avoiding streams altogether:
```
    BufferedSource source = response.body().source();
    BufferedSink sink = Okio.buffer(Okio.sink(new File(path)));
```
Even better, look at the [progress example](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java).

**Comment by xxxifan** [comment]
thanks! it help me a lot! :+1:

**Comment by TigerZhag** [comment]
> You're accumulating data into a buffer, but not pushing it down into the file. Adding a call to `sink.emit();` in the body of the loop will fix things.
> 
> You can simplify your code by avoiding streams altogether:
> 
> ```
>     BufferedSource source = response.body().source();
>     BufferedSink sink = Okio.buffer(Okio.sink(new File(path)));
> ```
> Even better, look at the [progress example](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java).

this link [progress example](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java) is not avaiable now, is there a new example of progress listener?

**Comment by TigerZhag** [comment]
> > You're accumulating data into a buffer, but not pushing it down into the file. Adding a call to `sink.emit();` in the body of the loop will fix things.
> > You can simplify your code by avoiding streams altogether:
> > ```
> >     BufferedSource source = response.body().source();
> >     BufferedSink sink = Okio.buffer(Okio.sink(new File(path)));
> > ```
> > Even better, look at the [progress example](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java).
> 
> this link [progress example](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java) is not avaiable now, is there a new example of progress listener?

Founded it. for others: [progress example](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java)

**Comment by tomerpetel** [comment]
> You're accumulating data into a buffer, but not pushing it down into the file. Adding a call to `sink.emit();` in the body of the loop will fix things.
> 
> You can simplify your code by avoiding streams altogether:
> 
> ```
>     BufferedSource source = response.body().source();
>     BufferedSink sink = Okio.buffer(Okio.sink(new File(path)));
> ```
> 
> Even better, look at the [progress example](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java).

Correct link is:
[progress example]
(https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java)
