### ISSUE TITLE
Gradle reports that okio references itself

### ISSUE THREAD

**Issue by MartinHaeusler** [square/okio#1373]
In my gradle project build where I use the Okio package, gradle reports the following in `compileKotlin`:

```
'dependencies.dependency[com.squareup.okio:okio:2.2.2]' for com.squareup.okio:okio:2.2.2 is referencing itself. 
    in com.squareup.okio:okio:2.2.2
```

I'm not 100% sure if I messed something up or not, but it sounds like something might be off with your *.pom file.

Could you please take a look if that's the case? Anybody else seeing this in their build logs?

**Comment by swankjesse** [comment]
Does the problem exist for the current Okio release?

**Comment by MartinHaeusler** [comment]
@swankjesse that's an excellent question... I'll need to do some experimentation, as okio occurs as a 3rd level transitive dependency for my project (I use OpenStack4J, which uses Okhttp, which uses okio). OpenStack4J isn't exactly the most update-happy lib out there, so I will have to try to upgrade okhttp and hope that OpenStack4J can work with the newer version.

**Comment by MartinHaeusler** [comment]
@swankjesse it turns out that an outdated dependency in our project had a transitive dependency on okio 2.2.2. We've updated that, all good now :)
