### ISSUE TITLE
Using FileSystem.SYSTEM.listRecursively() on MacOS, it returns incorrect directory name.

### ISSUE THREAD

**Issue by AzraelWarrior** [square/okio#1398]
When using the listRecursively() method on MacOS, there is a subdirectory named A/B in the child directories under the root directory. However, in the returned results of listRecursively(), the name of this subdirectory is treated only as a folder name, without its parent folder directory. 
directories: <img width="785" alt="image" src="https://github.com/square/okio/assets/3697072/ec1fc219-ae36-46d3-b2aa-321995f86b68">
code: 
<img width="637" alt="image" src="https://github.com/square/okio/assets/3697072/5a74345e-ab37-4943-8039-4bcd98319477">
result:
<img width="351" alt="image" src="https://github.com/square/okio/assets/3697072/6380a250-4b20-480f-bdc7-3d14aacbd3de">

Okio Version: 3.6.0

**Comment by swankjesse** [comment]
Okio’s FileSystem and Path APIs do not support individual file or directory names that include `/` or `\` characters.

If you need this, you should find a different file system API. We’ve chosen to not support this because the complexity is substantial and the benefits are negligible.

**Comment by swankjesse** [comment]
I wrote some notes on files [here](https://publicobject.com/2020/10/06/files/).

With Okio’s FileSystem APIs we’re not trying too hard to cater to use cases where files are end-user-visible UI elements. In particular, we’re not investing in building powerful ACL bindings, metadata management, or exotic file names that contain `/` characters. If you’re building systems that need this, our library might be too simple for you.

**Comment by AzraelWarrior** [comment]
> I wrote some notes on files [here](https://publicobject.com/2020/10/06/files/).
> 
> With Okio’s FileSystem APIs we’re not trying too hard to cater to use cases where files are end-user-visible UI elements. In particular, we’re not investing in building powerful ACL bindings, metadata management, or exotic file names that contain `/` characters. If you’re building systems that need this, our library might be too simple for you.

Well, thank you for your explanation.
