### ISSUE TITLE
Add zip file support on non-JVM targets. 

### ISSUE THREAD

**Issue by Wavesonics** [square/okio#1408]
Currently it's using Java's Zip file handling under the hood, what would be great is something written in kotlin so it can work on any of the targets.

**Comment by swankjesse** [comment]
With this, we’re mostly done:
https://github.com/square/okio/pull/1439

@Wavesonics need anything beyond `FileSystem.openZip()` ?

**Comment by Wavesonics** [comment]
I think that does it, and it just transparently handles de/compression?

**Comment by Wavesonics** [comment]
yep I think that does it. and I can traverse the tree in that file system and read and write to it?

and I guess it'll just do de/compression transparently?

**Comment by swankjesse** [comment]
Yep, it’s read-only currently. We could do read-write though! We’d do that in common code for both platforms.

**Comment by mipastgt** [comment]
Yes, please make this read-write.
