### ISSUE TITLE
Unsafe access to segment byte arrays

### ISSUE THREAD

**Issue by swankjesse** [square/okio#141]
```
UnsafeBuffer b = new UnsafeBuffer();
b.acquireForRead(buffer, 1024);
Audio.read(b.array, b.offset, b.count);
b.release();
```

**Comment by JakeWharton** [comment]
And just so we don't forget:

> if you want a 4096 byte[] we could just allocate it and create a segment that isn't recycled to the pool. and that's an implementation detail that might change if we get bucketed pools later on
