### ISSUE TITLE
Nothing could save Android-Studio-1.2.RC from Proguard, yet...

### ISSUE THREAD

**Issue by ShawnOceanHu** [square/okio#144]
Hi guys,
WIth Android Studio: 1.2.RC

I enabled proguard in .gradle:
```
          minifyEnabled=true
```
and added these rules to my proguard-rules.pro:
```
-dontwarn com.squareup.**
-dontwarn okio.**
```
and added these lint rules to my .gradle file:
```
        warningsAsErrors false
        abortOnError false
        disable 'InvalidPackage'
```

But I still get these warning when I try to run the app in debug mode:
```
Warning: okio.DeflaterSink: can't find referenced class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
Warning: okio.Okio: can't find referenced class java.nio.file.Files
Warning: okio.Okio: can't find referenced class java.nio.file.Files
Warning: okio.Okio: can't find referenced class java.nio.file.Files
Warning: okio.Okio: can't find referenced class java.nio.file.Path
Warning: okio.Okio: can't find referenced class java.nio.file.OpenOption
Warning: okio.Okio: can't find referenced class java.nio.file.Path
Warning: okio.Okio: can't find referenced class java.nio.file.OpenOption
Warning: okio.Okio: can't find referenced class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
Warning: okio.Okio: can't find referenced class java.nio.file.Path
Warning: okio.Okio: can't find referenced class java.nio.file.OpenOption
Warning: okio.Okio: can't find referenced class java.nio.file.Path
Warning: okio.Okio: can't find referenced class java.nio.file.OpenOption
Warning: okio.Okio: can't find referenced class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
Warning: there were 14 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
:app:proguardDebug FAILED
```

It's so weird since I also added these rules/options to all my library modules that depend on OkHttp/Picasso, I don't know where went wrong, perhaps this is a Android Studio bug ? Does anyone have any clues to this problem ?

**Comment by swankjesse** [comment]
Might have better luck asking on stackoverflow. This is a ProGuard / Android tools problem and okio is just the unlucky library that's doing something ProGuard doesn't like.

**Comment by swankjesse** [comment]
That said, I'd love too document the workaround here; lots of okio users get caught by this.

**Comment by tbsandee** [comment]
@ShawnOceanHu in addition to ```minifyenabled=true```, make sure you're including the proguard ruleset. I don't think there is a default Proguard filename.

```
proguardFile 'proguard-rules.pro`
```

Also, this is the set of rules I have in my ```proguard-okio.pro```:

```
-dontwarn java.nio.file.Files
-dontwarn java.nio.file.Path
-dontwarn java.nio.file.OpenOption
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
```

Running Android Studio 1.2.0-RC1 + Android Gradle Plugin 1.2.0-RC1.

**Comment by ShawnOceanHu** [comment]
Hi guys,
Sorry for the long delay, got stuck on another problem : )

I have tried @tbsandee 's suggestion but with no luck still the same errors.

I have posted this on SO: http://stackoverflow.com/questions/29886882/android-studio-1-2-rc-proguard-warnings-on-squares-okio-library-reference

**Comment by ShawnOceanHu** [comment]
BTW, does anyone have the same problem ?

**Comment by ShawnOceanHu** [comment]
Hi I have found the problem, I forgot to specify the proguard file for my debug build @tbsandee :+1: 

Awkward : )

**Comment by hslls** [comment]
any solution @ShawnOceanHu, i have encounter the same problem

**Comment by ShawnOceanHu** [comment]
Hi @hslls, check here: http://stackoverflow.com/questions/29886882/android-studio-1-2-rc-proguard-warnings-on-squares-okio-library-reference
