### ISSUE TITLE
BufferedSource read more that is in the stream or maybe broken Source from InputStream

### ISSUE THREAD

**Issue by novemberox** [square/okio#146]
I was looking for quick way to get size of my stream. So I've created method like this:

    private long getSize(InputStream in) throws IOException {
        BufferedSource source = Okio.buffer(Okio.source(in));
        return source.readAll(Sinks.DEV_NULL_SINK);
    }

Where `Sink` is empty implementation. I've wrote test for it:

    public void testSize() throws Exception {
        ByteArrayInputStream bis = new ByteArrayInputStream(new byte[123000]);
        assertEquals(123000, getSize(bis));
    }

and it fails with: `junit.framework.AssertionFailedError: expected:<123000> but was:<3993720>`. Documentation doesn't say that it might be valid behavior.

**Comment by swankjesse** [comment]
What did DEV_NULL sink do?

**Comment by novemberox** [comment]
It's empty implementation.

**Comment by novemberox** [comment]
I see, I should implement write method.

**Comment by novemberox** [comment]
Yep, simple 

        public void write(Buffer source, long byteCount) throws IOException {
            source.skip(byteCount);
        }

fixes that, sorry for that.

**Comment by swankjesse** [comment]
No problem. That surprised me too when I needed one. We should probably just include a null sync out of the box.
