### ISSUE TITLE
API for unwrapping FileSystem

### ISSUE THREAD

**Issue by yschimke** [square/okio#1465]
Maybe unblocked by https://github.com/square/okio/issues/1464

But given a FileSystem, I'd like to be able to unwrap it to tell it's real type. Is it FileSystem.SYSTEM under the hood? or a zip file? or resources? or S3?

**Comment by swankjesse** [comment]
I don’t want to do this because I think it’ll lead to fragile code in practice.

But I do think we should design a mechanism to add extensions to the file system API so it doesn’t have to be comprehensive always. Perhaps something like OkHttps request tags.

**Comment by swankjesse** [comment]
https://github.com/square/okio/issues/1466
