### ISSUE TITLE
BufferedSink.writeUtf8() not writing all content to file

### ISSUE THREAD

**Issue by chungchungdev** [square/okio#1480]
[My little project](https://github.com/chungchungdev/GGenCrossRayTblConvertor.git) extract strings from some tbl files and then write them to a txt file. But the BufferedSink.writeUtf8() method cannot write all content to the file. I also tested with printing to console and java nio,. Only okio produce inconsistent result, the last few lines are missing.

The raw file is probably copyrighted so I share it separately on a [google drive link](https://drive.google.com/file/d/1-xV1QGmCnXWKOZ8Y5BTQ05LgUNHT8aEi/view?usp=drive_link). Put it "src/main/kotlin/ggendata" folder, then run the Main.kt.

**Comment by JakeWharton** [comment]
Are you wrapping it in a `use` so that the buffer is flushed and the file is closed?

**Comment by chungchungdev** [comment]
well... you are right. I am really sorry for wasting you guys time...

**Comment by JakeWharton** [comment]
No problem! Glad you got it sorted out.
