### ISSUE TITLE
Supports quic network protocol

### ISSUE THREAD

**Issue by zoujiaqing** [square/okio#1482]
In theory, systems that support UDP support the QUIC protocol.
We would love to use kotlin to develop cross-platform web applications, but our protocol currently relies on QUIC for network transport. (Currently using quic-go)
When will ktor support QUIC protocol communication?

**Comment by JakeWharton** [comment]
Ktor is https://github.com/ktorio/ktor, not this project.

**Comment by zoujiaqing** [comment]
> Ktor is https://github.com/ktorio/ktor, not this project.

Thank you! 
However, ktor's IO adaptation layer should use okio.
