### ISSUE TITLE
Add a feature to load data in chuncks using BufferedSource 

### ISSUE THREAD

**Issue by premrajm** [square/okio#150]
BufferedSource designed to use against InputStream but since BufferedSource loads entire data in memory, it cannot be used to read big files. 
It would be great if BufferedSource can really buffer some chunk of data instead of whole file. 

Since Okio complements java.io and nio I really thought BufferedSource is an replacement/option to java's BufferedReader. 

Example I was trying : https://gist.github.com/premrajm/c5f012ced316b7de17b1

**Comment by swankjesse** [comment]
For what it's worth, the API lets you buffer as much as you want. `readString()` reads the whole thing in one go.
