### ISSUE TITLE
Transitive dependency on kotlinx-datetime:0.5.0 breaks backward compatibility?

### ISSUE THREAD

**Issue by Spirarel** [square/okio#1517]
There is an [upstream issue](https://slack-chats.kotlinlang.org/t/18822236/hi-there-i-m-trying-to-update-to-0-6-0-from-0-5-0-but-i-m-fa) ([cause](https://youtrack.jetbrains.com/issue/KT-60874/KLIB-Resolve-Dont-save-transitive-dependencies-in-manifests-depends-property)) with kotlinx-datetime:0.5.0 -> 0.6.0 breaking compatibly.

3.9.0 specifies kotlinx-datetime:0.5.0, whereas 3.10.0-SNAPSHOT has been updated to 0.6.1.

Is there a timeline you can share for that release?

**Comment by JakeWharton** [comment]
> Is there a timeline you can share for that release?

Today!

https://github.com/square/okio/releases/tag/3.9.1
