### ISSUE TITLE
Logs uncatchable java.io.InterruptedIOException

### ISSUE THREAD

**Issue by musselwhizzle** [square/okio#152]
If you get an InputStream from Okio and interrupt it's Thread, Okio logs an uncatchable exception. 

> 06-03 16:05:03.973    3295-3394/com.junk.sampleapp W/System.err﹕ java.io.InterruptedIOException
06-03 16:05:03.975    3295-3394/com.junk.sampleapp W/System.err﹕ at com.android.okio.Deadline.throwIfReached(Deadline.java:56)
06-03 16:05:03.975    3295-3394/com.junk.sampleapp W/System.err﹕ at com.android.okio.Okio$2.read(Okio.java:110)
06-03 16:05:03.975    3295-3394/com.junk.sampleapp W/System.err﹕ at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
06-03 16:05:03.975    3295-3394/com.junk.sampleapp W/System.err﹕ at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
06-03 16:05:03.975    3295-3394/com.junk.sampleapp W/System.err﹕ at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
06-03 16:05:03.975    3295-3394/com.junk.sampleapp W/System.err﹕ at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
06-03 16:05:03.975    3295-3394/com.junk.sampleapp W/System.err﹕ at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
06-03 16:05:03.975    3295-3394/com.junk.sampleapp W/System.err﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
06-03 16:05:03.975    3295-3394/com.junk.sampleapp W/System.err﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:649)

Below is sample code (Android) to reproduce

> public class MainActivity extends ActionBarActivity {

	private UrlConnTask task;
	private boolean isLoad = true;
	private Button button;
	private ImageView iv;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		installStreamHandler();
		LinearLayout ll = new LinearLayout(this);
		ll.setOrientation(LinearLayout.VERTICAL);
		button = new Button(this);
		button.setText("Start process");
		button.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				loadAndCancel();
			}
		});
		ll.addView(button);
		ll.addView(iv = new ImageView(this));
		setContentView(ll);
	}

	private void installStreamHandler() {
		URL.setURLStreamHandlerFactory(new OkUrlFactory(new OkHttpClient()));
	}

	private void loadAndCancel() {
		if (isLoad) {
			iv.setImageBitmap(null);
			task = new UrlConnTask();
			task.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, "http://your_image_url_here.png");
		} else {
			task.cancel(true);
		}
		button.setText(isLoad ? "Cancel" : "Load");
		isLoad = !isLoad;
	}

	private class UrlConnTask extends AsyncTask<String, Void, Bitmap> {
		@Override
		protected Bitmap doInBackground(String... params) {
			try {
				URL u = new URL(params[0]);
				HttpURLConnection conn = (HttpURLConnection) u.openConnection();
				conn.setConnectTimeout(2500);
				conn.setReadTimeout(2500);
				conn.setUseCaches(false);
				conn.setDoInput(true);
				conn.setInstanceFollowRedirects(false);
				conn.connect();
				InputStream is = conn.getInputStream();
				Bitmap bitmap = BitmapFactory.decodeStream(is);
				return bitmap;
			} catch (InterruptedIOException e) { // uncatchable. This never reached. 
				Log.i("Main", "Caught an InterruptedIOException", e);
				return null;
			} catch (IOException e) {
				Log.i("Main", "Caught an IOException", e);
				return null;
			}
		}

		@Override
		protected void onPostExecute(Bitmap bitmap) {
			super.onPostExecute(bitmap);
			if (isCancelled()) return;
			Log.i("Main", "Got an image:" + (bitmap != null));
			iv.setImageBitmap(bitmap);
		}

		@Override
		protected void onCancelled() {
			Log.i("Main", "onCancelled");
			iv.setImageBitmap(null);
		}
	}

}

**Comment by swankjesse** [comment]
It's your code calling into `BitmapFactory.decodeStream`. Nothing we can do! You probably want to catch the exception into whatever is decoding your bitmaps.

**Comment by musselwhizzle** [comment]
> You probably want to catch the exception into whatever is decoding your bitmaps.

Did you read the description, or look at the code, or even try the code? The code sample and logs make it pretty clear.

**Comment by swankjesse** [comment]
Can you simplify the sample to omit Android's bitmap decoder? That isn't okio and suggests the problem lies far away from okio.

**Comment by musselwhizzle** [comment]
> It's your code calling into
Oh I see what you mean. It's BitmapFactory. decodeStream swallowing the error and not okhttp. Yea, nothing you can do. Thanks for looking into it and considering.
