### ISSUE TITLE
Optional limits on methods like readLine()

### ISSUE THREAD

**Issue by swankjesse** [square/okio#153]
To avoid exhausting memory when it would be better to just crash.

Inspired by https://github.com/square/okio/issues/150

**Comment by eneim** [comment]
I'm waiting for this ... Just for an extra: any idea of a delayed readLine()? (so every 100ms I read the next line, without the Thread.sleep() methodology). Thanks and hope this one is added to life soon :D.

**Comment by swankjesse** [comment]
The limits I was imagining would cause the reads to fail with an exception if they were too long. This might not be a good fit.

**Comment by ericedens** [comment]
For `readUtf8LineStrict`, I just submitted a #279 to recast _limit_ as the maximum number of bytes returned, rather than the maximum number of bytes scanned.

I'll start on the remaining methods soon! (`readUtf8Line()`, `indexOf(ByteString)`, and `indexOfElement()`)

**Comment by ericedens** [comment]
OK, I'm looking at `readUtf8Line(long limit)` now. Any preference on the behavior if `limit` is 0? Looking at its analogs:
- `readUtf8LineStrict(0)` throws an `EOFException`
- `readUtf8(0)` returns an empty string
- Calling `readUtf8Line()` on an empty source returns null

Returning an empty string follows the spirit of `readUtf8Line` being a forgiving API, and we're indeed returning a string that has zero bytes. So I'm inclined in that direction.

Thoughts?

**Comment by swankjesse** [comment]
I should apologize I also changed `readUtf8LineStrict()` to permit 0 and return an empty string. I should have mentioned that on that PR.

My original plan to forbid it wasn’t counting on the fact that sometimes callers may wanna just consume a `\n` or `\r\n` from the input.

So I think the same makes sense for non-strict. Really the only difference between the two is that the strict one won’t accept the end of the file as a line terminator.

**Comment by ericedens** [comment]
Good to close this?

**Comment by swankjesse** [comment]
Yes! Thanks @ericedens!
