### ISSUE TITLE
[Feature] Read values unsigned as next bigger type

### ISSUE THREAD

**Issue by panzerdev** [square/okio#155]
In a current project I have to parse `byte[]` but the values I want are supposed to be unsigned. 

For example the value I need is 0 to 255 but Java's `byte` is -128 to 127 so I always have to do:
`Buffer buffer = new Buffer()`

`int unisignedValue = buffer.readByte() & 0xff;` instead of 
`int unisignedValue = buffer.readByteAsUnsignedInt()`

`int unisignedValue = buffer.readShort() & 0xffff;` instead of 
`int unisignedValue = buffer.readShortAsUnsignedInt()`

`long unisignedValue = buffer.readInt() & 0xffffffff;` instead of 
`long unisignedValue = buffer.readInttAsUnsignedLong()`

Of course for little-endian as well.

Java 8 is already offering tools for this with `Byte.toUnsignedInt()` for example.
[Byte.toUnsignedInt()](https://docs.oracle.com/javase/8/docs/api/java/lang/Byte.html#toUnsignedInt-byte-)

Do you think this would this fit into Okio?

**Comment by swankjesse** [comment]
Tough call. I don't mind `readByte() & 0xff` personally, but I can see where you're coming from.

**Comment by adelnizamutdinov** [comment]
sigh, this is trivial with Kotlin, but painful in Java

especially when `writeShort` takes `int`, but `readShort` returns `short`

**Comment by swankjesse** [comment]
One other problem is that we can’t be consistent because `readLong()` exists.

**Comment by panzerdev** [comment]
Wouldn't it be `readUnsignedInt()` returning a `long` ?

**Comment by swankjesse** [comment]
Yeah, but what does `readUnsignedLong` return?

**Comment by panzerdev** [comment]
`BigInteger` ? But I'm not sure if uint64 is really a thing in the real world.

**Comment by swankjesse** [comment]
No further action planned on this.
