### ISSUE TITLE
java.nio.file.*  can not be resolved

### ISSUE THREAD

**Issue by haogg** [square/okio#169]
a bit strange.
My project works well with the 1.5.0 jar file but not  the source.
It tells me that classes in java.nio can not be resolved. But my jdk  is 1.8 and eclipse is 4.4.2.
So, is there any help or explaination for me?
Thanks.

**Comment by swankjesse** [comment]
You're probably resolving against Android which doesn't have `java.nio.file.*`. This is okay; that API doesn't hurt if it's unused.
