### ISSUE TITLE
BufferedSource.indexOf(ByteString) is very slow

### ISSUE THREAD

**Issue by JanecekPetr** [square/okio#171]
We almost DDoSed ourselves on this one.

If the source is big enough (a few megabytes is ok, with 40 MB+ is almost impossible to finish) and contains the first byte of the target `ByteString` a couple of times before the actual match, the method is not very likely to finish.

The profiler says that the worst offender is, understandably, the `Buffer#getByte(long)` which is invoked many, many times, but always starts the search from `head` even though we know we are searching the buffer sequentially and therefore don't always have to start from scratch.

Are there any plans to make this smarter? Are there any plans to abandon this altogether and go for something like Rabin-Karp or something similar?

**Comment by swankjesse** [comment]
This is a bug. It should be either `O(N * M)` or `O(N)`, depending on how much up-front overhead we're willing to tolerate. Maybe we could have two implementations internally, and switch from "fast-to-start O(N*M)" to "linear O(N)" when we cross some boundary like 2 KiB.

Boyer-moore is what I'd reach for, but I don't know Rabin-Karp.

This seems like it'd be fun to hack on. I'll take a look.

**Comment by JanecekPetr** [comment]
Oh, I didn't actually expect a KMP or Boyer-Moore for, because of, you know, one or two methods in an IO library. However, yes, that's the way to go, for sure. I actually suggested Rabin-Karp as it's easier to implement (I think), but is definitely not as efficient as Boyer-Moore.

Anyway, even if it's possible to quickly fix the current naive search (maybe by an internal `indexOf(byte target, long offset, Segment lastScannedSegment)` or making Segments more clever in general) before implementing something really efficient, that's be very helpful.

**Comment by swankjesse** [comment]
First step: https://github.com/square/okio/pull/201

**Comment by swankjesse** [comment]
Fixed. https://github.com/square/okio/pull/203
