### ISSUE TITLE
JavaDoc of BufferedSource.indexOfElement(ByteString) is misleading

### ISSUE THREAD

**Issue by JanecekPetr** [square/okio#172]
By just reading the JavaDoc, it's not very apparent that it looks for any byte of `target`. Maybe it'd be worth it to rephrase

> Returns the index of the first byte in `targetBytes` in the buffer.

to

> Returns the first index of any byte from `targetBytes` in the buffer.

...or something similar, preferably with an example?

**Comment by swankjesse** [comment]
Send a PR!

**Comment by JanecekPetr** [comment]
I will, thank you! For clarification - renaming/removing/(moving to a helper class) the method is out of question? The name itself isn't helpful (unless there's some hidden logic behind it that I can't see?) and I didn't even find any example of such method in other libraries / languages. It usually simply doesn't exist and if it does, it goes under the name of indexOfAny or similar...
So, in order to document this properly, what is the method used for, why did you need it?

**Comment by swankjesse** [comment]
It's really handy in parsers. For example, in a JSON string you can skip runs of anything but `\"`. Using `indexOfAny` is a nicer name, but it isn't worth the churn of changing it.
