### ISSUE TITLE
support for reset timeout

### ISSUE THREAD

**Issue by asg-mojtaba** [square/okio#175]

**Comment by swankjesse** [comment]
What does this mean?

**Comment by asg-mojtaba** [comment]
in some situation i want to rest countdown for timeout. Assume that in some situation i want to prevent my Source be timed out.(Or something like extension their timeout)

**Comment by swankjesse** [comment]
Interesting. Is the extension offered by the thread doing the work, or by some other thread?

**Comment by asg-mojtaba** [comment]
Probably other thread.

**Comment by swankjesse** [comment]
Currently no plans to implement this. If you’d like to build your own timeout class that does this, I’ll be curious to see how that works!
