### ISSUE TITLE
Memory compact ByteString

### ISSUE THREAD

**Issue by swankjesse** [square/okio#176]
Suppose we want to operate on 16 GiB of UTF-8 strings in a single heap. ByteString is currently bad at this because the string cache consumes a ton of memory.

**Comment by haaawk** [comment]
@swankjesse 
How about putting the string cache behind SoftReference?

Alternatively, a global LRU for those cached string could be smarter about what's worth keeping and what's not. It can be problematic in concurrent scenarios though but there are well-known solutions for concurrent queues.

Another way would be to give some sort of a TTL to those cached strings. The question is what would set the field to null when the time is up. 

Does any of this sound like a reasonable solution?

**Comment by swankjesse** [comment]
No further action on this.
