### ISSUE TITLE
Deflater.SYNC_FLUSH cannot be resolved to a type

### ISSUE THREAD

**Issue by dyglcc** [square/okio#180]

**Comment by dyglcc** [comment]
compile error ！How can I deal with this problem? Any can help me?

**Comment by swankjesse** [comment]
You gotta build with Java 7 or newer.

**Comment by dyglcc** [comment]
Thanks you!

**Comment by dyglcc** [comment]
Hi,I have updated my JDK .But it does work.JDK is 1.8,Gradle2.2.1,Any suggest?
------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_65 (Oracle Corporation 25.65-b01)
OS:           Mac OS X 10.11.2 x86_64
