### ISSUE TITLE
Update Hosted Javadoc

### ISSUE THREAD

**Issue by ericleong** [square/okio#181]
It looks like [the website](http://square.github.io/okio/) has Javadoc for `1.4.0`, and [the changelog](https://github.com/square/okio/blob/master/CHANGELOG.md) suggests that methods have been added between that version and [the current version](https://github.com/square/okio/releases), `1.6.0`.

**Comment by swankjesse** [comment]
I’ll delete the old obsolete Javadoc.
http://square.github.io/okio/1.x/okio/

**Comment by swankjesse** [comment]
Fixed. Thanks!
