### ISSUE TITLE
 http://square.github.io/okio - link referenced is broken and throws 404

### ISSUE THREAD

**Issue by harshavardhana** [square/okio#182]
![screen shot 2016-01-05 at 9 42 28 pm](https://cloud.githubusercontent.com/assets/622699/12135802/4a7f9664-b3f5-11e5-9d16-b18a89b7dfe2.png)

**Comment by harshavardhana** [comment]
![screen shot 2016-01-05 at 9 42 28 pm](https://cloud.githubusercontent.com/assets/622699/12135801/44318f9c-b3f5-11e5-870c-4dea931b465a.png)

**Comment by ericleong** [comment]
It was broken by #181 and I think the easiest fix is to use `jekyll-redirect-from` ([I had a similar issue with Backboard, actually](https://github.com/tumblr/Backboard/pull/10)).

**Comment by JakeWharton** [comment]
Yeah we'll probably just redirect to `/1.x/okio/index.html`

**Comment by swankjesse** [comment]
Fixed the source link. Thanks!
