### ISSUE TITLE
Watchdog thread is eating CPU

### ISSUE THREAD

**Issue by swankjesse** [square/okio#185]
http://stackoverflow.com/questions/34997596/abnormal-cpu-usage-okio-watchdog

**Comment by DavidEdwards** [comment]
I am able to reproduce this consistently in my current project. I haven't used OkHttp (okio) before this project. I cannot guarantee that it isn't a problem introduced by me.

I'll post an example of how I use OkHttp (okio) shortly.

**Comment by DavidEdwards** [comment]
How I am starting the trace, `onPause`:

```java
Debug.startMethodTracing("debug", 80 * 1024 * 1024); // 80 MiB trace file
new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
	@Override
	public void run() {
		Debug.stopMethodTracing();
	}
}, 30000);
```

A barebones example of how I use the library:

```java
public class Api {

	private static Api mApi = null;
	private OkHttpClient mClient = null;
	private WeakReference<Context> mContext = null;

	private final boolean mTestDelay = false;

	private static final String API_GET_USER = "http://example.com/api/userinfo.php";

	private static String VERSION_CODE = "0";
	private static String VERSION_VERSION = "1.0";

	@NonNull
	public static Api getInstance() {
		return getInstance(OTRApplication.sContext.get());
	}

	@NonNull
	public static Api getInstance(@NonNull Context context) {
		if (mApi == null) {
			mApi = new Api(context);
		}
		if(mApi.mClient == null) {
			OkHttpClient.Builder builder = new OkHttpClient.Builder();

			mApi.mClient = new OkHttpClient();

			File cacheDir = new File(context.getCacheDir(), "okhttp");
			if(!cacheDir.mkdirs()) {
				cacheDir = context.getCacheDir();
			}
			int cacheSize = 1 * 1024 * 1024; // 1 MiB
			Cache cache = new Cache(cacheDir, cacheSize);

			builder.connectTimeout(15, TimeUnit.SECONDS);
			builder.cookieJar(new NotPersistentCookieJar());
			builder.cache(cache);

			mApi.mClient = builder.build();
		}
		mApi.mContext = new WeakReference<Context>(context);

		return mApi;
	}

	public Api(@NonNull Context context) {
		try {
			PackageInfo pInfo = context.getPackageManager().getPackageInfo(context.getPackageName(), 0);
			VERSION_CODE = String.valueOf(pInfo.versionCode);
			VERSION_VERSION = pInfo.versionName;
		} catch (PackageManager.NameNotFoundException e) {
			e.printStackTrace();
		}
	}

	@NonNull
	public OkHttpClient getClient() {
		return mClient;
	}
	
	private void introduceDelay() {
		long ms = (new Random()).nextInt(5000)+2000;
		Utils.log("HTTP", "Delay of "+ms+"ms");
		Utils.sleep(ms);
	}

	private String logUrl(@NonNull String url) {
		Utils.log("API", "I::URL: "+url);
		return url;
	}
	
	@WorkerThread
	@NonNull
	public String getAccountXmlSync(@NonNull String email) {
		try {
			Request request = new Request.Builder()
					.url(logUrl(API_GET_USER)
					.build();

			Response response = mClient.newCall(request).execute();

			if(mTestDelay) {
				introduceDelay();
			}

			return response.body().string();
		} catch (IOException e) {
			Utils.log("API", "E::"+e.toString());
		}

		return "";
	}

	public void getUserAccount(@NonNull final String email, @NonNull final GetAccountTask.IAccountListener callback) {
		GetAccountTask task = new GetAccountTask(mContext.get(), callback);
		AsyncTaskCompat.executeParallel(task, email);
	}
}
```

Here is the related `AsyncTask`:

```java
public class GetAccountTask extends AsyncTask<String, Void, UserAccount> {
	private WeakReference<Context> mContext = null;
	private GetAccountTask.IAccountListener mCallback = null;

	public GetAccountTask(final Context context, final GetAccountTask.IAccountListener callback) {
		this.mContext = new WeakReference<Context>(context);
		this.mCallback = callback;
	}

	@Override
	protected void onPreExecute() {
	}

	@Override
	protected UserAccount doInBackground(String... emails) {Process.setThreadPriority(Process.THREAD_PRIORITY_BACKGROUND+Process.THREAD_PRIORITY_MORE_FAVORABLE);
		
		final String email = emails[0];
		if(TextUtils.isEmpty(email)) return UserAccount.empty();
		String xml = Api.getInstance(context.get()).getAccountXmlSync(email);
		
		return UserAccount.fromXML(xml);
	}

	@Override
	protected void onPostExecute(UserAccount result) {
		// Do stuff with result
	}
}
```

The whole sequence would start by: `Api.getInstance(context.get()).getUserAccount(email, callback);`

I also tested commenting out the OkHttp specific lines in `getAccountXmlSync` so that it only returns "". The [result is as follows in my trace view](http://imgur.com/a/vrbBf).

**Comment by DavidEdwards** [comment]
Has any clue been found to this issue?

**Comment by swankjesse** [comment]
Haven’t investigated, but will take a look soon.

**Comment by molexx** [comment]
For me it seems to be caused by proguard optimization - I get this every time (on startup the app does a lot of retrofit and picasso calls) with optimization on but it's fine with it off. 

We would much prefer our production app be built with optimization enabled.

If I use Android's proguard-android-optimize.txt config but then override it to disable every optimization option listed here:
http://proguard.sourceforge.net/manual/optimizations.html
there is no problem. If someone can suggest which of those might be causing it I'll test.

**Comment by DavidEdwards** [comment]
@molexx Are you using `-dontoptimize` or are you literally disabling each option?

**Comment by molexx** [comment]
@DavidEdwards either of those works.
I would like to try and narrow down which option is causing the problem - initially so our app can be as optimized as possible but it should give a hint towards a proper fix.

Are you using optimization too?

**Comment by DavidEdwards** [comment]
Yes, I am running tests at the moment. So far my findings correlate with yours.

**Comment by DavidEdwards** [comment]
So far I am working with:

`-optimizations !class/*,!field/*,!method/marking/*,!method/removal/*,!code/removal/*`

I cannot reduce it much further (creates errors in other parts of my code). Hopefully this gives an indication of where to look.

Swapping out either of these two result in a switch between bad .trace and good .trace.
`!method/marking/*` `!code/removal/*`

**Comment by molexx** [comment]
Great, thanks!

I'm down to:

    -optimizations !method/marking/static,!method/removal/parameter,!code/removal/advanced
The standard proguard-android-optimize.txt already contains `!field/*`.

**Comment by DavidEdwards** [comment]
That ProGuard config works here too. That narrowed it down further.

**Comment by DavidEdwards** [comment]
@swankjesse The optimizations above from ProGuard are causing the issue. Tested by me and Molexx. After uploading a version to my users with this change, they are also reporting their battery issues are gone.

ProGuard is definitely messing with okio somehow.

**Comment by swankjesse** [comment]
I haven’t been able to isolate the problem with ProGuard. I’ve gotten as far as building Okio with different ProGuard configurations, and visually comparing the generated bytecode, but nothing is jumping out at me as the culprit.

I’d like some help reproducing if you’re able. First configure ProGuard to disable obfuscation with `-dontobfuscate`. Next build two `.jar` files, one with the good ProGuard config and one with the bad ProGuard config. Finally send these two me, either by attaching them here or by emailing ’em confidentially. I’m `jesse@swank.ca`.

Thanks.

**Comment by DavidEdwards** [comment]
I am not certain what you mean here. If I disable obfuscation then the results will be the same won't they?

Do you mean:

1. `.jar` with a working config
2. `.jar` with a bad config

**Examples**

**Working**

-optimizations !field/*,!method/marking/static,!method/removal/parameter,!code/removal/advanced

**Not working**

-optimizations !field/*,!method/marking/static,!method/removal/parameter

**Comment by swankjesse** [comment]
Yes, please send both working and non-working `.jar` files. You can disable _obfuscation_ for both without impacting _optimization_. It’s the optimizations that are causing the behavior change.

**Comment by DavidEdwards** [comment]
Is it still remotely helpful to you without `--dontobfuscate`?

Unfortunately, I cannot bring my code to compile with that set.

@molexx perhaps you would have better luck?

**Comment by molexx** [comment]
Maybe I'm in the same place - if I add -dontobfuscate (one hyphen) then dex fails with an unhelpful error message.

That said our app has many dependencies and does a lot of retrofit and picasso calls on startup so it's difficult to narrow down what is triggering this.

To recreate this publicly I've tried proguarding Jake Wharton's u2020 demo app as it uses many of the same libraries but without success so far - something to do with Dagger I think.

**Comment by swankjesse** [comment]
@DavidEdwards @molexx I’ve spent a couple days comparing the .class files optimized by ProGuard and the class files not optimized by ProGuard and I haven’t yet found anything obviously wrong. I’m starting to think this bug only arises when the ProGuard-optimized code interacts with an ART or Dalvik VM. Could you tell me which versions of Android you’ve been able to reproduce this on? I wonder specifically if it’s ART-only, dalvikvm-only, and which versions of each.

**Comment by DavidEdwards** [comment]
I got an incredible number of crash reports relating to finalizing when this issue was a problem for me.

The error was:

```
Fatal Exception: java.util.concurrent.TimeoutException
com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
```

The reason for it was due to [long running background processes](http://stackoverflow.com/a/28708351/503508).

The reason I am mentioning this, is that this error is gone now. I assume that the watchdog was the main reason for this crash issue. I can use this to determine reasonably well which Android versions had this issue.

**Crash report 1**
```
samsung - 95%
asus - 3%
Enspert - 1%
Other… - 1%

4.4.2 - 48%
4.3 - 40%
4.2.2 - 6%
Other… - 6%
```
**Crash report 2**
```
LGE - 47%
motorola - 33%
Huawei - 13%
Other… - 7%

6.0.1 - 100%
```
**Crash report 3**
```
samsung - 81%
motorola - 8%
LGE - 7%
Other… - 4%

4 - 79%
6 - 20%
5 - 1%
```
**Crash report 4**
```
samsung - 63%
Sony - 31%
ODYS - 3%
Other… - 3%

5.1.1 - 97%
5.1 - 3%
```

So, I think that it affects all versions of Android. ART / Dalvik. 

I have personally reproduced it on Marshmallow on my Nexus 5X.

**Comment by molexx** [comment]
It recreates 100% on my test 4.2 and 5.1.1 ARM devices, and on the 6.0 x86_64 emulator. I can try more if that would be useful?

I've proguarded the Picasso sample app and a Retrofit2 sample app and neither showed the problem.

I've been unable to get a -dontobfuscate proguarded build to get through dexing.

I'll work on cutting down our app to the minimum needed to recreate.


Here's the app's dependencies: http://pastebin.com/ch4mqwtU
@DavidEdwards perhaps it's worth comparing your dependency list to mine?

**Comment by DavidEdwards** [comment]
Here is my dependencies list also: http://pastebin.com/akzdG2BH

**Comment by molexx** [comment]
Thanks. I've taken out crashlytics and gms, hasn't helped.
I am wondering if it could be multidex? That would explain why small demo apps are not having issues.

It's tricky to orchestrate as attempting to trigger multidex by adding unused libs will be undone by proguard's optimizer. I'll continue to investigate.

**Comment by molexx** [comment]
It seems proguard's `-assumenosideeffects` is the trigger. If I add it for an empty class that isn't referenced then the watchdog loop starts happening as soon as a retrofit call is made.
e.g.:
    `-assumenosideeffects class com.example.DummyClass { *; }`

Without that it works fine regardless of the optimization exclusions.

I can post a small demo app next week.

@DavidEdwards do you have any `-assumenosideeffects` statements in your config? Can you try commenting them out please?

(multidex appears to be irrelevant)

**Comment by swankjesse** [comment]
@molexx awesome!

**Comment by molexx** [comment]
Very small demo project uploaded. I've stripped out retrofit as the problem can be caused by issuing an okhttp request. Proguard is enabled in debug builds. Comment out the `-assumenosideeffects` line and it's fine.

As with other projects I've been unable to get it to dex with `-dontobfuscate` specified.

https://github.com/molexx/okiowatchdogtest

**Comment by swankjesse** [comment]
@molexx great!

**Comment by DavidEdwards** [comment]
Yes, I use it to remove various unwanted code out of production, for example:

```
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
    public static *** i(...);
    public static *** w(...);
    public static *** e(...);
}
```

What on earth could that be doing to OKIO? A bug in Proguard?

**Comment by lber19535** [comment]
I find a **NOTE** in this [manual](http://proguard.sourceforge.net/manual/troubleshooting.html)

Note: the configuration specifies that none of the methods of class '...' have any side effects
> Your configuration contains an option -assumenosideeffects to indicate that the specified methods don't have any side effects. However, the configuration tries to match all methods, by using a wildcard like "*;". This includes methods from java.lang.Object, such as wait() and notify(). Removing invocations of those methods will most likely break your application. You should list the methods without side effects more conservatively. You can switch off these notes by specifying the -dontnote option.

In [AsyncTimeout.awaitTimeout()](https://github.com/square/okio/blob/master/okio/src/main/java/okio/AsyncTimeout.java#L332), there have a wait code:
```java
AsyncTimeout.class.wait();
```
when using -assumenosideeffects with * for some class, the proguard will remove wait method from superclass.  When I modify the proguard file and use method name, all works fine.

So I think this is not a bug of okio.

**Comment by DavidEdwards** [comment]
I decided to [science](https://github.com/DavidEdwards/okiowatchdogtest/tree/master/science) @molexx [test project](https://github.com/molexx/okiowatchdogtest).

I decompiled them and I compared them. There is clearly a change being made by ProGuard due to this added ProGuard

Here is an [HTML diff](https://github.com/DavidEdwards/okiowatchdogtest/blob/master/science/report-diff.html)

Here is a [git friendly diff](https://github.com/DavidEdwards/okiowatchdogtest/blob/master/science/git.diff).

As you can see, there is a massive change in `awaitTimeout()` and a smaller change in `scheduleTimeout(AsyncTimeout, long, boolean)`.

**Comment by molexx** [comment]
Very interesting @DavidEdwards  and @lber19535 
Removing the wildcard method spec does make the problem go away.

Assuming that okio isn't trying to call .wait() on DummyClass which is not referenced or instantiated, I think this seems like a bug in proguard: -assumenosideeffects applying to classes not specified by the pattern.

**Comment by molexx** [comment]
Apparently:

https://sourceforge.net/p/proguard/discussion/182456/thread/d447d007/

this is how proguard is supposed to work: assumenosideeffects operates up the chain on superclasses and still applies to those superclasses when they are extended by other classes not covered by the spec.


So this is not an okio bug. I am happy for it to be closed.


Unlike a lot of proguard-caused Android problems though this one would be quite difficult to detect and diagnose. Would there be an efficient way for okio to detect that wait() has been removed and throw or log an error?

**Comment by DavidEdwards** [comment]
@molexx Upon which chain of superclasses? Your example project is a standalone POJO inheriting nothing. There is no chain to follow.

**Comment by molexx** [comment]
All classes implicitly inherit from Object even if not specified. Object has the method `wait()` which is removed by the wildcard method pattern.

**Comment by DavidEdwards** [comment]
Ach, of course. `Object` has `wait()`.

Well, it seems to be that general advice for using OKIO / OkHttp should be to not use `-assumenosideeffects` if that is expected behaviour. That should probably be listed promenantly on the relevant readme files.

**Comment by swankjesse** [comment]
So ProGuard’s `-assumenosideeffects` is dangerous and should not be used.

**Comment by molexx** [comment]
Definitely used with caution. Which to be fair is what the docs say. I hadn't realised that the removals affected parent classes and applied to other uses of those classes.

IMHO though it's essential in some cases such as to remove logging from production apps.

If okio wanted to be super-nice it could detect the missing wait() and log about it, but I'm not sure how that could be done performantly i.e. without reflection at runtime. Maybe once on startup?

**Comment by EricLafortune** [comment]
Molexx and DavidEdwards are correct. The option -assumenosideeffects is the only one that intentionally changes the functionality of your code, so you should use it with care. Typically:
```
-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int d(...);
    public static int i(...);
    public static int w(...);
    public static int e(...);
    public static java.lang.String getStackTraceString(java.lang.Throwable);
}
```

Do not use `-assumenosideeffects class android.util.Log { *; }`, because it includes methods like wait(), which ripples up to Object#wait() and all other implementations, and thus quietly breaks your code.

Recent versions of ProGuard explicitly print out a warning at build time if you have this wildcard in your configuration. Admittedly, the warning may be easy to miss.

Eric (developer of ProGuard)

**Comment by swankjesse** [comment]
@EricLafortune glad to hear there’s a warning. Is stripping `Object.wait()` ever safe?

**Comment by swankjesse** [comment]
No action for us to take on this.

**Comment by tomsang** [comment]
I'm using OkHttp3 based on OkIo 1.9.0 in Android 6.0 and 4.4 in Debug mode without assumenosideeffects.

The issue still happens occasionally.  Ｓｏ it seems that the issue hasn't been fixed yet.

The stack is  the almost  same as that in https://github.com/square/okio/issues/214

Maybe assumenosideeffects is implicitly used in my Android apk. Ｃｏｕｌｄ you help me know whether assumenosideeffects is used actually or not .

**Comment by swankjesse** [comment]
@tomsang are you using ProGuard?

**Comment by tomsang** [comment]
@swankjesse I'm using the debug section of following 
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.Platform
            debuggable false
        }
        debug {
            signingConfig signingConfigs.Platform
            debuggable true
        }
    }
I believe my Android studio 2.1.2  will use the debug version of Proguard.  It has no optimization .
