### ISSUE TITLE
Exception when casting Sink to BufferedSink

### ISSUE THREAD

**Issue by RezaOruji** [square/okio#188]
private void saveData(T data, Object cacheKey) throws IOException, CacheSavingException {
        Converter<T, RequestBody> requestBodyConverter = (Converter<T, RequestBody>)
                converter.requestBodyConverter(data.getClass(),data.getClass().getAnnotations(),null);
        RequestBody requestBody = requestBodyConverter.convert(data);
        FileOutputStream out = null;
        try {
            out = new FileOutputStream(getCacheFile(cacheKey));
            BufferedSink bufferedSink = (BufferedSink) Okio.sink(out);
            requestBody.writeTo(bufferedSink);
        } finally {
            if (out != null) {
                out.close();
            }
        }
    }

in above code where i cast the Sink to BufferedSink, the exception occurs 

> java.lang.ClassCastException: okio.Okio$1 cannot be cast to okio.BufferedSink
>                                                                                         at ir.smartrestaurant.robospice.persistence.retrofit.RetrofitObjectPersister.saveDataToCacheAndReturnData(RetrofitObjectPersister.java:77)
>                                                                                         at com.octo.android.robospice.persistence.CacheManager.saveDataToCacheAndReturnData(CacheManager.java:77)
>                                                                                         at com.octo.android.robospice.request.DefaultRequestRunner.saveDataToCacheAndReturnData(DefaultRequestRunner.java:266)
>                                                                                         at com.octo.android.robospice.request.DefaultRequestRunner.processRequest(DefaultRequestRunner.java:173)
>                                                                                         at com.octo.android.robospice.request.DefaultRequestRunner$1.run(DefaultRequestRunner.java:217)
>                                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
>                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                                         at java.lang.Thread.run(Thread.java:818)
>                                                                                      Caused by: java.lang.ClassCastException: okio.Okio$1 cannot be cast to okio.BufferedSink
>

**Comment by JakeWharton** [comment]
`Okio.sink` does not return a `BufferedSink`. Wrap with `Okio.buffer`.

**Comment by RezaOruji** [comment]
thanks , but how ?

**Comment by JakeWharton** [comment]
Call Okio.buffer with the Sink
