### ISSUE TITLE
WatchDog: execute timeout callbacks in another threadpool?

### ISSUE THREAD

**Issue by diegomontoya** [square/okio#189]
trimedOut.timedOut() can sometimes do i/o which is blocking in itself aka write data, close connection. Wouldn't it be better if this timedout() call be scheduled on another background thread/pool? So not to block the delay the other timeout events.

``` java
private static final class Watchdog extends Thread {
    public Watchdog() {
      super("Okio Watchdog");
      setDaemon(true);
    }

    public void run() {
      while (true) {
        try {
          AsyncTimeout timedOut = awaitTimeout();

          // Didn't find a node to interrupt. Try again.
          if (timedOut == null) continue;

          // Close the timed out node.
          timedOut.timedOut();
        } catch (InterruptedException ignored) {
        }
      }
    }
```

**Comment by swankjesse** [comment]
Tempting. I think that since many async timeouts can be handled immediately without blocking, the best behavior is to let the timeout handler spawn its own thread.

**Comment by diegomontoya** [comment]
@swankjesse Or add a big fat doc warning in AsyncTimeOut along the lines of  "all timeout callbacks are sequentially called on a single background thread. You better not do anything blocking or non-deterministic in this method." That should do the trick. =)

```java
/**
   * Invoked by the watchdog thread when the time between calls to {@link
   * #enter()} and {@link #exit()} has exceeded the timeout.
   */
  protected void timedOut() {
  }
```

**Comment by swankjesse** [comment]
The docs already say this:
```
 * <p>Subclasses should override {@link #timedOut} to take action when a timeout
 * occurs. This method will be invoked by the shared watchdog thread so it
 * should not do any long-running operations. Otherwise we risk starving other
 * timeouts from being triggered.
```
