### ISSUE TITLE
Buffer.writeString(String, Charset) throws NullPointerException instead of IllegalArgumentException

### ISSUE THREAD

**Issue by raskasa** [square/okio#191]
If the given `String` is `null`, `Buffer.writeString(String, Charset)` will throw a `NullPointerException` before it can call the `Buffer.writeString(String, int, int, Charset)` method ([source](https://github.com/square/okio/blob/master/okio/src/main/java/okio/Buffer.java#L908)).

This is a minor issue, but thought I'd mention it since most of your `null` checks throughout the code throw an `IllegalArgumentException` exception ([source](https://github.com/square/okio/blob/master/okio/src/main/java/okio/Buffer.java#L914)).

**Comment by JakeWharton** [comment]
We've actually come to prefer NPE for this case. But :+1: we'll normalize.
