### ISSUE TITLE
Buffer.snapshot(size) can return a ByteString longer than size

### ISSUE THREAD

**Issue by ksperling** [square/okio#192]
It seems this is due to reusing the internal segments of the buffer. I think the behaviour is fine, should just be documented accordingly.

**Comment by swankjesse** [comment]
Yikes, that's a severe bug. If you can provide an executable test case I'll fix this ASAP.

**Comment by ksperling** [comment]
Noticed this when checking if a buffer starts with a specified ByteString by using snapshot()... looking at the code more it seems maybe I should just iterate over the prefix bytes myself like rangeEquals() does and avoid allocating any temporary ByteStrings.
