### ISSUE TITLE
Efficient Message digest for buffers...

### ISSUE THREAD

**Issue by Lakedaemon** [square/okio#195]
Could we have efficient message digest  for Buffer ? (like updating a sha256 with the content of a buffer)

If I'm not mistaken, sha256 can be computed for a buffer by doing 
buffer.snapshot().sha256()  <-- lots of work in there
while  In the toString implementation of buffer, we have something that looks like way more efficient : 

try {
      MessageDigest md5 = MessageDigest.getInstance("MD5");
      md5.update(head.data, head.pos, head.limit - head.pos);
      for (Segment s = head.next; s != head; s = s.next) {
        md5.update(s.data, s.pos, s.limit - s.pos);
      }
      return String.format("Buffer[size=%s md5=%s]",
          size, ByteString.of(md5.digest()).hex());
    } catch (NoSuchAlgorithmException e) {
      throw new AssertionError();
    }

**Comment by swankjesse** [comment]
Yeah, good idea. I'd like something that'll work on any source or sink.

**Comment by swankjesse** [comment]
This is for sources and sinks:
https://github.com/square/okio/pull/204

Still to do is adding md5(), sha1(), and sha256() methods to Buffer.
