### ISSUE TITLE
Is there a way to have a buffer implement `getDouble()`, `writeDouble`?

### ISSUE THREAD

**Issue by weitzj** [square/okio#199]
I want to hava a byte buffer, which should be able to operate on a `double` representation.
How can I achieve this with `Buffer`? I can see methods linke `getInt()`, `getLong()`.

Are there any reasons, there is no `getDouble()` ?
Maybe I am misunderstanding something?

Do I have to wrap a `DataOutputStream` around it?
Or use `Double.longBitsToDouble() ` on `Buffer.getLong()` ?

**Comment by swankjesse** [comment]
Try this:
https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#longBitsToDouble(long)
And it's friend, doubleToLongBits().

**Comment by weitzj** [comment]
Thank you.

**Comment by weitzj** [comment]
Ah. Kotlin is so much fun. :)

Here my final solution with extension functions on `Buffer` itself:

```
inline fun Buffer.sizeDouble(): Long {
    return size() * java.lang.Byte.SIZE / java.lang.Double.SIZE
}

inline fun Buffer.readDoubleLe(): Double {
    return java.lang.Double.longBitsToDouble(readLongLe())
}

inline fun Buffer.writeDoubleLe(value: Double): Buffer {
    return writeLongLe(java.lang.Double.doubleToLongBits(value))
}
```
