### ISSUE TITLE
Sending big files hang on socket write

### ISSUE THREAD

**Issue by jianghaolu** [square/okio#200]
Initially I thought this is similar to https://github.com/square/okhttp/issues/2122 but looks like it isn't.

Calling from Retrofit:
```java
interface UploadService {
    @Headers("Content-Type: application/octet-stream")
    @PUT("uploadfile")
    Call<ResponseBody> uploadFileViaBody(@Body RequestBody fileContent);
}

File file = new File("some_file_bigger_than_512k");
Call<ResponseBody> call = service.uploadFileViaBody(RequestBody.create(MediaType.parse("application/octet-stream"), file ));
call.execute();
```

It keeps calling `out.write(head.data, head.pos, toCopy);` successfully in Okio.java until at some point it just hangs until timeout is hit.

The issue only appears with files bigger than 512k. Extending the timeout helps but with files > 800k I need more than 2 minutes timeout which I can't bear with.

Turning on Fiddler magically solves it.

**Comment by swankjesse** [comment]
I recently merged a fix: https://github.com/square/okio/pull/196

Could you attempt with a recent snapshot to see if this is still an issue?

**Comment by jianghaolu** [comment]
Looks like an express server issue :( 

But thanks for replying :) That fix is helpful too.

**Comment by Andy-Ho-GotIt** [comment]
sorry, i am using retrofit 2.0.0, but the bug still happen, what is the release version of retrofit that fix this bug
