### ISSUE TITLE
Add convenience method for other java floating-point types(float, double)

### ISSUE THREAD

**Issue by lkishor** [square/okio#202]
It would be great if BufferedSource & BufferedSink would have methods for reading and writing float & doubles as

`float readFloat()`
`float readFloatLe()`
`double readDouble()`
`double readDoubleLe()`

`writeFloat(float v)`
`writeFloatLe(float v)`
`writeDouble(double v)`
`writeDoubleLe(float v)`

I need these methods, as I am trying to read from a Persistent Socket connection which transfers byte[].
And now for reading a float I have to write
`float val = ByteBuffer.wrap(data.readByteArray(4)).order(ByteOrder.LITTLE_ENDIAN).getFloat()`

which at the least is a lot of code instead of `data.readFloatLe()`

and as per my understanding involves **multiple copying of byte[]** (memory allocation stuff), which is what I was trying to avoid by using OKIO

**Comment by JakeWharton** [comment]
Can you do Float.intBitsToFloat(data.readIntLe()) and
Double.longBitsToDouble(data.readLongLe()) ?

**Comment by lkishor** [comment]
that's great, thank you for the quick response..
