### ISSUE TITLE
ArrayIndexOutOfBoundsException when SSL connection

### ISSUE THREAD

**Issue by jakubzieba** [square/okio#221]
Hi i notice crash in library Okio, details http://crashes.to/s/d1da98d2736. I think in such case should be thrown another kind of exception.

**Comment by swankjesse** [comment]
My guess is that you’ve got a concurrency problem. Are you ever reading or writing streams from multiple threads concurrently? Also can you please provide an executable test case to reproduce this?

**Comment by jakubzieba** [comment]
Hi, never because i use Okio indirectly by OKHttp, so i don't manually read/write on streams. Furthermore i call client.newCall(request).execute() only from one thread. Maybe OKHttp have some concurrence problem?

**Comment by jakubzieba** [comment]
I can't provide test executable because this problem occurs randomly.

**Comment by swankjesse** [comment]
Any information on which devices this impacts?

**Comment by swankjesse** [comment]
This is interesting:
http://stackoverflow.com/questions/34942269/downloadmanager-illegalstateexception-creating-a-download-in-directory-downloads

**Comment by jakubzieba** [comment]
Device: gi_i9500_tmmars (i guess its Samsung device). More details you can find under http://crashes.to/s/d1da98d2736 (crash report)

**Comment by swankjesse** [comment]
@jakubzieba if this is just happening on one device, I’m going to assume that it’s a lousy device, possibly with sketchy software. If you see it on common devices, please let me know & we’ll investigate.

**Comment by jakubzieba** [comment]
Ok, thanks for the help.

**Comment by antoinerousseau** [comment]
`GI-I9500_TMMARS` is a [software from Trend Micro](http://stackoverflow.com/a/34942270/1052033), thus:
> It is extremely likely that the system is not behaving as the App expects it to, simply because it is a threat detection environment.

Now, my stack trace shows an error coming from `okio.Okio$2.read (Okio.java:138)`:

	java.lang.ArrayIndexOutOfBoundsException: length=8192; regionStart=0; regionLength=-1
	java.util.Arrays.checkOffsetAndCount (Arrays.java:1719)
	java.io.FileOutputStream.write (FileOutputStream.java:186)
	java.util.MarsUtils.write (MarsUtils.java:33)
	com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read (OpenSSLSocketImpl.java:704)
	okio.Okio$2.read (Okio.java:138)
	okio.AsyncTimeout$2.read (AsyncTimeout.java:238)
	okio.RealBufferedSource.request (RealBufferedSource.java:66)
	okio.RealBufferedSource.require (RealBufferedSource.java:59)
	okio.RealBufferedSource.readByte (RealBufferedSource.java:72)
	okhttp3.internal.ws.WebSocketReader.readHeader (WebSocketReader.java:115)
	okhttp3.internal.ws.WebSocketReader.processNextFrame (WebSocketReader.java:104)
	okhttp3.internal.ws.RealWebSocket.readMessage (RealWebSocket.java:97)
	okhttp3.ws.WebSocketCall.createWebSocket (WebSocketCall.java:152)
	okhttp3.ws.WebSocketCall.access$000 (WebSocketCall.java:41)
	okhttp3.ws.WebSocketCall$1.onResponse (WebSocketCall.java:97)
	okhttp3.RealCall$AsyncCall.execute (RealCall.java:126)
	okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
	java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
	java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
	java.lang.Thread.run (Thread.java:818)

Any idea why okio whould crash on this virtual device? (I'm using React Native)

**Comment by swankjesse** [comment]
Notice there’s a class `MarsUtils` in the stacktrace. This class isn’t present in standard devices. You can ignore this error. I’ve attempted and failed to get TrendMicro to fix their stuff.
https://github.com/square/okhttp/issues/2976
