### ISSUE TITLE
Add convenience methods for non-UTF-8 decoding

### ISSUE THREAD

**Issue by raskasa** [square/okio#222]
`BufferedSource` has the following convenience methods for UTF-8 decoding:

```java
BufferedSource.readUtf8Line()
BufferedSource.readUtf8LineStrict()
```

Do you have any interest in adding the below convenience methods for decoding in other character sets?

```java
BufferedSource.readStringLine(Charset)        // or #readLine(Charset)
BufferedSource.readStringLineStrict(Charset)  // or #readLineStrict(Charset)
```

**Comment by swankjesse** [comment]
That's pretty tricky to do in general actually. For example it'd need to scan for an aligned four-byte sequence in UTF-32 and an aligned two byte sequence in UTF-16.

We really think everyone should be using UTF-8 exclusively. If you aren't, you'll probably be best with BufferedReader.

**Comment by raskasa** [comment]
Got it - thanks.  I want to understand a little more about the implementation difficulties.

Do you have any resources that you can link me to?

**Comment by swankjesse** [comment]
You could read the sources of the Java InputStreamReader code to see how it does it.

**Comment by raskasa** [comment]
Sounds good.  Thanks.
