### ISSUE TITLE
RandomSource ?

### ISSUE THREAD

**Issue by swankjesse** [square/okio#228]
It’d be interesting to offer a `Source` that pulls an unlimited stream of data from calls to `Random.nextBytes()`.

Sadly our sources are never threadsafe, so we couldn’t offer a `public static final Source RANDOM` which would otherwise be kinda cute. Or even better, `public static final BufferedSource RANDOM`, which would permit nice utilities like this: `RANDOM.readByteString(20).base64()`

**Comment by JakeWharton** [comment]
Depending on how clever you want to be it could delegate to a thread local
internally.

**Comment by swankjesse** [comment]
We use one in DiskLruCache to accept output when the filesystem is unwriteable. I had a use today when writing tests. I don’t necessarily think it’s worth the API bloat cause it’s pretty straightforward to write, but it’s a thing to consider.

**Comment by swankjesse** [comment]
Yeah, but as soon as you try to put a BufferedSource in front of it, things get weird.

**Comment by JakeWharton** [comment]
Yeah I meant a thread local implementation of BufferedSource which
delegated. Annoying to write, surely.

**Comment by swankjesse** [comment]
Upon further investigation this gets pretty unsatisfying very quickly. Either the caller needs to provide the Random, or we need policy. Also randoms want to use thread locals for high throughput. I’m going to punt on this for now.

Someday I would still like `ByteString.secureRandom(24L)` or something.
