### ISSUE TITLE
Blackhole

### ISSUE THREAD

**Issue by swankjesse** [square/okio#229]
We have a NULL_SINK in Okio that accepts bytes but doesn’t do anything with ’em. Seems like something that would be generally useful. Maybe `Okio.blackhole()` ?

**Comment by JakeWharton** [comment]
For JMH? What does this afford over just skipping?

**Comment by swankjesse** [comment]
We use one in DiskLruCache to accept output when the filesystem is unwriteable. I had a use today when writing tests. I don’t necessarily think it’s worth the API bloat cause it’s pretty straightforward to write, but it’s a thing to consider.

**Comment by pawatzaza** [comment]
ok

**Comment by JakeWharton** [comment]
> What does this afford over just skipping?

Consuming sources of unknown length. Use case: hashing something and not caring about the actual data.
