### ISSUE TITLE
Buffer.exhaused() will block?

### ISSUE THREAD

**Issue by FlyClover** [square/okio#238]
According to the documentation, calling Buffer.exhaused() "will block until there are bytes to read or the source is definitely exhausted". But from the implementation, it only checks whether size is equal to 0 and returns immediately.

**Comment by swankjesse** [comment]
Take a look at RealBufferedSource? We have two implementations of that interface. Buffer doesn't need to block because if it's empty it'll stay empty.

**Comment by pawatzaza** [comment]
c
