### ISSUE TITLE
ByteString decode/encode custom charset

### ISSUE THREAD

**Issue by djodjoni** [square/okio#248]
ByteString currently can be created by encoding string using only UTF-8 charset, also decoding underlying byte array can be done using again only UTF-8 charset, which means in order to use another charset for decoding one needs to allocate another clone of byte[] and then decode this array.

Are you willing to extend this functionality or stick to utf-8 only?

**Comment by swankjesse** [comment]
You can do it manually with String. We really like UTF-8 and look forward to a time when that's the only charset you need.

**Comment by djodjoni** [comment]
I am looking forward this bright future as well :)
It is of course possible to use String but this will add more wrapper code and create otherwise unnecessary memory allocations to clients.

So you prefer to keep it simple and not to add something like "getString(java.nio.charset.Charset charset)" and extend its "ergonomic-ability" ?

**Comment by swankjesse** [comment]
Yeah, we could use an API for that. encodeString/decodeString ?

**Comment by djodjoni** [comment]
yea, looks good to me
