### ISSUE TITLE
GzipSource does not support reading a source larger than 2GB 

### ISSUE THREAD

**Issue by joshzana** [square/okio#250]
We use OKHttp to download files, and recently hit a failure downloading large files, which we traced back to this exception:
```
java.io.IOException: ISIZE: actual 0x7fffffff != expected 0xc0000000
0 = {StackTraceElement@10289} "okio.GzipSource.checkEqual(GzipSource.java:205)"
1 = {StackTraceElement@10290} "okio.GzipSource.consumeTrailer(GzipSource.java:174)"
2 = {StackTraceElement@10291} "okio.GzipSource.read(GzipSource.java:92)"
3 = {StackTraceElement@10292} "okio.RealBufferedSource$1.read(RealBufferedSource.java:371)"
4 = {StackTraceElement@10293} "java.io.FilterInputStream.read(FilterInputStream.java:118)"
5 = {StackTraceElement@10294} "java.io.InputStream.read(InputStream.java:162)"
```

The line in question is:
```
    checkEqual("ISIZE", source.readIntLe(), inflater.getTotalOut());
```

`getTotalOut()` has the following [javadoc](
https://docs.oracle.com/javase/7/docs/api/java/util/zip/Inflater.html#getTotalOut()):
> Since the number of bytes may be greater than Integer.MAX_VALUE, the getBytesWritten() method is now the preferred means of obtaining this information.

The [Gzip RFC](https://www.ietf.org/rfc/rfc1952.txt) has this to say:

>         ISIZE (Input SIZE)
            This contains the size of the original (uncompressed) input
            data modulo 2^32.

`GzipSink` likely has the same issue, as it is using `getTotalIn()` but I don't have a repro of that.

**Comment by swankjesse** [comment]
Any idea which gzip encoder you’re using on the other end? I attempted to reproduce this with `GzipOutputStream` on Java 7 and it encodes the size mod 2^31 in its `ISIZE`. Since both the `Inflater.getTotalOut()` value _and_ the gzip’s `ISIZE` are truncated, it doesn’t fail.

**Comment by swankjesse** [comment]
[RFC 1952](https://tools.ietf.org/html/rfc1952#section-2.2) says that `ISIZE` is modulo 2^32. It looks like when there’s an overflow `Inflater.getTotalOut()` returns `Integer.MAX_VALUE` in some environments and wraps on others.

```
         ISIZE (Input SIZE)
            This contains the size of the original (uncompressed) input
            data modulo 2^32.
```

We can fix our code to just use `getBytesWritten()` unconditionally.

**Comment by swankjesse** [comment]
AOSP is also broken.
https://code.google.com/p/android/issues/detail?id=219964

**Comment by joshzana** [comment]
Sweet!  Not sure which encoder we are using on the other end, but our requests are terminated with nginx, so it 's possible that's where the gzip is happening
