### ISSUE TITLE
Add MacSink and MacSource

### ISSUE THREAD

**Issue by tmarsteel** [square/okio#254]
I currently need a `MacSink` and a `MacSource`. Are these currently planned? If not, i'd create a pull request within the next days containing the code i am about to write...

**Comment by swankjesse** [comment]
Nothing in flight but it makes sense. Could we reuse HashingSink and HashingSource?

**Comment by swankjesse** [comment]
I'm specifically interested in keeping our APIs small. Maybe we make HashingSource abstract, and have two non-public implementations, one that uses MessageDigest, and the other that uses Mac.

**Comment by tmarsteel** [comment]
What about this?

```java
public class AccumulatorCalculationSink<T> extends ForwardingSink {
	
	private Accumulator<? extends T> accumulator;
	
	public AccumulatorCalculationSink(Sink forwardSink, Accumulator<? extends T> accumulator) {
		super(forwardSink);
		
		this.accumulator = accumulator;
	}
	
	@Overwrite
	public void write(Buffer buffer, int nBytes) {
		byte[] data = buffer.readByteArray(nBytes);
		accumulator.add(data, 0, nBytes);
	}
	
	public T result() {
		return accumulator.result();
	}
	
	public interface Accumulator<T> {
		public static void add(byte[] data, int offset, int len);
		public static T result();
	}
}

// vice-versa for Source
```

And then have a HashingAccumulator, MacAccumulator to do the work; maybe add some factory methods to Okio?

**Comment by swankjesse** [comment]
I don't think we need hardly any new public APIs. Maybe just new methods like this?

```
public class HashingSource {
  public static Source sha1Mac(Key key)
  public static Source sha256Mac(Key key)
  public static Source md5Mac(Key key)
  ...
}
```

**Comment by tmarsteel** [comment]
And these would return package-private MacSource objects?

**Comment by swankjesse** [comment]
Exactly!
