### ISSUE TITLE
Reset on Buffer and/or Source

### ISSUE THREAD

**Issue by bfincher** [square/okio#26]
There should be a mark / reset on the Buffer and/or Source objects.  For example, I read a few bytes from a socket and then analyze those bytes to determine how many further bytes to ready.  I want the consumer of my Buffer to receive all of the read bytes but the Buffer's internal offset has been moved as a result of my examining the initial bytes.

**Comment by heinrichreimer** [comment]
> That said, I think we need a solution to the mark/reset problem, even if it doesn't use the same broken mechanism as InputStream.

Indeed this would be a very useful feature and could probably be used to help solving #255 / mirroring `Sources`.

**Comment by NightlyNexus** [comment]
icymi, #360

**Comment by swankjesse** [comment]
Yay. Direct link:
https://github.com/square/okio/blob/master/samples/src/main/java/okio/samples/SourceMarker.java
