### ISSUE TITLE
CipherSink/CipherSource

### ISSUE THREAD

**Issue by cketti** [square/okio#260]
What are your thoughts on CipherSink and CipherSource analogous to CipherInputStream/CipherOutputStream? Is that something that would be included in Okio or should it go into a separate library?

**Comment by swankjesse** [comment]
The cipher streams are pretty hazardous to use directly – it’s so easy to do the IV or MAC wrong and write broken crypto. I’d prefer to recommend specific high-level abstractions like TLS. Is there a good format for encrypting data at rest? GPG?

**Comment by cketti** [comment]
Fair enough. It's probably a good idea not to include foot guns.

TLS and OpenPGP both come with enough parameters that using them isn't as risk-free as one would hope. Still, better than rolling your own cryptosystem.

However, I'll soon need CipherSource/CipherSink to create an implementation of a proprietary crypto system. It'll be a separate library with a big fat warning message then.

**Comment by erickok** [comment]
For future visitors that are interested, I have a CiperSource/CipherSink implementation (as well as Base64Source/Sink) on https://github.com/erickok/okio-extensions which, without warrety, might help you out.
