### ISSUE TITLE
Add website like OkHttp and Retrofit

### ISSUE THREAD

**Issue by jaredsburrows** [square/okio#268]
This would be nice to have :)

http://square.github.io/okhttp/
http://square.github.io/retrofit/

**Comment by castellanprime** [comment]
Hi. First time-contributor here. Could I take this task? Thanks.

**Comment by swankjesse** [comment]
I don't think this is a good fit for a new contributor. I'm very particular about these things.

**Comment by jaredsburrows** [comment]
@swankjesse Would be just like okhttp and retrofit but with a different color?

**Comment by swankjesse** [comment]
It's the text I'm concerned with.

**Comment by jaredsburrows** [comment]
@swankjesse Let me know what you want. I posted this October of last year. I can help with the PR.

**Comment by castellanprime** [comment]
@swankjesse @jaredsburrows Is there any task on the issue list that I could help with if I cannot help with the website? On the website for okio, I have experience with bootstrap websites so I could be of assistance if you want. Thanks.

**Comment by swankjesse** [comment]
Thanks for volunteering @castellanprime! Right now I’m pretty happy with the feature set, and API. I’d love to further optimize it for real-world applications. I’m not quite sure what’s involved here. We got a nice improvement when we optimized our UTF-8 encoder. I suspect there are other cases where we’re being inefficient (too many / too few segments). It’s a decent amount of work to find these.

**Comment by jaredsburrows** [comment]
@swankjesse my original idea of me creating this was to create a `gh-pages` for this repo just like you did for http://square.github.io/okhttp/ and http://square.github.io/retrofit/.

**Comment by swankjesse** [comment]
No action to take on this. I might do a website, but only if I can come up with some tight explanations to put with it.
