### ISSUE TITLE
okio is getting slow when use GSM, HSDPA Network type in Android Emulator

### ISSUE THREAD

**Issue by DanielWorld** [square/okio#271]
If I set Android Enmulator's Network type as FULL or LTE, it is quite fast!
But if I select HSDPA (3G) Network type, it gets slower and GSM network time throw Socket Timeout Exception on Okio 1.11.0!

**Comment by swankjesse** [comment]
Presumably the 3G Network type exists to throttle your network, so I consider this to be working as designed.
