### ISSUE TITLE
Make the Segment class public 

### ISSUE THREAD

**Issue by fabienrenaud** [square/okio#273]
I had to write a custom Source almost identical to the implementation in Okio.source(InputStream,Timeout), except, I didn't want to the close method to do anything such as I could reuse the input streams...

Unfortunately, the Segment class the implementation uses isn't public and I was forced to move my custom Source implementation to a made-up local okio package.

Please make the Segment class public such as devs are free to choose where to put their custom implementations of Okio interfaces.

**Comment by swankjesse** [comment]
Why not delegate to the built-in Source class? Making `Segment` public would make it public API, which would make it difficult to make certain types of optimizations in the future.

**Comment by fabienrenaud** [comment]
Because I want to reuse my InputStream using the reset() function which I can't do if the stream is closed, which the built-in Source always do (always closes).
See here https://github.com/fabienrenaud/java-json-benchmark/blob/moshi/src/main/java/okio/ReusableSource.java#L38 and here https://github.com/fabienrenaud/java-json-benchmark/blob/moshi/src/main/java/com/github/fabienrenaud/jjb/data/JsonSource.java#L96 (+ line  83).

> Making Segment public would make it public API, which would make it difficult to make certain types of optimizations in the future.

If you really worry about that (which isn't a problem if you accept releasing non-backward compatible versions of okio and versionize the lib properly), I could live with an interface for Segment, all I need after all is this:

    Segment tail = sink.writableSegment(1);
    int maxToCopy = (int) Math.min(byteCount, Segment.SIZE - tail.limit);
    int bytesRead = in.read(tail.data, tail.limit, maxToCopy);
    if (bytesRead == -1) {
        return -1;
    }
    tail.limit += bytesRead;

so data(), limit() and incLimit(int) + the SIZE constant.

IMO, public + future non-backward compatible optimizations is just fine.

**Comment by swankjesse** [comment]
What about this?

```
    Source nonClosingSource = new ForwardingSource(source) {
      @Override public void close() throws IOException {
      }
    };
```

**Comment by JakeWharton** [comment]
Why not wrap the stream and suppress close instead?

**Comment by fabienrenaud** [comment]
That seems acceptable. I think I can live with that.
Thanks. :)
