### ISSUE TITLE
Question, will read operation wait?

### ISSUE THREAD

**Issue by wu-sheng** [square/okio#276]
Hello, I have just known this repo. I like its api style, if I use `readInt` or `readFully` from a file input stream, at the same time, another thread is using outputstream to write this file.
Maybe, reading is faster than writing, will `readInt` or `readFully` wait, until there is enough data? 

```java
    int length = pngSource.readInt();
    String type = pngSource.readUtf8(4);
    pngSource.readFully(chunk, length);
    int crc = pngSource.readInt();
```

**Comment by swankjesse** [comment]
Don’t read a file that you’re actively writing; that won’t work. Instead consider copy-pasting Relay into your program. 
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/cache2/Relay.java

**Comment by wu-sheng** [comment]
**okio** should focus on the file is permanent, and wait for reading? Am I correct? 
Does that mean, if I readFully with an outOfRange length, it will trigger exception?

**Comment by swankjesse** [comment]
I'm not sure. The reader isn't going to wait for the writer though.
