### ISSUE TITLE
EOFException on okio

### ISSUE THREAD

**Issue by crossle** [square/okio#286]
Sometimes it ok, but always throw

                         E  java.io.EOFException
                         E      at okio.RealBufferedSource.require(RealBufferedSource.java:59)
                         E      at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
                         E      at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
                         E      at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
                         E      at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
                         E      at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
                         E      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                         E      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                         E      at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
This just looks like the underlying connection has died/closed. What makes you think it's an Okio bug?

**Comment by crossle** [comment]
look like https://github.com/square/okhttp/issues/3113
