### ISSUE TITLE
NullPointerException:Attempt to invoke virtual method 'okio.Timeout okio.Timeout.timeout(long, java.util.concurrent.TimeUnit)' on a null object reference

### ISSUE THREAD

**Issue by devinhu** [square/okio#289]
Caused by: java.lang.NullPointerException:Attempt to invoke virtual method 'okio.Timeout okio.Timeout.timeout(long, java.util.concurrent.TimeUnit)' on a null object reference
1	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:107)
2	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
3	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
4	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
5	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
6	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
7	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
8	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
9	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
11	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
13	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
14	at okhttp3.RealCall.access$100(RealCall.java:33)
15	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
16	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
17	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
18	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
19	at java.lang.Thread.run(Thread.java:818)

okhttp version 3.3.1  
okie version 1.8.0

**Comment by swankjesse** [comment]
Can you reproduce this with the latest OkHttp and Okio? Test case would be great.

**Comment by JakeWharton** [comment]
This is an OkHttp bug, not Okio.

**Comment by devinhu** [comment]
thanks. I just want to make sure that the following questions are OKhttp's Bug? Because I can't reproduce the problem, can't it be our problem or Okhttp? Is there a problem with the latest version?

Caused by: java.lang.NullPointerException:Attempt to invoke virtual method 'okio.Timeout okio.Timeout.timeout(long, java.util.concurrent.TimeUnit)' on a null object reference

Caused by: java.lang.NullPointerException:Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
---at okhttp3.internal.http.StatusLine.parse(StatusLine.java:51)

Caused by: java.lang.NullPointerException:Attempt to invoke interface method 'okio.BufferedSink okio.BufferedSink.writeUtf8(java.lang.String)' on a null object reference
---at okhttp3.internal.http.Http1xStream.writeRequest(Http1xStream.java:167)

Caused by: java.lang.NullPointerException:Attempt to read from field 'okhttp3.Request okhttp3.internal.cache.CacheStrategy.networkRequest' on a null object reference
---at okhttp3.internal.cache.CacheStrategy$Factory.get(CacheStrategy.java

okhttp version 3.3.1
okio version 1.8.0

**Comment by SnakeEys** [comment]
I have the same Exception as @devinhu on okhttp 3.2.0, okio 1.8.0.

**Comment by swankjesse** [comment]
@devinhu which version are you using? Is it still a problem on 3.6.0?
