### ISSUE TITLE
Write some examples of how to open a binary file from /res/raw?

### ISSUE THREAD

**Issue by mikelupo** [square/okio#291]
It would be helpful if OKIO developers could write up some examples of how to fill a Buffer object with the bytes from a raw resource, such as a .png, .jpg, .mp4, etc.
Likewise, from the SD Card. 

Would be very useful for http/https mocking as used by okhttp3 mocking. The okhttp3 responses use your OKIO Buffer as an input.

Thanks in advance.

**Comment by JakeWharton** [comment]
Android gives you those as an `InputStream` so you can write `Okio.source(is)` to create a `Source` and then `Okio.buffer(source)` to create a `BufferedSource`. If you need an actual `Buffer`, create a new one and then call `buffer.writeAll(source)` to write the entire source into the buffer.

**Comment by mikelupo** [comment]
Jake, that is helpful. If I get my tests working, perhaps I can write up an example to share.

**Comment by mikelupo** [comment]
@JakeWharton. I tried what you recommended, but the buffer would always be 0 bytes in size. 
This is what I ended up doing. In my modified example (below) the buffer size = that of the file size itself. Because they are equal in size, I am assuming that the Buffer object is correct. Your input is welcome.

    public static Buffer getRawBinaryResourceAsBuffer(Context context, int resourceId) throws     IOException {
        Buffer buffer = new Buffer();
        InputStream ins = context.getResources().openRawResource(resourceId);
        Source source = null;
        BufferedSource bufferedSource = null;

        try {
            ByteArrayOutputStream outputStream=new ByteArrayOutputStream();
            int size = 0;

            // Read the entire resource into a local byte buffer.
            byte[] fileData = new byte[1024];
            while((size=ins.read(fileData,0,1024))>=0){
                outputStream.write(fileData,0,size);
            }
            //now store it in a byte array
            fileData=outputStream.toByteArray();
            
            //fill the buffer object.
            buffer.write(fileData);

            //write the byteArray to the buffer.
            //source = Okio.source(ins);

            //if you need a bufferedSource...
            //bufferedSource = Okio.buffer(source);

            //Log.d(TAG, "BUFFEREDSOURCE BUFFER SIZE IS: "+bufferedSource.buffer().size());
            Log.d(TAG, "FILEDATA LENGTH SIZE IS: "+fileData.length);
            Log.d(TAG, "OKIO BUFFER SIZE IS: "+buffer.size());
        } catch (Resources.NotFoundException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        } finally {
            ins.close();
        }
        Log.d(TAG, "getRawBinaryResourceAsBuffer is returning a buffer of size: "+ buffer.size());
        return buffer;
    }

**Comment by swankjesse** [comment]
I think you just want this.
```
    BufferedSource bufferedSource = Okio.buffer(Okio.source(
        context.getResources().openRawResource(resourceId)));
```
