### ISSUE TITLE
Error when running android: duplicate entry: okio/AsyncTimeout$1.class

### ISSUE THREAD

**Issue by liuzhen2008** [square/okio#296]
I just recently added an intel video chat library into `./libs`, and then added 

`compile files('./libs/intelVideoChat.jar')`

In my app, I have always had the package

`compile 'com.squareup.okhttp:okhttp:2.3.0'`

I notice that once I added the intel stuff into my app, i start running into the problem duplicate entry: okio/AsyncTimeout$1.class that breaks build.

What are some of the ways I can do to resolve it?

Thanks

**Comment by swankjesse** [comment]
If the IntelVideoChat library is embedding Okio, then it should use [jarjar](https://github.com/shevek/jarjar) to prevent that dependency from colliding with your own version of Okio. You should suggest this to them!
