### ISSUE TITLE
Bytes go missing randomly

### ISSUE THREAD

**Issue by Philipp91** [square/okio#304]
I have the following setup: Gson/Retrofit -> OkHttp -> okio -> Android 7.0 in an emulator -> PHP7 running on the same host machine with Windows 7.

My request returns a JSON response, usually around 30k bytes. When executed quickly one after another, some responses lack a single byte. Mostly, this is the very last byte, a closing `}` for the outer JSON object, resulting in a
```
java.io.EOFException: End of input at line 1 column 27011 path $.items
  at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393)
```

Occasionally, a byte from the middle is missing, resulting in exceptions like (note the missing dash in the date):
```
java.text.ParseException: Unparseable date: "201512-07T00:00:00Z"
  at java.text.DateFormat.parse(DateFormat.java:358)
```
Very rarely, multiple bytes are missing.

I have a webapp running in Chrome that queries the exact same webserver and both run the exact same queries. I have the server log the responses it sends and they match exactly. But whereas Chrome always receives all bytes, the responses logged by the `okhttp3.logging.HttpLoggingInterceptor` sometimes lack a byte.

What I tried without success:
- disable antivirus/firewall on host machine
- `AndroidManifest.xml` -> `android:vmSafeMode="true"`
- The requests are triggered by an infinitely scrolling ListView - thus by construction I can ensure that no two requests are running at the same time.

I'm not sure this is actually an okio bug, but any help is appreciated and okio is the closest I was able to narrow down:
I computed the exact lengths of all responses including the header length and logged the `bytesRead` values here: https://github.com/square/okio/blob/master/okio/src/main/java/okio/Okio.java#L139
Adding up these values shows that, just before the crash, okio receives one byte too few, e.g., 3*8192 bytes and then another 2619 instead of 2620.

**Comment by Philipp91** [comment]
Now I'm relatively sure that this is not caused by okio, as it also happens with HttpURLConnection. Hints are appreciated nevertheless.

**Comment by swankjesse** [comment]
Try this:
Use reflection or make a custom build of Okio to set the segment pool’s `MAX_SIZE` to 0.
https://github.com/square/okio/blob/master/okio/src/main/java/okio/SegmentPool.java

The segment pool makes it possible for thread-unsafe code to corrupt distant buffers. In particular, a thread-unsafe class might pool a segment and then write it. If another thread picks up the pooled segment, it can break in spooky ways.

Shrinking the segment pool to zero prevents thread unsafe code from polluting the heap and harming thread safe code. If this works, we know you have some thread unsafe code somewhere.

Note that HttpURLConnection also uses a bundled Okio, so it could be the same cause in either case.

**Comment by Philipp91** [comment]
Set through reflection -- no change in behavior. I put a breakpoint in the `SegmentPool.recycle()` method, which was hit, then made it conditional for `byteCount > 57344` and it wasn't hit at all anymore. So the `MAX_SIZE` value does not make a difference in this scenario.

**Comment by Philipp91** [comment]
I ran a couple more tests with different devices:
- My Windows computer is attached via LAN and has a server and two virtual devices: Marshmallow and Nougat.
- My Windows laptop can be attached via LAN or WLAN, has a server and a Nougat virtual device.
- I have a Motorola Marshmallow device attached via WLAN.

Using those devices, I tested most of the combinations (between the 4 clients and the 2 servers, laptop on LAN or WLAN). What I found is that:
- no errors occur at all over WLAN, hence no errors ever occur with the physical Moto device.
- rare errors occur when a virtual devices accesses the server on the other computer over LAN.
- many errors occur when a virtual devices accesses its own host, whether it's through the 10.0.2.2 IP or my local NAT IP.

=> The faster the connection, the more errors occur. (Where "faster" could also mean greater packet sizes or sth like that, I don't know that much about networking.)

All those experiments used the HttpURLConnection. Since I can't attach a physical device over LAN (so "fast" enough to expect erros), I can't rule out the Android emulator as the culprit.

**Comment by swankjesse** [comment]
Any chance you can reproduce with HttpURLConnection on a JVM instead of Android? That one doesn't use Okio at all.

**Comment by Philipp91** [comment]
I ran the exact same code directly on the Windows laptop that also hosts the Android emulator, using an x64 JDK 8, Update 131 (so just the latest), ran it about 20 times, no lost bytes ever. Yes, this setup doesn't use Okio at all, but it also doesn't use the Android emulator at all. Right before and after, I was able to reproduce the problem in the emulated app running against the same PHP server on the same machine. 

However, on my other machine, where I continued developing the app, the problem has disappeared. Two things have changed since then: the database (the responses now have different lengths) and the app itself (it might fire out requests faster, slower, differently, idk). I am going to bisect my changes and report here.

**Comment by swankjesse** [comment]
No clear action for us to take on this.

**Comment by mhsmith** [comment]
@Philipp91 did you learn anything more about this? I think I may be experiencing a similar issue.

**Comment by mhsmith** [comment]
I've recorded my findings at https://issuetracker.google.com/issues/150758736.

**Comment by Philipp91** [comment]
Sorry, no new insights on my end. I have a similar setup still (Android emular, PHP backend, etc.) but everything uses much newer versions now and I haven't encountered the issue anymore in a long time.
