### ISSUE TITLE
Provide consumer proguard file to avoid warnings

### ISSUE THREAD

**Issue by danepowell** [square/okio#305]
Projects must currently add `-dontwarn okio.**` to their proguard file as documented in the okio readme: https://github.com/square/okio#proguard

However, it seems like this manual step could be avoided if okio included a consumer proguard file, like ParseSDK did here: https://github.com/parse-community/Parse-SDK-Android/commit/95aa512eb44f6aac0e0ece042cd504c1ff7f9fc1

Is this a possibility?

**Comment by JakeWharton** [comment]
Okio is not an Android library and thus is a jar and not an aar and so it cannot bundle rules. If you think jars should be able to do this, file a bug at http://b.android.com for the Android tools team.
