### ISSUE TITLE
Feature/Contribution request

### ISSUE THREAD

**Issue by jtuchek** [square/okio#306]
It'd be really handy for dealing with low level protocol parsing and decoding if `Buffer` was able to read non-standard byte widths into standard java types.

For example, a protocol using only 2 bytes to represent a shortened or unsigned integer would need to be placed into a java int to accommodate the size.

I don't know how applicable this would be to a wide variety of people, or the needs your team has while maintaining the project - just wanted to get some feedback or thoughts before going down the route of a PR, fork, etc.

I would imagine an API similar to
```java
public int readInt(int byteWidth);
public int readIntLe(int byteWidth);
```

or

```java
public int readAsInt(int byteWidth);
public int readAsIntLe(int byteWidth);
```

For all other purposes, developing with okio has been a breeze!

**Comment by JakeWharton** [comment]
Related: #74
