### ISSUE TITLE
Buffer.peek(Options)

### ISSUE THREAD

**Issue by tadfisher** [square/okio#310]
It seems to me that anyone can use the exposed `rangeEquals` to implement `selectPrefix` externally, so why is this method package-private?

Main use case is to use `select` without consuming the input, guarded by `require`.

**Comment by jaredsburrows** [comment]
@JakeWharton Can we make this `public`?

**Comment by swankjesse** [comment]
This method doesn’t have particularly reusable semantics. It’s an implementation detail of `RealBufferedSource` which needs to defer reads from a buffer.

I think you probably want a method like `select()` but maybe named `peek()` ? This method would behave exactly like `select()` but without consuming the input? Ie. no special behavior if the buffer is a prefix of one of the selected strings.

**Comment by tadfisher** [comment]
Yes, `peek()` would be just what I'd want.

**Comment by bnorm** [comment]
With the new `BufferedSource.peek()` method, this could be achieved with `bufferedSource.peek().select(options)`.

**Comment by tadfisher** [comment]
Nice!
