### ISSUE TITLE
AsyncTimeout.java#L167 obscure code

### ISSUE THREAD

**Issue by NormanOu** [square/okio#311]
https://github.com/square/okio/blob/fe9abc51fb7d7ce6bf25f5f2a1d58b933734241a/okio/src/main/java/okio/AsyncTimeout.java#L167

feeling sick about this line of code
s = s.next seems taking no effect

**Comment by JakeWharton** [comment]
It traverses the linked list of segments. The next line is the issue. Should be using `s` and not `source`.

**Comment by swankjesse** [comment]
Good find! Fix is out for review!
