### ISSUE TITLE
Convert a byte array ( byte[] ) to ByteString

### ISSUE THREAD

**Issue by Wodehouse211** [square/okio#314]
I use JNI to pass file information from C++ to my Java okhttp3 Websocket client. I convert, say an image file, from a base64 string to a byte array using the standard JNI signatures. The Websocket client receives the byte array. But I couldn't find a way to convert the byte array byte[] to ByteString format so I could send from client to the server (using ws.send(ByteString) method call). The websocket.send(String) method works great. 

Is there a way I could do the required conversion? Thanks ..

**Comment by swankjesse** [comment]
`ByteString.of(byteArray)`

**Comment by chayki** [comment]
ByteString.copyFrom(byte[] bytes)
