### ISSUE TITLE
BufferedSource  method readAll  can not  limit read byte counts .

### ISSUE THREAD

**Issue by wujingchao** [square/okio#315]
Why the BufferedSource interface no method to limit byte counts that read from the source, like this:

	public long readAll(Sink sink, long byteCount) throws IOException

or BufferedSink interface no method to limit byte counts that append the sink, like this

	public long writeAll(Source source, long byteCount) throws IOException

Considering this situation， when reading fix-length byte stream from network and writing to file, but the network stream cannot read EOF because of the connection is reusing. So it wants to limit read length from network stream. But the library no API can do this. This method can cause OOM when the buffer held larger byte array:

    void readFully(Buffer sink, long byteCount) throws IOException;

I known the buffer can do this:

    while (true) {
      Buffer chunk = new Buffer();

      // Each chunk is a length, type, data, and CRC offset.
      int length = pngSource.readInt();
      String type = pngSource.readUtf8(4);
      pngSource.readFully(chunk, length);
      int crc = pngSource.readInt();

      decodeChunk(type, chunk);
      if (type.equals("IEND")) break;
    }

I just want to simply method invoke....

**Comment by cketti** [comment]
If you need to pass along parts of a stream to another consumer you probably want to use something like okhttp's [`FixedLengthSource`](https://github.com/square/okhttp/blob/d1b21e1913bd52c0d40331e3d72d0ba1b3fbb3ce/okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java#L369).

To write all of a `Source` to a `Sink`, e.g. a file, use `BufferedSink.writeAll(Source)`. That will do the right thing and not read the whole source data into memory before writing it.

**Comment by swankjesse** [comment]
Does this work?
http://square.github.io/okio/1.x/okio/okio/BufferedSink.html#write-okio.Source-long-

`BufferedSink.write(Source, long)`

**Comment by wujingchao** [comment]
@swankjesse Got it, thank you.
