### ISSUE TITLE
Resume download

### ISSUE THREAD

**Issue by shawara** [square/okio#316]
i want to resume download of files
`.header("Range", "bytes=" + downloadedFile.length() + "-")`

but i am not able to set offset read and write 

`           BufferedSink sink = Okio.buffer(Okio.sink(downloadedFile));
            sink.writeAll(response.body().source());
            sink.close();`

**Comment by swankjesse** [comment]
`Okio.appendingSink(File)` ?

**Comment by shawara** [comment]
thanks
