### ISSUE TITLE
Buffer.read/write for NIO ByteBuffer

### ISSUE THREAD

**Issue by robeden** [square/okio#318]
I've seen issue #197 regarding NIO integration but would like to request a different type of integration. In my application I have `ByteBuffer`s which feed and are fed by `Buffer`s. I would like to request the addition of `read(ByteBuffer)` and `write(ByteBuffer)` methods.

I don't think the discussion in #197 applies since this doesn't involve a hypothetical custom implementation of ByteBuffer, but rather just uses them in the same way as byte arrays are currently used.

The currently process for integrating the two libraries requires the usage of extra `byte[]`s to copy between. This could be avoided by writing directly to or reading from the underlying `Segment` data arrays. Without such methods, there is no way I can see to avoid the extra copy.

**Comment by ksperling** [comment]
Being able to read and write ByteBuffers was one of the things I was thinking of relating to #197, but also being able to e.g. expose a `MappedByteBuffer` as a `Source` directly, without having to copy into a `Buffer`.

**Comment by bnorm** [comment]
With the addition of `Buffer.UnsafeCursor`, would something [like this](https://gist.github.com/bnorm/34fffd47169fd561eb522910a655a8a7) be of use? Allows for the conversion of a ByteBuffer to a Source or Sink.

**Comment by robeden** [comment]
Thanks, @swankjesse! 👍
