### ISSUE TITLE
How to integrate okio1.3.0 directly using source codes in android studio？

### ISSUE THREAD

**Issue by minibeep** [square/okio#320]
I am trying to write a sdk which relies on okhttp and okio 1.3.0 in android studio. Rather than using "compile 'com.squareup.okio:okio:1.3.0'", I want to integrate okio 1.3.0 using SOURCE CODES. 

However, when I compile, the following files are shown to be not found 

import java.nio.file.Files;
import java.nio.file.OpenOption;
import java.nio.file.Path;

import org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement;

Any solution to this issue?
Many thanks.

**Comment by JakeWharton** [comment]
You have to compile against API 26 and include the animal sniffer annotations via `org.codehaus.mojo:animal-sniffer-annotations:1.10`.

**Comment by minibeep** [comment]
Thanks for your fast reply. However, it seems that problem is still there. Can you provide an example/sample of  buildscript? Thanks again.

**Comment by JakeWharton** [comment]
We don't support compiling in Android Studio or with Gradle so I'm afraid
that you're on your own here.

**Comment by minibeep** [comment]
Thanks anyway. Still wish you can provide the solution for android studio for your convenience, since okio is very useful for making an android SDK.
