### ISSUE TITLE
Warning:okio.DeflaterSink: can't find referenced class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

### ISSUE THREAD

**Issue by FongMi** [square/okio#327]
Android Studio 3.0.1
compileSdkVersion = 27
buildToolsVersion = '27.0.1'
supportLibraryVersion = '27.0.1'

My proguard rule

> -dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

and I build release apk get error.
I don't know why and I had reinstall android studio.

![default](https://user-images.githubusercontent.com/3471963/33117624-191649b6-cfa4-11e7-95fa-f093075738fb.PNG)

**Comment by JakeWharton** [comment]
Those rules are correct to suppress the displayed warning. If they're not, then your build is configured incorrectly and the rules are not being honored. Ensure your build is configured to correctly use your rules. Feel free to ask on StackOverflow or the Android developer tools mailing list to try and seek help for that. This isn't an issue with Okio though.

**Comment by FongMi** [comment]
Thanks @JakeWharton 
I recreate my project finally and works well.

**Comment by akashraj9828** [comment]
![sketch](https://user-images.githubusercontent.com/29796785/43217153-78c2894e-905e-11e8-8246-bfb97f2e22be.png)
minSdkVersion 17
targetSdkVersion 27

I'm getting these warnings whenever i try to build release apk 

@FongMi can you help me out how u resolved these warnings 
I was trying to find its solution but i had no luck till now

**Comment by dipskp** [comment]
Adding below lines  to the proguard will ignore these warnings and will successfully generate the signed build

-dontwarn okhttp3.**
-dontwarn okio.**

I tried this and I was able to generate signed build, but I don't know why the app kept crashing as i open it. 
Can anyone help?

**Comment by andronicus-kim** [comment]
@dipskp i'm experiencing the same problem, did you find a solution?

**Comment by vjvk** [comment]
I have resolved this error by adding below lines in proguard-rules.pro from Gradle scripts.

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**
