### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by georgi-neykov-hub** [square/okio#332]
I am occasionally spotting the following error in an application's Craslytics log:

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int okio.Segment.limit' on a null object reference
       at okio.Okio$1.write(Okio.java:78)
       at okio.RealBufferedSink.close(RealBufferedSink.java:229)
...

I could not find a similar issue posted here, so adding it here.
Contact me if anything else is needed, the Okio version used is 1.13.0

**Comment by swankjesse** [comment]
Typically this kind of exception occurs when there’s a data race; multiple threads operating on the same data simultaneously. If you could provide an executable test case, that’ll help!

**Comment by weizhizhanghao** [comment]
I think this issue is the same as https://github.com/square/okio/issues/163
