### ISSUE TITLE
SegmentPool lock is a hot spot; investigate ConcurrentLinkedDeque etc.

### ISSUE THREAD

**Issue by swankjesse** [square/okio#335]
I was running some code that was hitting the segment pool pretty hard. It looked like things were bottlenecked on the `static synchronized` lock in the pool.

Replacing the lock with a ConcurrentLinkedDeque and an AtomicLong appears to make things faster, at least in a heavily-contended situation on a JVM on a 4-core PC.

We should investigate whether a different locking mechanism in the SegmentPool improves throughput. We should also investigate tuning its size.

**Comment by galderz** [comment]
Do you need a hand with this?

**Comment by swankjesse** [comment]
No thanks! The issue as I see it is we can either lock or allocate, and I don’t think I’m ready to allocate.

**Comment by swankjesse** [comment]
Implemented a fix here:
https://github.com/square/okio/pull/717
