### ISSUE TITLE
ByteString concatenation methods

### ISSUE THREAD

**Issue by furyalex** [square/okio#341]
ByteString will benefit from simple concatenation method.

```java
final ByteString s1 = ByteString.of(1,2,3);
final ByteString s2 = ByteString.of(4,5,6);
final ByteString result = ByteString.concat(s1,s2);
assert result.equals(ByteString.concat(1,2,3,4,5,6));
```

For non-trivial cases `new Buffer().write(s1).write(s2).readByteString()` could be used, but it makes code less readable in trivial cases of concatenating 2-3 byte strings together.

Consider following alternatives
* `public static @Nonnull ByteString copyFrom(final ByteString... chunks)` + overloads for 2 and 3 parameters -- this API is similar to protobuf
* `public static @Nonnull ByteString concat(final ByteString... chunks)` + overloads for 2-3 parameters
* `public static @Nonnull ByteString of(final ByteString... chunks)` + overloads for 2 and 3 parameters
* `public @Nonnull ByteString concat(final ByteString right)` -- this is a non-static method, it may cause performance penalty when concatenating more then 2 strings

**Comment by furyalex** [comment]
I can contribute change for those methods once decided on naming.

**Comment by swankjesse** [comment]
I actually prefer the Buffer approach because it's most flexible. In particular, that API works no matter what you’re doing: concatenating ByteStrings with each other, concatenating ByteStrings with byte arrays, concatenating Buffers with each other, etc.

I don't want to add this API because I don't like the APIs we’d add in follow up.

**Comment by furyalex** [comment]
I understand that Buffer is flexible and can solve concatenation problem. It is useful for complex operations.

Downsides of using Buffer as the only way of concatenation:
* has verbose syntax: `new Buffer()`,  try-with-resources to close it, write and read operations. This makes concatenation less readable.
* hard to discover: I had to help an SDE on my team to find that solution.

Concatenation is one of important operations on strings. It should be solved by the class. We also may add a hint on using `Buffer` in javadocs of basic concat methods.

Java simplifies concatenation of regular strings with language syntax-sugar. It would be unnatural to write `new StringBuilder().append("Hello").append(" ").append("world!").toString()` each time we need to combine few strings. Unfortunately we can not rely on operators for ByteString.

Having concat methods for fixed number of arguments will also improve performance because we do not need to allocate additional objects: `Buffer` and `Segment`

**Comment by furyalex** [comment]
Which APIs you do you mean when you say you do not want to add as follow up?

**Comment by furyalex** [comment]
Adding concatenation APIs for byte strings does not implies that we will need to add overloads for bytes and buffers. `Buffer` is still there and we can add JavaDocs to concatenation methods pointing that for other cases `Buffer` class should be used.

Adding concatenation methods will make byte strings more self-contained. In my team we try to use byte strings as much as possible to emphasize immutability. So concatenation of byte strings is frequent operation, when concatenation of other types is not.

**Comment by swankjesse** [comment]
No further action on this.
