### ISSUE TITLE
How to use  okio like  RandomAccessFile 

### ISSUE THREAD

**Issue by ilpanda** [square/okio#345]
I  want  to use  okio  like  RandomAccessFile ,then I can  read and wrie to a random access file .
so  could  you  tell me   what  should  I  do ? 
such as :   I want to write some   byte[]    to  file  .

```
        try {
            RandomAccessFile randomAccessFile = new RandomAccessFile(new File(AppPathManager.getAppRootPath()), "rw");
            randomAccessFile.seek(100);
            randomAccessFile.write();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
 ```

what  should I do  with okio ?

**Comment by swankjesse** [comment]
We don’t have anything at the moment. There’s one experiment in OkHttp that uses FileChannel for something similar.
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/cache2/FileOperator.java
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/cache2/Relay.java

**Comment by ilpanda** [comment]
Thank you for your reply !
