### ISSUE TITLE
Kotlin extension properties for the Okio.<...>() helper methods

### ISSUE THREAD

**Issue by heinrichreimer** [square/okio#352]
Would be nice for readability if we could use Kotlin extension properties for not having to nest the `Okio.source(...)`, `Okio.sink(...)`, `Okio.buffer(...)` methods.  
That way one could intuitively navigate to a `File`'s `BufferedSink` using `file.sink.buffered`.

@swankjesse's [Okio file copy example](https://twitter.com/jessewilson/status/529497763625455616) on Twitter would then be reduced to this:
```kotlin
from.source.use { source ->
    to.sink.buffered.use { sink ->
        sink.writeAll(source)
    }
}
```

#### Extension properties
```kotlin
val Source.buffered: BufferedSource
    get() = Okio.buffer(this)
val Sink.buffered: BufferedSink 
    get() = Okio.buffer(this)
val OutputStream.sink: Sink
    get() = Okio.sink(this)
val Socket.sink: Sink 
    get() = Okio.sink(this)
val File.sink: Sink
    get() = Okio.sink(this)
val Path.sink: Sink
    get() = Okio.sink(this)
val File.appendingSink: Sink 
    get() = Okio.appendingSink(this)
val InputStream.source: Source 
    get() = Okio.source(this)
val Socket.source: Source 
    get() = Okio.source(this)
val File.source: Source
    get() = Okio.source(this)
val Path.source: Source
    get() = Okio.source(this)
val BufferedSink.outputStream: OutputStream 
    get() = outputStream()
val BufferedSource.inputStream: InputStream
    get() = inputStream()
```

**Comment by swankjesse** [comment]
Please don't do this! Each call to buffered() creates a new Buffer, and that's both inefficient and incorrect.

**Comment by heinrichreimer** [comment]
What about extension functions instead of `Sink.buffered`/`Source.buffered` extension properties:
```kotlin
fun Source.buffer(): BufferedSource = Okio.buffer(this)
fun Sink.buffer(): BufferedSink = Okio.buffer(this)
```
That way you the code can be readable while being clear about `buffer()` returning a new `Buffer` each time it's called.

Don't get me wrong, I know that one should not write something like this:
```kotlin
val sink = ...
sink.buffered.write(...)
sink.buffered.write(...)
sink.buffered.write(...)
```
... but rather this
```kotlin
val sink = ...
val bufferedSink = sink.buffered
bufferedSink.write(...)
bufferedSink.write(...)
bufferedSink.write(...)
```

**Comment by heinrichreimer** [comment]
Also something like this in Kotlin:
```kotlin
@file:JvmName("Okio")

package okio

import ...

fun Sink.buffer(): BufferedSink = RealBufferedSink(this)

val File.sink: Sink
    @JvmName("sink") get() {
        return FileOutputStream(this).sink
    }

val OutputStream.sink: Sink
    @Throws(FileNotFoundException::class)
    @JvmName("sink") 
    get() {
        ...
    }
```

... would actually compile to this in Java:
```java
package okio;

import ...;

public final class Okio {
   @NotNull
   public static final BufferedSink buffer(@NotNull Sink $receiver) {
      return new RealBufferedSink($receiver);
   }

   @NotNull
   public static final Sink sink(@NotNull File $receiver) {
      return sink(new FileOutputStream($receiver));
   }

   @NotNull
   public static final Sink sink(@NotNull OutputStream $receiver) throws FileNotFoundException {
      Intrinsics.checkParameterIsNotNull($receiver, "$receiver");
      ...
   }
}

```

So when changing Okio's static utility methods to extension functions or extension properties, the Java code would still be the same, thus not breaking compatibility to older Okio versions.
Only downside I see here is that there's currently no efficient way to rename the receiver parameter name in the compiled JVM code.

**Comment by heinrichreimer** [comment]
It wouldn't be hard to transform the whole `Okio` class into a Kotlin file with extension functions/properties that would compile to the same JVM signature as the current implementation but at the same time being more readable when writing Kotlin code.  
If you'd like, I could submit a pull request.

**Comment by JakeWharton** [comment]
We don't want the dependency on the Kotlin stdlib.

**Comment by heinrichreimer** [comment]
@JakeWharton That's reasonable.

What about a section in the Readme about Kotlin compatibility?
It just seems to me that writing something like `Okio.buffer(Okio.sink(to))` is not a good code style in Kotlin when you could call `to.sink().buffer()` or something similar instead...

**Comment by JakeWharton** [comment]
Well you should import those functions to clean it up a bit, but I'm still
not sure what we'd put in the README. There's nothing wrong with that style
of function calls in Kotlin. And if you want to call them after the subject
you can write those extensions in your project or even do
file.let(::sink).let(::buffer). We could ship a Kotlin artifact that adds
these functions, but I would want a bit more value from it than just these.

**Comment by heinrichreimer** [comment]
@JakeWharton Agreed!

I'll continue collecting Kotlin-specific "syntactic sugar" here until we have a reasonable value to create a separate artifact.

So for now the list would be:

- [ ] Extension functions/properties for a more functional way to access `Okio.source(...)`, `Okio.sink(...)`, `Okio.buffer(...)` methods
- [ ] Operator overloading for a more convenient way to concatenate `ByteString`s as in #341
- [ ] DSL for creating and modifying `Buffer`s

**Comment by brettwooldridge** [comment]
@JakeWharton 

> We don't want the dependency on the Kotlin stdlib.

If you don't use any stdlib functions, Kotlin compiles to pure byte-code with no runtime dependency.

Alternatively, if you wish to use Kotlin classes you can invoke kotlinc in a way (``-includeRuntime``) that builds a jar which includes your classes and kotlin runtime classes, so there is no external dependency.  The cost is ~200Kb.

Not that I care one way or another, just sayin' ...

**Comment by JakeWharton** [comment]
Your first statement is in accurate. The declaration of a non-null
parameter or calling a Java method that you coerce the platform type into a
non-null type will emit a call to the Intrinsics class. Any proposed
extension would be on a non-null receiver thus causing this dependency
immediately even though we never explicitly reference the stdlib. Even if
it's marked inline that doesn't help Java callers from executing the
bytecode with the Intrinsics reference.

Also 200kb is nearly triple the size of the entire library.

**Comment by brettwooldridge** [comment]
@JakeWharton ... except when you compile with ``-Xno-param-assertions`` and ``-Xno-call-assertions``.

**Comment by JakeWharton** [comment]
That removes most, but not all. We've explored this before!

**Comment by brettwooldridge** [comment]
@JakeWharton Ok.  Do you recall what dependencies remained?

**Comment by JakeWharton** [comment]
I'll have to check tomorrow. I spent some time investigating it for
android-ktx project. I'd be happy to figure out a way to eliminate more of
these interop checks.

It's worth noting, though, that we actually would want the parameter checks
here in Okio. A better solution is probably using ProGuard to strip and
rename the unused stdlib methods which would likely only leave is with one
or two methods from Intrinsics.

**Comment by swankjesse** [comment]
Obsoleted by our Okio 2 effort.
