### ISSUE TITLE
large memory usage while IO

### ISSUE THREAD

**Issue by ilpanda** [square/okio#361]
I hava a problem when I download  a file !  This  is  my  code  :

```
                Response response = null;
                BufferedSink sink = null;
                try {
                    response = okHttpClient.newCall(request).execute();
                    sink = Okio.buffer(Okio.sink(downloadFile));
                    BufferedSource source = response.body().source();

                    long contentLength = 0;
                    long progress = 0;
                    String contentLengthStr = response.header("Content-Length");

                    if (!TextUtils.isEmpty(contentLengthStr)) {
                        contentLength = Long.parseLong(contentLengthStr);
                    }

                    long readCount = 0;
                    while (readCount != -1) {
                        readCount = source.read(sink.buffer(), DOWNLOAD_CHUNK_SIZE);
                        progress += readCount;
                    }
                } catch (Exception e) {
                    Log.e(TAG, "download error urL:" + url + "  the exception: " + e);
                } finally {
                    Closeables.closeQuietly(sink);
                    Closeables.closeQuietly(response);
                }
```
I  find  that  my  memory  always   increase !   
I read   the  source code  ,  I  fonud  that  the  all  the  data  is  in the  buffer;
So   I  add  sink.emit() !   Things   seems to  good !
First   I want  to know  what's the  difference between   sink.emit()  and  sink.flush() !
Second  I want  to  know  the  standard   code  !
Third  #137   your  link  is  404 ! 
Thanks !

**Comment by Guang1234567** [comment]
@ilpanda 

>  Third [#137](https://github.com/square/okio/issues/137) your link is 404 !

is OK, no 404....

**Comment by ilpanda** [comment]
@Guang1234567   
the  #137  is  ok !
the  progress example  is 404  in   swankjesse's   answer .

**Comment by NightlyNexus** [comment]
Updated link: https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java

And here's a post covering the difference between emit and flush: http://jakewharton.com/forcing-bytes-downward-in-okio/

**Comment by ilpanda** [comment]
@NightlyNexus  Thanks !  The  link  is  very useful!

**Comment by swankjesse** [comment]
Unclear what action to take on this.
