### ISSUE TITLE
Should Okio handle UTF-8 BOM?

### ISSUE THREAD

**Issue by cbruegg** [square/okio#364]
The Unicode standard includes a sequence of bytes called _byte order mark_ (`0xEFBBBF`) that can be put in the beginning of a file/stream to identify it as being encoded in UTF-8, although it's not recommended ([see also](https://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom/2223926#2223926). 

Unfortunately, Okio does not seem to be handling this at the moment, which means that BOM detection needs to be implemented by every Okio user to support UTF-8 properly. This became apparent in tikxml, an XML parser based on Okio that crashed when reading files encoded using UTF-8 BOM. To avoid the crash, the BOM is skipped in the buffer if it is detected, [as can be seen here](https://github.com/Tickaroo/tikxml/pull/79/files#diff-276e57d82cefbd738df750990350e3b1R801).

However, @sockeqwe wondered whether this is something that should be Okio's responsibility and after giving this some thought, I tend to agree. Putting the burden of checking for the BOM on every Okio user is prone to errors, since many won't even know about it. Is there any specific reason why Okio doesn't handle this, or would you agree that this should be changed? Thanks already!

**Comment by swankjesse** [comment]
The BOM is a document-level responsibility and Okio doesn't know about documents. It doesn't know whether a file contains a single XML document, or a database of them.

The BOM prefix is not universal. It shows up occasionally in XML documents. I don't recall seeing one with JSON or CSV.

Handling it in tikxml is the right place.

**Comment by sockeqwe** [comment]
Thanks for your feedback. Makes sense, tikxml will handle it.
