### ISSUE TITLE
Build Error in Android Studio 3.1

### ISSUE THREAD

**Issue by mob-rockstar** [square/okio#368]
I tried to use the okio third party in my android project.
but when I build apk, I am facing following errors:
`Program type already present: okio.AsyncTimeout$Watchdog
Message{kind=ERROR, text=Program type already present: okio.AsyncTimeout$Watchdog, sources=[Unknown source file], tool name=Optional.of(D8)}`

How can I solve this error?

**Comment by JakeWharton** [comment]
You have two copies of Okio. This is a build system misconfiguration and not something specific to this library. Without more details it's impossible to know how you are receiving two copies, but it usually means you have both the jar and a dependency (potentially transitive). If you are unable to resolve this, I would suggest posting to StackOverflow with details about your setup.

**Comment by lakshmi098** [comment]
Did you get the answer? if you plz post here.

**Comment by emrealparslan93** [comment]
I've faced with similar issue. In my case I had added these dependencies:

    implementation 'com.squareup.retrofit2:retrofit:2.7.1'
    implementation 'com.squareup.retrofit2:converter-gson:2.7.1'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.11.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.7.1'
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.1'


I removed `leakcanary` and rebuild. Error went away. I don't know why I got`Program type already present: okio`.
