### ISSUE TITLE
Combine ByteString.getByte() and ByteString.get()

### ISSUE THREAD

**Issue by swankjesse** [square/okio#429]
We currently have two public methods that do the same thing because I couldn’t figure out how to do a function that’s open, an operator, and has a JVM name.

**Comment by swankjesse** [comment]
Might be impossible.
https://stackoverflow.com/questions/47504279/java-interop-apply-jvmname-to-getters-of-properties-in-interface-or-abstract-c#comment84359346_47526540
https://github.com/JetBrains/kotlin/blob/19e38bbc725ec68c9d40bc5c4ad8945266df7231/compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/checkers/declarationCheckers.kt#L141

**Comment by swankjesse** [comment]
And a place to vote:
https://youtrack.jetbrains.com/issue/KT-20068

**Comment by Egorand** [comment]
For `ByteString.size`, I experimented with something like:

```
val size
  @JvmName("size") get() = getSize()

protected open fun getSize() = data.size
```

It's hacky, and it also breaks binary compat by making `size()` final, but it's an option.

**Comment by JakeWharton** [comment]
Since no one can subclass anyway that would be a safe change.

**Comment by Egorand** [comment]
I'll push the PR in a sec
