### ISSUE TITLE
Representing a Buffer as a NIO ByteBuffer

### ISSUE THREAD

**Issue by bnorm** [square/okio#434]
I recently needed to turn a Okio Buffer into a NIO ByteBuffer so I could pass it to AsynchronousSocketChannel to perform reads from the channel using Kotlin coroutines.

```kotlin
private suspend fun AsynchronousSocketChannel.aRead(
  buffer: Buffer,
  cursor: Buffer.UnsafeCursor
): Long {
  buffer.readAndWriteUnsafe(cursor).use {
    val oldSize = buffer.size()
    cursor.seek(oldSize)

    cursor.expandBuffer(8192)
    val length = cursor.end - cursor.start
    val read = aRead(ByteBuffer.wrap(cursor.data, cursor.start, length), 5, TimeUnit.SECONDS)

    if (read == -1) {
      cursor.resizeBuffer(oldSize)
      return -1
    } else {
      cursor.resizeBuffer(oldSize + read)
      return read.toLong()
    }
  }
}
```

Is this pattern worth a sample? Another use case for Buffer cursors that show off some their power. Maybe demonstrate how to turn a ReadableByteChannel/WriteableByteChannel into a Source/Sink? Happy to put something together and open a pull-request just wanted to make sure it was something worthwhile.

```java
final class ByteChannelSource implements Source {
  private final ReadableByteChannel channel;
  private final Buffer.UnsafeCursor cursor = new Buffer.UnsafeCursor();

  public ByteChannelSource(ReadableByteChannel channel) {
    this.channel = channel;
  }

  @Override
  public long read(Buffer sink, long byteCount) throws IOException {
    try (Buffer.UnsafeCursor ignored = sink.readAndWriteUnsafe(cursor)) {
      long oldSize = sink.size();
      cursor.seek(oldSize);

      cursor.expandBuffer(8192);
      long length = Math.min(cursor.end - cursor.start, byteCount);
      int read = channel.read(ByteBuffer.wrap(cursor.data, cursor.start, (int) length));

      if (read == -1) {
        cursor.resizeBuffer(oldSize);
        return -1;
      } else {
        cursor.resizeBuffer(oldSize + read);
        return read;
      }
    }
  }

  @Override
  public Timeout timeout() {
    return Timeout.NONE;
  }

  @Override
  public void close() throws IOException {
    channel.close();
  }
}
```

**Comment by swankjesse** [comment]
Beyond a sample, I want new APIs:
 * Use Okio with AsynchronousSocketChannel
 * Use Okio with coroutines

Not sure whether to do these as independent or linked features. I'm reluctant to do coroutines in the core API til they're released, though we can do lots with a coroutines integration module.

**Comment by bnorm** [comment]
So that's a yes to the sample?

Is the thought to introduce asynchronous `Source` and `Sink` interfaces into Okio? This could be really interesting given the large number of synchronous functions in interfaces like `BufferedSource` that might have to be duplicated.

**Comment by swankjesse** [comment]
Sure! But don't be disappointed if the sample eventually grows into a shipping API!

I'm trying to work out what async looks like with Okio. My current temptation is a small number of new methods:

```
suspend fun BufferedSource.asyncRequire(...)
suspend fun BufferedSource.asyncRequest(...)
suspend fun BufferedSink.asyncFlush(...)
suspend fun BufferedSink.asyncEmit(...)
```

But this is mostly a bad idea because you don't know when to call these methods, and it falls back to blocking if you forget.

**Comment by bnorm** [comment]
Hah! Disappointed... Right. 😄 

The only problem I see with suspension methods like those - if I understand the suggested implementation correctly - is underneath you aren't getting the shared execution benefits you would get if the suspension behavior was built all the way through. There is still a thread blocking somewhere for each call, just might not be the calling thread.

Ultimately the library needs to provide value above what anyone can achieve with `async/await` or `launch/join`. The only way _I currently think_ to get that is a deep cutting architecture change where `Source` and `Sink` are natively async. But then you are either dealing with backwards compatibility issues or API duplication due to the two color function problem.

It's a really hard problem. That's what makes it so fun and satisfying when you figure it out, right? I'll help where I can; starting with putting up the `ByteChannel` samples.

**Comment by swankjesse** [comment]
To make it concrete, lets consider what it’ll take to get all of OkHttp’s HTTP/2 connections to share a thread for incoming frames. Today each connection has a dedicated reader thread. It looks like this:

```
class ReaderRunnable implements Http2Reader.Handler {
  final Http2Reader reader;
  ...
  @Override public void run {
    try {
      reader.readConnectionPreface(this);
      while (reader.nextFrame(false, this)) {
      }
  }
}
```

We add a new interface that offers async reads:

```
interface SuspendingSource {
  ...
  @Throws(IOException::class)
  suspend fun read(dispatcher Dispatcher, sink: Buffer, byteCount: Long) Long
}
```

That’s a Kotlin coroutines example; we could also do a Java interface with our own `Callback` interface.

In either case I think we want our own dispatcher type to represent the shared I/O thread:

```
class Dispatcher {
  // Tuning parameters and methods to cancel in-flight I/O operations.
}
```

**Comment by bnorm** [comment]
Pull request for the synchronous NIO Channel samples is up: #442. I'm working on a sample for the asynchronous Channels (Socket, File) as well.

I think you are correct in needing a new interface like `SuspendingSource`. I would dive right in with Kotlin coroutines, they're awesome, but I understand the hesitation given they are still experimental.

One thing I would suggest is making the `Dispatcher` a property of the implementation and not a parameter. This would allow different layers in the stack to determine where their operations are performed, like GZIP decompression being performed on a separate dispatcher. This also makes the method signature exactly the same as `Source` but with the addition of the `suspend` keyword.

**Comment by swankjesse** [comment]
Thumbs up. I’m not enough of a NIO user to know when you’d use it synchronously, but it seems like a reasonable enough thing to sample.

For coroutines, maybe we follow Kotlin’s lead and do it in an optional module? When they finalize their API we can do likewise.

 I like `Dispatcher` as something the caller provides for two reasons. It makes it clear that the method is async (so we can use the same name as the synchronous overload) and it allows the caller to provide the thread for the callback. A webservice might have dedicated thread pools for interactive vs. non-interactive work, but the streams might come from the same place.

**Comment by bnorm** [comment]
Finally got back around to this a little. [I put together a gist](https://gist.github.com/bnorm/02062544ded9ddeb21fc6f58b6e4115f) showing extension functions for reading and writing to async socket and file channels using a Buffer as the source/sink.

As for `Dispatcher`, coroutines already allow you to [jump between context/thread pools](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#jumping-between-threads). So your example could become something like this:
```kotlin
suspend fun Http2Reader.readAllFrames(
    ioContext: CoroutineContext, handler Http2Reader.Handler) {
  while (true) {
    while (!hasFullFrame(source.buffer)) {
      withContext(ioContext) {
        source.read()
      }
    }
    // Decode frame and call handler.
  }
}
```
Where `ioContext` would be a dedicated thread pool of some kind and where everything in the `withContext` block would be executed on. I think all of the coroutine behavior you want already exists. However, this would require a dependency on the kotlinx.coroutines library unless you want to re-implement a small part of that library for Okio.

**Comment by bnorm** [comment]
I'm guessing this ticket can be closed and the coroutine discussion can continue in #501. The ByteChannel side of this ticket is resolved.
