### ISSUE TITLE
Maven snapshots not being published

### ISSUE THREAD

**Issue by swankjesse** [square/okio#435]
Lost in the migration to gradle.
https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okio/okio/2.0.0-SNAPSHOT/

**Comment by Egorand** [comment]
@AlecStrong does SQLDelight have a working Gradle setup for automatically publishing snapshots?

**Comment by digitalbuddha** [comment]
RxBinding is pretty simple setup 
https://github.com/JakeWharton/RxBinding/blob/master/gradle/gradle-mvn-push.gradle
https://github.com/JakeWharton/RxBinding/blob/master/rxbinding-kotlin/build.gradle#L44  
https://github.com/JakeWharton/RxBinding/blob/master/gradle.properties#L2
https://github.com/JakeWharton/RxBinding/blob/master/rxbinding-kotlin/gradle.properties

**Comment by Egorand** [comment]
@digitalbuddha 💯

**Comment by digitalbuddha** [comment]
Looking at last pr @swankjesse merged. Travis logs are showing Task :okio:jvm:uploadArchives FAILED
Could not transfer artifact com.squareup.okio:okio:jar:1.15.0-20180510.205246-11 from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okio/okio/1.15.0-SNAPSHOT/okio-1.15.0-20180510.205246-11.jar. Return code is: 401, ReasonPhrase: Unauthorized.

https://travis-ci.org/square/okio/builds/377456939#L1106

Overall things look correct no idea why the after success is failing.

**Comment by Egorand** [comment]
@digitalbuddha exactly, the setup looks correct, we're missing auth credentials

**Comment by digitalbuddha** [comment]
I don't believe you need em for snapshot only for signed release deployments

**Comment by swankjesse** [comment]
I did one manually by adding my personal credentials to `gradle.properties`:

```
SONATYPE_NEXUS_USERNAME=jessewilson
SONATYPE_NEXUS_PASSWORD=p34nutbutt3r
```

We need to figure out what credentials to use and how to get Travis to make them available as properties when Gradle is running. It’ll let us set environment variables which is probably how we’ll make this work.

**Comment by JakeWharton** [comment]
I will do it. There's a trick. Will share offline.

**Comment by JakeWharton** [comment]
It's just an env var with the password in it. We changed build systems so
we need to change the env var name to match the Gradle publishing setup
which is different. No real trick. Just a joke.

**Comment by vanniktech** [comment]
Oh okay yeah that one I know.
