### ISSUE TITLE
Kotlin/Native ByteString

### ISSUE THREAD

**Issue by Egorand** [square/okio#453]
Similar to #431, we need a working version of ByteString that targets Kotlin/Native

**Comment by kkalisz** [comment]
Welll I'm thinking how to implement this. Propably ByteString alone can be implemented as single Kotlin/Native module. But In some point we may need to use platform specific API and different modules for diffrent native targets may be needed. 
I would be happy to provide PR for this, but i need decision what woould be propper way of implementing this.
