### ISSUE TITLE
Increment SegmentPool.MAX_SIZE

### ISSUE THREAD

**Issue by felixbarny** [square/okio#455]
While analyzing flight recorder recordings of my JMH benchmarks which serialize fairly large JSON documents and send them in an HTTP request using okhttp, I noticed that there are quite a lot allocations of `Segment`s. This is due to the `SegmentPool` being too small for the workload. When doubling the `SegmentPool.MAX_SIZE` from 64 KiB to 128 KiB, the allocations where gone.

Allocation rate as reported by the JMH `gc` profiler before the change:
```
ElasticApmActiveContinuousBenchmark.benchmarkWithApm:·gc.alloc.rate.norm 35,863 ±  18,792    B/op
```
Allocation rate after I have increased the max segment pool size:
```
ElasticApmActiveContinuousBenchmark.benchmarkWithApm:·gc.alloc.rate.norm   3,349 ±   0,217    B/op
```

Some Java Mission Control screenshots:

Before:
<img width="1252" alt="screen shot 2018-05-14 at 21 12 58" src="https://user-images.githubusercontent.com/2163464/40018806-a5a4a4ee-57bd-11e8-86e8-5391eb0d239f.png">

After:
<img width="1252" alt="screen shot 2018-05-14 at 21 17 43" src="https://user-images.githubusercontent.com/2163464/40018817-adcd8032-57bd-11e8-8466-c43a4da0a8f4.png">

I'd suggest setting the max segment pool size to 128 KiB, or at least add an option to manually set the max segment pool size via system properties like `Long.getLong("okio.segment.pool.size.max", 64 * 1024)`.

**Comment by swankjesse** [comment]
Interesting! I suspect we could benefit from being dynamic here: grow the pool on a miss.

**Comment by felixbarny** [comment]
Isn't that how it is working at the moment? The pool starts empty and gets filled as segments are recycled. But if the total size of the byte arrays of all segments in the pool exceeds 64 KiB, segments are not stored in the pool but are made eligible for GC. As the segment size is 8kb, the segment pool can only contain 8 segments.

**Comment by swankjesse** [comment]
Maybe we track put failures due to a full pool. If we later drain the pool to be empty, we grow its max size.

**Comment by felixbarny** [comment]
Isn't that the same as having no limit at all?

**Comment by felixbarny** [comment]
I think it does makes sense to have some kind of limit for this in order to avoid the pool to grow indefinitely. As it is currently implemented, it only grows on demand and does not pre-allocate the segments, which seems to be just what you have proposed. But maybe I don't fully understand your proposal yet. Before replacing the current mechanism with a more sophisticated solution, could we just increase the default max size? That value works nice in my use case and shouldn't be a too disruptive change for others.

**Comment by felixbarny** [comment]
This problem is most likely a result of a misuse of the `GZipSink`:

https://github.com/elastic/apm-agent-java/blob/acf494923fe9e2346876313990565d41fe2aa502/apm-agent-core/src/main/java/co/elastic/apm/report/ApmServerHttpPayloadSender.java#L100-L109
```java
public void writeTo(BufferedSink sink) throws IOException {
    if (useGzip(payload)) {
        GzipSink gzipSink = new GzipSink(sink);
        gzipSink.deflater().setLevel(GZIP_COMPRESSION_LEVEL);
        sink = Okio.buffer(gzipSink);
    }
    payloadSerializer.serializePayload(sink, payload);
    sink.close();
    payload.recycle();
}
```

This leads to the creation of three `BufferedSink`s, which all need to get `Segments` from the segment pool. One `BufferedSink` is provided as an argument of `RequestBody#writeTo`, another one gets created in the constructor of `GzipSink` and yet another one is required as `GzipSink` does not extend `BufferedSink`.

When changing my implementation of `RequestBody#writeTo` to this, I don't have problems with segment allocations:

```java
public void writeTo(BufferedSink sink) throws IOException {
    OutputStream os = sink.outputStream();
    if (useGzip(payload)) {
        final Deflater def = new Deflater(GZIP_COMPRESSION_LEVEL);
        os = new DeflaterOutputStream(os, def);
    }
    payloadSerializer.serializePayload(os, payload);
    sink.close();
    payload.recycle();
}
```

**Comment by felixbarny** [comment]
I'm not entirely sure that this is the way it's supposed to work. @swankjesse do you know about best practices around gzipping the content that is written into the sink? It's important that there are no intermediate Objects I need to create, like writing the JSON content to a string or `ByteArrayOutputStream`. I rather want to directly serialize my content to a deflated `OutputStream`. A Sink does not work in that case, because the JSON serialization library I'm using, expects an `OutputStream` it can write to.

**Comment by swankjesse** [comment]
@felixbarny try this: 
```
Sink sink = new GzipSink(...);
BufferedSink bufferedSink = Okio.buffer(sink);
OutputStream outputStream = bufferedSink.outputStream();
```

**Comment by felixbarny** [comment]
This is just what I initially did, but that leads to buffering tree times, which leads to a higher consumption of Segments, which leads to the SegmentPool being empty, which leads to Segment allocations.

**Comment by swankjesse** [comment]
We increased the segment pool size in 2.7.0.
https://square.github.io/okio/changelog/#version-270
