### ISSUE TITLE
Issue file on Android

### ISSUE THREAD

**Issue by miibpa** [square/okio#466]
Hi All I'm reading raw audio from Android device and I want to write it into a file like this:

    BufferedSink sink = Okio.buffer(Okio.sink(file));
I have a callback to retrieve audio data, and then write the audio data to bufferedSink

    @Override
    public void onAudioData(byte[] data) {
        sink.write(data);
    }
But sometimes, when I listen to the audio file the last frames are missing, and all files have a length of 8182 bytes or multiples.

If I use FileOutputStream everything works well, but this is a first approach and my future purpose is to stream the audio using a Pipe and OkHttp as described here https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/PostStreaming.java

**Comment by cketti** [comment]
Sounds like you're forgetting to close the `Sink`.

**Comment by miibpa** [comment]
That solved my Issue, That you very much!
