### ISSUE TITLE
Discussion: Prefer extension functions to member functions in Kotlin common

### ISSUE THREAD

**Issue by bnorm** [square/okio#470]
First I want to say that I understand the need to maintain backwards compatibility with Okio 1.x. Not suggesting breaking that. Now on to my thoughts...

It seems to be a common design in the Kotlin standard library to prefer extension functions to member functions. Just take a look at the [Kotlin String class](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html) compared to the [Java String class](https://docs.oracle.com/javase/10/docs/api/java/lang/String.html). With this in mind, I'd like to suggest that as code is moved into the common module, each member function be evaluated if it needs to be a member function or can be replaced with an extension function.

`ByteString` is a little difficult because of `SegmentedByteString`, but member functions like `startsWith(...)` and `endsWith(...)` could be easily converted to extension functions in Kotlin common and have member functions in Kotlin/JVM.

`Buffer` could benefit with the recent introduction of `Buffer.UnsafeCursor`. For example, all the `digest(...)` and `hmac(...)` related member functions could be extension functions. The additional cost of using a cursor might not be worth it for every method, but I think these would make good candidates.

What are your thoughts on this?

**Comment by Egorand** [comment]
I like the idea, this should reduce the number of `common...()` functions we have and break the classes by responsibility. However, the experience for Java users will be pretty bad.

**Comment by bnorm** [comment]
I've been messing with this a little just to see how the experience would be. Current design goes something like this:

`common/ByteString.kt`
```kotlin
expect ByteString {
  // remove startsWith()
}

fun ByteString.startsWith(prefix: ByteString) = commonStartsWith(prefix)
```

`jvm/ByteString.kt`
```kotlin
actual class ByteString {
  ...

  fun startsWith(prefix: ByteString) = commonStartsWith(prefix)

  ...
}
```

This way the JVM maintains the same API but any use of Kotlin/Common, /JS, or /Native would prefer extension functions. Doesn't get ride of the `common*()` methods which is unfortunate, but I haven't found a way to explicitly call an extension function in Kotlin.

**Comment by Egorand** [comment]
Oh, I see what you mean now. [This](https://discuss.kotlinlang.org/t/calling-implementation-method-in-extension-function-with-same-name/5121/2) resource suggests that you can import and alias the extension function to resolve the naming clash. Eventually, when Kotlin allows us to have default impls for `expect` members and we get rid of the `common` stuff, we can just alias the extension to `commonStartsWith`.

**Comment by bnorm** [comment]
Good find! Actually, that tip combined with inlining `commonStartsWith` into the public extension function completely removes the need for `commonStartsWith`.

`jvm/ByteString.kt`
```kotlin
import okio.startsWith as exStartsWIth
actual class ByteString {
  fun startsWith(prefix: ByteString) = exStartsWith(prefix)
}
```

Now you don't need a default implementation in the expect because there isn't one anymore.

**Comment by Egorand** [comment]
That's awesome! Would love a PR!

**Comment by bnorm** [comment]
Just to make my sample more complete, [here's an example change](https://github.com/square/okio/compare/master...bnorm:bnorm.0711.extension_functions) that still passes the `japicmp` check.

Polymorphism is my main concern. It does potentially limit new things like `SegmentedByteString` from being introduced. My thought was if there were member functions that were tangential to the core functionality of a class, it might be nice to break that off as extension functions if possible.

I don't really have a strong desire either way, just wanted to bring this topic up before it was too late.

**Comment by swankjesse** [comment]
Nothing further to do here. I think it’s cool to change existing methods just as long impact binary compatibility.
