### ISSUE TITLE
Throttler okio source implement?

### ISSUE THREAD

**Issue by Gohan** [square/okio#490]
Hi, I can't find the implement of the throttler implement of okio. Don't know where I can find it.

![default](https://user-images.githubusercontent.com/212567/43537461-f19bc2d4-95f1-11e8-8842-a198103719f3.png)

https://youtu.be/WvyScM_S88c?t=29m37s

**Comment by JakeWharton** [comment]
It was never finished and the branch seems to have been deleted. I might have it on a backup somewhere. What's your use case?

**Comment by Gohan** [comment]
Just for curious, learn some tricks around okio

**Comment by Tolriq** [comment]
@JakeWharton Did not know there was already something as some users did asked me that.

They would like that I add an option to not download at full speed as okio is so fast that it takes all their 4G BW and prevent browsing at the same time.

Or maybe there's already a recipe somewhere else?
