### ISSUE TITLE
How do I preempt an existing reader blocked on BufferedSource.readUtf8Line()?

### ISSUE THREAD

**Issue by jatinlodhia** [square/okio#505]
**Context:**
I have a reader on Thread T1 that is blocked on BufferedSource.readUtf8Line() or BufferedSource.exhausted()  for more bytes to come through. 
I have another Thread T2 that monitors T1 and needs to make T1 break out of blocked reading (Say network is bad and taking too long).

I dont want to completely kill T1 since it reports success/failure and cause of failure after reading the response body and we dont want to loose these logs.

I have tried calling  (BufferedSource) instance.close() from T2 but it seems like T1 still stays blocked on exhausted() method call. I expected it to throw an IOException and unblock T1.

**Comment by swankjesse** [comment]
You should close the socket that it's blocked reading.

**Comment by swankjesse** [comment]
Also, source.close() is not threadsafe. Don't do that.

**Comment by hzsweers** [comment]
What if you're using the socket for other connections?
