### ISSUE TITLE
Buffer.truncate(size)

### ISSUE THREAD

**Issue by bnorm** [square/okio#514]
I found myself in a situation today where it was more efficient to write extra data (in the form of SegmentedByteStrings) to a buffer and truncate the buffer. Currently, I'm doing it this way:

```
long oldSize = sink.size();
long toWrite = Math.min(byteCount, SEGMENT_SIZE);
// ... maybe other writes
sink.write(segmentTemplate); // might overfill the buffer
sink.readAndWriteUnsafe(cursor);
try {
    cursor.resizeBuffer(oldSize + toWrite);
} finally {
    cursor.close();
}
```

This would also be alleviated if there was better handling of ByteStrings substrings. Either make creating substrings of a SegementedByteString share the underlying segments or add a BufferedSink.write method which allows for a begin and end index when writing a ByteString. Probably all good things regardless?

**Comment by swankjesse** [comment]
As a general rule I prefer all Buffer changes to be either reading from the front or writing to the end. You can cheat to truncate like so:

```
Buffer needsToTruncate = ...
long truncatedLength = ...;
Buffer temp = new Buffer();
temp.write(needsToTruncate, truncatedLength);
needsToTruncate.clear();
needsToTruncate.writeAll(temp);
```

I wonder which of the two variants will perform better. One of ’em might share segments better than the other.

**Comment by swankjesse** [comment]
Yeah, my preference is to keep the conceptual model as “read front, write back” and optimize performance for all combinations of that. If we offer APIs to do things like insert bytes in the middle of a buffer those APIs won’t be very fast on our current implementation and I don’t like that.

**Comment by bnorm** [comment]
The write method I am describing would write a substring of ByteString, not to write to the middle of the BufferedSink. Exactly like how `BufferedSink.write(ByteArray, beginIndex, endIndex)` currently works, but for ByteString.

I messed around with a few optimizations for SegmentedByteString. Substring segment sharing, utf8 saving, digest and hmac via segments, etc. Is this a pull-request you would be interested in?

**Comment by swankjesse** [comment]
Ahh, sorry this issue covering other things got me thinking something else. My bad.

Yeah, we definitely should have a method to write a slice of a ByteString. Starting with the basic implementation that copies, and later optimizing for SegmentedByteString!

**Comment by bnorm** [comment]
No worries, I sort of jumped topics pretty quick there. Closing as the original request is not going to be implemented.
