### ISSUE TITLE
Okio 2.1.0 / Proguard issue

### ISSUE THREAD

**Issue by Tolriq** [square/okio#516]
Took me a while to figure out what was the cause as the issue does not occurs on my CI but updating Okio from 2.0.0 to 2.1.0 cause proguard 6.0.3 on my windows dev machine to goes nuts.

I fear you won't have any idea and I have no idea how to debug that but with Okio 2.1.0 + Moshi 1.7 (And 1.6) + Okhttp 3.11 + some basic okio code in kotlin in my code like 
```
response.body()?.use { body ->
                    return ByteArrayOutputStream().run {
                        this.sink().buffer().use { it.writeAll(body.source()) }
                        toByteArray()?.also { close() }
                    }
                }
```
Cause proguard to be stuck for infinite time at Optimizing (pass 1/5)... step.
Gradle debug mode does not show any issue during that time, just the usual memory checks without any memory issues.

Reverting to 2.0.0 fix the issue.

R8 from AGP 3.2 have an issue I reported that was unfortunately not fixed in time, and R8 from 3.3a12 does compile but Moshi is no more working (was previously when I helped the Google team fixing the R8 issue) and I have not yet found (searched) the cause but maybe it's tied. (Moshi generates {} instead 
of correct objects).

Edit: Tested 2.0.0 with R8 AGP 3.3a12 and same json issue so proguard issue not related to R8 issue that I'll investigate later.

**Comment by Tolriq** [comment]
So I guess no one have an idea :) Let's hope AGP 3.3 gets final for R8 before OkHTTP require version 2.1 :)

**Comment by Egorand** [comment]
Interesting. Might be worth trying to identify the offending part of that snippet to figure out what exactly breaks ProGuard.

**Comment by Tolriq** [comment]
I've commented all my custom code that used okio as a test after your remark and the issue is still present.

Okhttp / moshi are the only one using okio

```
+--- com.squareup.okhttp3:okhttp:3.11.0
|    \--- com.squareup.okio:okio:1.14.0 -> 2.1.0
|         \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.60 -> 1.2.71
|              +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.2.71
|              \--- org.jetbrains:annotations:13.0
+--- com.squareup.okio:okio:2.1.0 (*)
+--- com.squareup.moshi:moshi:1.7.0
|    \--- com.squareup.okio:okio:1.15.0 -> 2.1.0 (*)

```

**Comment by Egorand** [comment]
So you're suspecting either OkHttp or Moshi? AFAIK neither is supposed to work with Okio 2 (althought it's binary-compatible with Okio 1), so I would probably not force the version by declaring Okio dependency explicitly.

**Comment by Tolriq** [comment]
@Egorand I don't know the cause I just know 2.0.0 works 2.1.0 don't :)

I've seen https://github.com/square/okhttp/pull/4256 where it's said it work :)

And since I'm using Kotlin the new 2.0 kotlin things for my own code are a great addition. I can stay at 2.0 as it works and I can use the Kotlin stuff, but I think it's good to know that there's something odd somewhere that may worth investigating.

**Comment by qwertyfinger** [comment]
Sharing my observations regarding this issue, which I encounter both on macOS and Windows (so I'm not sure it is exclusive to some environment).

Summary:
`Okio 2.1.0` + `AGP >= 3.2.0` + `Proguard with optimizations` = `Infinite execution of optimization step (build never finishes)`

Take anything out of this equation and everything works fine.

Possible **solutions** in detail:
1. Use Okio 2.0.0 or 1.x.x.
2. Stick to AGP 3.1.4 or earlier.
3. Disable optimizations with `-dontoptimize` flag in your Proguard config.
4. Use R8 instead of Proguard:
a) For AGP 3.2.x: add `android.enableR8=true` to your gradle.properties.
b) Use AGP 3.3.0-alphaXX (R8 is enabled by default). **Note:** You can use any AGP >= 3.3.0-alpha01 but the latest (at the moment it's 3.3.0-alpha13) is recommended.

Each solution has its drawbacks, but the most production-friendly are probably using earlier Okio versions if you don't need v.2.1.0 specifically, or disabling optimizations if you can afford to have somewhat bigger APK.

Regarding the origins of this issue and who should be responsible for fixing it:  ¯\\\_(ツ)_/¯

**Comment by Tolriq** [comment]
Thanks for confirming :)

Maybe @swankjesse or @JakeWharton  have ideas about how to debug this :(

R8 is far from production ready seeing the few bugs I have reported to them. And no proguard is not possible for most large applications that do not want multidex.
Only real solution now is 2.0 and 1.x with 2.0 way more fun when working with Kotlin.

I fear that 2.1 or 2.2 or next will be needed by okhttp or moshi before R8 is stable.

**Comment by qwertyfinger** [comment]
@Tolriq I never mentioned "no ProGuard", only "no ProGuard optimization", these are different things. You can still have ProGuard shrinking and obfuscating. Optimization provides relatively small gain in comparison with shrinking, in most cases you don't need it to avoid multidex.

**Comment by Tolriq** [comment]
@qwertyfinger For the record on my production app difference between 5 optimization pass and don't optimize is:
+ 238 classes
+ 13 625 methods
+ 15 254 method references

Inlining and merging with Java 8 and lambdas ;)

I'm not sure you can call that small gains ;) (And from real word tests, speeds impact is huge too).
But yes they are not the same thing.

**Comment by Tolriq** [comment]
No it does not. (Sorry for delay but I can no more revert the nice 2.0 kotlin code without conflicts)

**Comment by swankjesse** [comment]
Hmmmm... I think our next step is to report an issue to the ProGuard project, which I assume is where the fix will go.

Can you use `ps` to get the process ID of the hanging ProGuard process, and then `jstack` to pull a stacktrace from it? That'll help them to diagnose where the problem is.

**Comment by Tolriq** [comment]
Here's the dump.

Before finding it was okio 2.1 I first tried to see how to report to them but it seems all support is now paid. I suppose you have better contacts :)

[okio.txt](https://github.com/square/okio/files/2472852/okio.txt)

**Comment by ursusursus** [comment]
I am experiencing this as well with 2.1.0, reverting to 2.0.0 helps

**Comment by qwertyfinger** [comment]
@ursusursus Probably not a 'google thing'. In fact, the shrinker Google introduced (R8) doesn't have this issue, only ProGuard does.

**Comment by ursusursus** [comment]
@qwertyfinger hmm, I thought it was default in AS 3.2, even the log outputs changed while building. Is it still behind that exprimental flag?

**Comment by Tolriq** [comment]
R8 is still not default, but no more experimental.

Beware that R8 with AS 3.2 B2 still have some potential major issues and 1.3.33 should be used (or wait for Beta 3 ;))

**Comment by ursusursus** [comment]
Oh, thanks guys

**Comment by Tolriq** [comment]
R8 does have impact on APK size, but R8 full mode is really impressive (still experimental and still have some bugs that they are working on, so be cautious for prod).
On my large production application R8 full mode is 1MB less on the dex file compared to R8 normal, and 1.5MB from proguard with 5 optimization pass.

Not talking about compilation speed, they are really making a fantastic job with those tools. (Special thanks to Jinseong at Google for the fast and efficient support and complicated work on understanding and fixing some quite complex issues).

**Comment by ursusursus** [comment]
now im confused 😀 r8 normal mode is on in as 3.2, agp 3.2.1?

**Comment by JakeWharton** [comment]
It is not, no

**Comment by jsjeon** [comment]
We enabled R8 normal mode in AS 3.3 canary, then disabled for beta. It's still enabled by default in AS 3.4 canary, and we plan to keep it that way for AS 3.4. At the same time, full mode is available: https://android-developers.googleblog.com/2018/11/r8-new-code-shrinker-from-google-is.html

**Comment by swankjesse** [comment]
Tracked by the ProGuard project here. No action for us to take.
https://sourceforge.net/p/proguard/bugs/730/

**Comment by ursusursus** [comment]
Question: how a new version of proguard would get to my android build? via AGP?

**Comment by qwertyfinger** [comment]
@ursusursus Yes, that's correct. But currently all of the AGP 3.2.1, 3.3.0-beta03 and 3.4.0-alpha03 use ProGuard 6.0.3.

**Comment by qwertyfinger** [comment]
@Tolriq Seeing as you're aware of all the subtle quirks of R8, are there any dangers in using this latest beta ProGuard version in your opinion?

**Comment by Tolriq** [comment]
Well it's more that I'm unfortunate to be touched by a few of them in my main application ;)

R8 works great, there's some edge case with over optimization, they fixed a few already, there's still at least one very nasty one that generate native crash and no one have a clue about it for the moment.

About proguard, since beta 1 crash for me on some cases for me I'd say be careful and test :) And if you have issue, just report there, too bad no one gave the bug tracker url when I said I did not found it.

But it's the same thing for every thing that you'll update, you should have proper tests, and use alpha / beta channels on Play Store before production.

**Comment by hunter-t** [comment]
Unfortunately, this issue is still here for this config:
- Android Studio Android Studio 3.4 Beta 3
- Andoid Gradle Plugin 3.3.0 
- Okio 2.2.2

R8 is just frozen on `Optimizing (pass 1/5)...`

Had to revert to Okio 2.0.0 in order to resolve this problem.

**Comment by Tolriq** [comment]
@hunter-t 

This is not R8 but proguard that output that.

Either switch to R8 or use the last proguard beta.

**Comment by shashachu** [comment]
Overriding the proguard version doesn't seem to work for me - I used the gradle config in this comment: https://github.com/square/okio/issues/516#issuecomment-437618476

`./gradlew buildEnvironment` is showing the proper version:

```|    +--- net.sf.proguard:proguard-gradle:6.0.3 -> 6.1.0beta1
|    |    \--- net.sf.proguard:proguard-base:6.1.0beta1```

Is there some gradle incantation I'm missing?

I'm using AGP 3.3.2, Gradle 4.10.3

**Comment by shashachu** [comment]
For future readers: the issue was that we have a `buildSrc/build.gradle` file. I had to set `
    implementation "net.sf.proguard:proguard-base:6.1.0beta1"` inside of that file.
