### ISSUE TITLE
Kotlin/Native

### ISSUE THREAD

**Issue by Dkhusainov** [square/okio#519]
Any ETA on when major parts of Okio (`Sink`/`Source`/etc) will be moved to Kotlin common code so we can use it in Kotlin Native?
Also do you plan on supporting new `kotlin-multiplatform` gradle plugi?

**Comment by swankjesse** [comment]
As an open source project we prefer to avoid giving ETAs. But this is the sort of work we're thinking about.

**Comment by ptran-gpfw** [comment]
Hi, I was wondering if Kotlin Native work was still in the 'thinking about' phase or further along, perhaps 'developing on a branch' phase ?

**Comment by swankjesse** [comment]
Nothing to report in either direction.
