### ISSUE TITLE
http input stream always reads 8192 bytes, ignoring passed in buffer size

### ISSUE THREAD

**Issue by kmansoft** [square/okio#530]
Hi,

I'm using okhttp / okio in an Android app,  version 3.11.0 / 1.14.0

Noticed that http request . body . byteStream reads 8192 bytes at most, even if I pass in a larger buffer.

The code is here, note it uses `Segment.SIZE` and not `len` parameter:

https://github.com/square/okio/blob/okio_1_14/okio/src/main/java/okio/RealBufferedSource.java#L440

Oh and my code is like this:

```kotlin
val buf = ByteArray(64 * 1024)

while (true) {
 val r = stream.read(buf)
  // r is at most 8192 here
}
```
One other thing... The server is http/2, nginx 1.14.0. Don't know if it matters (maybe 8192 is some sort of default chunk size in http/2?)

**Comment by cketti** [comment]
Neither `BufferedSource.read(byte[])` nor `InputStream.read(byte[])` make guarantees about the number of bytes returned. 
If you require a certain number of bytes try one of the other methods on `BufferedSource` that make those guarantees, e.g. `readFully(byte[])`.

**Comment by kmansoft** [comment]
Yes I fully understand that there can be no guarantees (stream may end, or be slow...) and the code does not expect or require stream.read to fill the entire buffer.

It's just weird that - given a pretty large amount of upstream data in this case - the stream still wants to read it in smaller chunks.

It almost feels like using stream.read() : Int :)

**Comment by swankjesse** [comment]
What size will maximize throughput? Presumably it’s big enough to benefit from batching and small enough to stay in your CPU cache.

**Comment by veselov** [comment]
It looks like OKIO harcodes an internal buffer size to 8192, which I don't think is a good idea, honestly:

From `okio.RealBufferedSource.kt`:

```kotlin
        if (buffer.size == 0L) {
          val count = source.read(buffer, Segment.SIZE.toLong()) // Segment.SIZE is fixed at 8K
          if (count == -1L) return -1
        }
````
