### ISSUE TITLE
OutOfMemoryError thrown while trying to throw OutOfMemoryError

### ISSUE THREAD

**Issue by lbenedetto** [square/okio#534]
I'm not sure if this error actually involves this library, but Crashlytics seems to think so.

Any help would be appreciated.

Crashlytics says 
```
Okio.java line 140
okio.Okio$2.read
```

As well as 
```
Fatal Exception: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```

![image](https://user-images.githubusercontent.com/4466272/48146520-784bed80-e2b5-11e8-9174-a26d55379ce8.png)

**Comment by JakeWharton** [comment]
OOMs rarely are caused by the stacktrace they report. In reality, it's the
last straw the broke the camel's back.

**Comment by lbenedetto** [comment]
Thanks anyways, sorry for bothering you.

**Comment by lbenedetto** [comment]
Thanks anyways, sorry for bothering you.
