### ISSUE TITLE
Migrate to the new Kotlin multiplatform Gradle plugin

### ISSUE THREAD

**Issue by Egorand** [square/okio#537]
Here's the guide: https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html
Thread announcing the new plugin: https://discuss.kotlinlang.org/t/kotlin-1-3-m2-new-multiplatform-projects-model/9264
Bunch of examples here (marked obsolete but whevs): https://github.com/h0tk3y/k-new-mpp-samples

Would be great if we could keep the current project structure to avoid polluting Git history and making it hard for in-flight PRs to rebase, but I'm not sure it's possible.

**Comment by Egorand** [comment]
Assigned to myself, should be able to get to it within a week or so, but if anybody wants to take a crack at this - please feel free!

**Comment by bnorm** [comment]
I actually worked on this a while ago just to see what it would take:
https://github.com/bnorm/okio/commits/bnorm.1004.gradle_kotlin_multiplatform
Feel free to use some or all of it.

One problem I ran into is the multiplatform plugin doesn't compile Java files, leaving all the Java unit tests and jmh benchmarks unused unless they are put in a separate module. And there might be complications with japicmp.

I basically got just the multiplatform plugin figured out but nothing beyond that.

**Comment by Egorand** [comment]
Awesome stuff, thanks!

Hmm, the fact that JVM source sets can't contain Java files sounds weird, I'm curious to investigate. If it indeed doesn't work then yeah, we can restructure the project to move JMH and Java tests into separate modules.

**Comment by JakeWharton** [comment]
That present is deprecated: https://youtrack.jetbrains.com/issue/KT-26256
