### ISSUE TITLE
A seekable store

### ISSUE THREAD

**Issue by swankjesse** [square/okio#54]
We don't support anything like [SeekableByteChannel](http://docs.oracle.com/javase/7/docs/api/java/nio/channels/SeekableByteChannel.html). Would potentially be useful for random access. Could be very useful to navigate ZIP files, [dex files](https://android.googlesource.com/platform/libcore/+/master%5E2/dex/src/main/java/com/android/dex/Dex.java), etc.

Colin recommended a `Store` interface that permitted read and write access to a random access file.

**Comment by rzimmer** [comment]
We needed random access as well for our [xar Library for Java](https://github.com/sprylab/xar/). It might not be the most elaborated implementation. but for an inspiration, you may want to have a look at [RandomAccessFileSource](https://github.com/sprylab/xar/blob/master/xar/src/main/java/com/sprylab/xar/utils/RandomAccessFileSource.java).

**Comment by swankjesse** [comment]
Implemented in FileHandle
https://github.com/square/okio/issues/797
