### ISSUE TITLE
Hide/remove custom Kotlin annotations

### ISSUE THREAD

**Issue by Egorand** [square/okio#541]
Annotations such as `okio.JvmStatic` shouldn't be in the API, we should either replace them with the ones in the stdlib, or make `internal`.

**Comment by Egorand** [comment]
Ah, can't make them `internal` since they typealias to public annotations on JVM. Will wait until we can use stdlib annotations.

**Comment by JakeWharton** [comment]
That's just a bug, not a limitation: https://youtrack.jetbrains.com/issue/KT-19664
