### ISSUE TITLE
Extension functions not included in IDE autocomplete

### ISSUE THREAD

**Issue by oldergod** [square/okio#543]
I've noticed that Okio's extension functions (`String.encodeUtf8()` in my case), doesn't show up in auto completion. Nor can I get a suggested import once I typed it all.

Typing `ByteString.encodeUtf8()`, will properly suggest I replace it and all works but that's not a solution to the problem.

**Comment by Egorand** [comment]
Could it be due to https://youtrack.jetbrains.com/issue/KT-15286?

**Comment by oldergod** [comment]
Seems like so, yuck

**Comment by oldergod** [comment]
hmmm but `okio` doesn't declare them inside an object... and I got it working in IntelliJ just right now.
Not sure if I was dreaming back then or if something changed in the meantime but it's working fine now.

**Comment by Egorand** [comment]
`fun String.encodeUtf8()` is inside `ByteString`'s companion object. Yeah, they might've fixed it in recent Intellij, AFAIK the fix is targeted for 1.3.20 of Kotlin plugin.
