### ISSUE TITLE
okio leaks kotlin classes, causing failures in gradle 5

### ISSUE THREAD

**Issue by scumbkt19** [square/okio#562]
Hi!

I'm using okhttp 3.12 and in bumping from gradle 4.6 to gradle 5.2 my compileJava tasks started throwing new warnings due to `warning: unknown enum constant DeprecationLevel.WARNING
reason: class file for kotlin.DeprecationLevel not found`

Because we build with -Werror this is now causing things to fail. This might be because there is no exposed dependency on kotlin-stdlib.

Original research in https://github.com/gradle/kotlin-dsl/issues/1301 where it looked like a Deprecation annotation on ByteString could be the culprit https://github.com/square/okio/blob/2b65a6cb391ebc93c324d5d3a4d6cdc056bf47e7/okio/jvm/src/main/java/okio/ByteString.kt

my build environment:

Gradle 5.2.1
Build time: 2019-02-08 19:00:10 UTC
Revision: f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL: 1.1.3
Kotlin: 1.3.20
Groovy: 2.5.4
Ant: Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM: 1.8.0_144 (Oracle Corporation 25.144-b01)
OS: Mac OS X 10.13.6 x86_64

Forcing okio to 2.2.2 did not resolve the issue

**Comment by JakeWharton** [comment]
Yeah the dependency is marked as `implementation` but should be `api`. Far more than just this type is present in the public API.
