### ISSUE TITLE
Closing pipe source leads to read being stuck

### ISSUE THREAD

**Issue by hey99xx** [square/okio#564]
This is current pipe code for read and close: https://github.com/square/okio/blob/okio-parent-2.2.0/okio/jvm/src/main/java/okio/Pipe.kt#L123-L143 

When source is closed, further reads from the source should lead to `IllegalStateException`. This is mostly working fine, except this scenario where I have 2 threads:

- First thread (producer) is filling the `pipe.sink()` object regularly by reading from a network connection.

- Second thread (consumer) reads from an input stream connected to the source. Roughly with `Okio.buffer(pipe.source()).inputStream()`. It's repeatedly reading from the source until it returns -1 and it's printing bytes out.

- Let's say the network connection the producing thread reads from is destroyed. Now the producing thread needs to make sure the consumer thread is aware of this. So at this point I close the source so that further reads from it can fail.

- If I close the source before 2nd thread starts reading, the read will immediately fail with `closed`. This is good behavior. 

- However if 2nd thread already started reading, then it will only check source being closed at the beginning of read. Afterwards, I am stuck in the `timeout.waitUntilNotified(buffer)`. The buffer is already notified once, but its size does not change (stays 0), so this while loop keeps repeating once and on the 2nd iteration I'm stuck at timeout waiting.

```
while (buffer.size == 0L) {
  if (sinkClosed) return -1L
  timeout.waitUntilNotified(buffer) // Wait until the sink fills the buffer.
}
```

I am wondering if we can check another time inside the loop to make sure source is closed once again:

```diff
while (buffer.size == 0L) {
+ check(!sourceClosed) { "closed" }
  if (sinkClosed) return -1L
  timeout.waitUntilNotified(buffer) // Wait until the sink fills the buffer.
}
```

I can obviously close the sink, but that will just make the next read from source return -1, and since that means regular end of input, I cannot differentiate between cases of successful end of input vs. error case.

**Comment by hey99xx** [comment]
For now I've worked around this by adding

```
pipe.source().timeout().deadlineNanoTime(System.nanoTime()-1);
```

immediately before closing the source. This way after I know there's an issue with network, I can make sure timeout will immediately throw an `InterruptedIOException`. 

But I would prefer to do this in a non-hacky way if possible.

**Comment by hey99xx** [comment]
Sample code to reproduce the issue: https://gist.github.com/hey99xx/ac0fd8a906fa6c3693a3fd44e95455d9

**Comment by swankjesse** [comment]
The behavior you’re triggering is not expected to work, but we can potentially find ways to make things better.

As a rule you are expected to have at most one thread accessing the sink and at most one thread accessing from the source. When your producer thread closes the consumer’s source, that violates this rule because we have two threads simultaneously accessing the source.

A better solution is for the producer to close the sink, which should cause the source to be exhausted. If you want the close to be more . . . violent and immediate, we could add a method like `Pipe.cancel()` that causes both ends to fail with `IOExceptions`.

**Comment by hey99xx** [comment]
Thanks @swankjesse. That rule makes sense, even though it's not exactly documented. I guess I could take the hint from "Typically each is accessed by its own thread" in the javadoc.

I can close the sink, but as I mentioned then I would then not be able to understand whether sink is closed after successfully getting network data, or it's exhausted because of an error. Or if there's a way to distinguish two cases maybe you can point it out. If I cannot distinguish, I could accidentally show partial content to the user which would be a no-go.

`Pipe.cancel()` makes sense, I did not imagine you would be adding my one-liner without giving additional thought :) My use case is only being able to trigger exceptions on `source.read()` on demand without getting stuck elsewhere. If your idea is me replacing `pipe.source().close()` with `pipe.cancel()` to solve the issue, I would certainly use it. If you have an idea what the code in Pipe class would look like, I can give it a try on my sample code.

**Comment by hey99xx** [comment]
While I have not been commenting on this, I think I found a clean solution doable in the application space. The idea is having a `ForwardingSource` subclass where the producing thread can set an error field, and the consuming thread can check whether this field was set or null (no error).

Sample code: https://gist.github.com/hey99xx/4ca5a840f6010b5cb5b96c65f79178f4 @swankjesse If you think this is a reasonable solution I can close this issue.

**Comment by swankjesse** [comment]
Yep, that’s a great solution!

**Comment by hey99xx** [comment]
thanks; closing then.
