### ISSUE TITLE
java.io.IOException: CRC: actual 0x648b6135 != expected 0x29d115fe

### ISSUE THREAD

**Issue by dingyong666** [square/okio#569]
java.io.IOException: CRC: actual 0x648b6135 != expected 0x29d115fe
 at okio.GzipSource.checkEqual(GzipSource.java:205)
 at okio.GzipSource.consumeTrailer(GzipSource.java:173)
 at okio.GzipSource.read(GzipSource.java:92)
 at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
 at java.io.InputStream.read(InputStream.java:101)
...................................

Browser and Curl experiments are normal，webtools http://coolaf.com/en , need set 'accept-encoding': 'gzip' 。but okhttp is abnormal ~ , test url https://www.toptoon.net/comic/contents_list?comic_id=80029

**Comment by swankjesse** [comment]
Looks like a bad gzip job on that file. Workaround with this:

```
    Request request = new Request.Builder()
        .header("Accept-Encoding", "identity")
        .url("https://www.toptoon.net/comic/contents_list?comic_id=80029")
        .build();
```

OkHttp doesn’t offer a way to ignore bad checksums.
