### ISSUE TITLE
HashingSink slower than Java IO

### ISSUE THREAD

**Issue by LandChanning** [square/okio#571]
Hi,
I used HashingSink to get sha-1 from file. But I found that it takes more time than Java IO.
This is my code：
```
// Okio
// Algorithm is custom enum
@JvmStatic
fun digest(file: File, type: Algorithm): String =
    when (type) {
        Algorithm.MD5 -> HashingSink.md5(Okio.blackhole())
        Algorithm.SHA1 -> HashingSink.sha1(Okio.blackhole())
        Algorithm.SHA256 -> HashingSink.sha256(Okio.blackhole())
        Algorithm.SHA512 -> HashingSink.sha512(Okio.blackhole())
    }.use { hashingSink ->
        Okio.buffer(Okio.source(file)).use { source ->
            source.readAll(hashingSink)
            return hashingSink.hash().hex()
        }
    }

// Java IO
private static final int BUFFER_SIZE = 128 * 1024;

public static String sha1(String filePath) throws Exception {
    InputStream fis = null;
    byte[] buffer = new byte[BUFFER_SIZE];
    int numRead = 0;
    MessageDigest digest;
    try {
        fis = new FileInputStream(filePath);
        digest = MessageDigest.getInstance("SHA-1");
        while ((numRead = fis.read(buffer)) > 0) {
            digest.update(buffer, 0, numRead);
        }
        return toHexString(digest.digest());
    } finally {
        try {
            if (fis != null) { fis.close(); }
        } catch (IOException e) {
            // doNothing
        }
    }
}

public static String md5(String path) throws Exception {
    InputStream fis = null;
    byte[] buffer = new byte[BUFFER_SIZE];
    int numRead = 0;
    MessageDigest digest;
    try {
        fis = new FileInputStream(path);
        digest = MessageDigest.getInstance("MD5");
        while ((numRead = fis.read(buffer)) > 0) {
            digest.update(buffer, 0, numRead);
        }
        return toHexString(digest.digest());
    } finally {
        try {
            if (fis != null) { fis.close(); }
        } catch (IOException e) {
            // doNothing
        }
    }
}
```

Device: Xiaomi Redmi Note 4X
Android SDK: 28
Okio version: 3.14.0

Test result(including System.out.print time):

| file size | algorithm | Okio time-consuming | Java IO time-consuming |
| ------ | ------ | ------ | ------ |
| 315.7M | sha1 | 1736 | 755 |
| 315.7M | md5 | 2612 | 1603 |
| 5.86G | sha1 | 36589 | 29465 |
| 5.86G | md5 | 54304 | 35964 |

Is there any problem with my code?

**Comment by JakeWharton** [comment]
The hashing sink and source are for computing a hash while _also_ reading or writing the contents for some other purpose. If you're only needing to compute the hash you need to send the data to the blackhole sink so that the internal buffers can be freed to be reused. Right now I think you're basically causing byte arrays to be allocated to hold the entire contents in memory.

**Comment by LandChanning** [comment]
@JakeWharton Thanks for your reply, but I do use the blackhole sink.

```
HashingSink.md5(Okio.blackhole())
```
I learned this feature from the [sample](https://github.com/square/okio/blob/master/samples/src/main/java/okio/samples/Hashing.java).

**Comment by JakeWharton** [comment]
Ah, so you do! Sorry I was reading on mobile. Then I'm not quite sure where
the overhead comes from.

**Comment by LandChanning** [comment]
Maybe the buffer size？I used `BUFFER_SIZE = 128 * 1024` in Java IO function.

**Comment by JakeWharton** [comment]
Yeah, possibly. Okio uses fixed 8k chunks. You could make a custom build
with 128k chunks just to see whether it brings performance in line.

**Comment by LandChanning** [comment]
I'm sorry, I don't know how to make a custom build with 128k chunks. 
Like this? 
`source.read(byteArray, 0, 128 * 1024)` 
No, it is useless.
I am still a newbie about Okio, And found no useful information in Google.

**Comment by bnorm** [comment]
You could go the other way and decrease your buffer size `BUFFER_SIZE = 8 * 1024`. Might give you a better, direct comparison.

**Comment by LandChanning** [comment]
@bnorm Yeah, after decrease the buffer size to 8K, the speed is almost the same.

**Comment by swankjesse** [comment]
No action to take here.
