### ISSUE TITLE
Document proguard rules

### ISSUE THREAD

**Issue by swankjesse** [square/okio#58]
Our users are running into problems with java.nio.file.Path. We have proguard rules that help to work around this. We should document 'em.

See also https://github.com/square/okio/issues/42

**Comment by monxalo** [comment]
Rather than disabling the lint check you can change its severity.
```groovy
lintOptions {
   warning 'InvalidPackage'
}
```
This way it will still show up in lint results with a warning.

**Comment by mvyas85** [comment]
Hi i am also getting this error. How to fix it without disabling lint error or adding 

lintOptions {
   warning 'InvalidPackage'
}

Looking for more help - 
http://stackoverflow.com/questions/35492259/lint-error-on-okio

**Comment by davidvermeir** [comment]
Any updates on this problem? This is a really annoying issue.

**Comment by mvyas85** [comment]
David,

True.. nothing yet ! i started getting same issue in my other project also.
No idea why yet !

**Comment by Macarse** [comment]
```
<issue id="InvalidPackage" severity="error">
        <ignore regexp="okio.*jar" />
</issue>
```

to keep it as an error and ignore okio's jar file.

**Comment by 3flex** [comment]
Closed by #275?

Regarding Android lint, seems https://github.com/square/okio/issues/58#issuecomment-232811171 is the best workaround as it disables the error only for this lib. Could this be added to the README?

**Comment by noamtamim** [comment]
Is there a plan to fix the *lint* part of this issue? You may consider offering a separate build of the library for Android, that doesn't contain the non-Android java.nio.file.Path class.

**Comment by JakeWharton** [comment]
No. Android O will have this class anyway.

**Comment by jaredsburrows** [comment]
I tried to do this here: https://github.com/square/okio/issues/268.

**Comment by swankjesse** [comment]
We have a ProGuard section on our main readme now.
