### ISSUE TITLE
Project import into IntelliJ

### ISSUE THREAD

**Issue by bnorm** [square/okio#580]
Anybody else having trouble working with the project in IntelliJ? I'm seeing a lot of warnings and errors being reported but obviously the project compiles with Gradle just fine.

I've been poking at this for the last couple days and one of the bigger problems I've found is the conflict between where the project Kotlin common code is located and where IntelliJ presumes the Java code for the `jvmWithJava` code is going to be. But if the project Kolin common code is moved to `src/commonMain/kotlin` and `src/commonTest/kotlin`, a lot of the expect and actual warnings I've seen go away.

I know there's currently a lot of churn with the common code going on right now but I wanted to record my findings and see if anybody else is having the same problems I'm having.

**Comment by JakeWharton** [comment]
Yeah our project setup predates the new plugin and it's folder structure.
Best to wait for a day when no one is working on anything to send a PR to
move everything to be more in line with the new plugin setup.
