### ISSUE TITLE
How nativeX64Test implemented?

### ISSUE THREAD

**Issue by 9468305** [square/okio#615]
Hi guys,

I went through the project, and didn't find out where the `macosX64Test`, `linuxX64Test` and `winX64Test` gradle tasks implemented.  
I thought there would be a task(maybe named `iosX64Test`) which call `xcrun simctl spawn iPhoneDevice test.kexe` to run all Unit Test for iosX64, but I found nothing.  
Does it hiding in some gradle plugins?  

Thanks.

**Comment by Egorand** [comment]
These tasks are added by the Kotlin Gradle plugin, check out the main module's build.gradle file.
