### ISSUE TITLE
Cannot choose between the following variants of com.squareup.okio:okio:2.3.0

### ISSUE THREAD

**Issue by plastiv** [square/okio#647]
I just upgraded from `okio:2.2.2` to `okio:2.3.0` and don't know how to tell gradle which artifact to use 🤔 Is there a documentation how to declare okio for non kotlin-multiplatform projects?

```
Could not determine the dependencies of task ':main:kaptDebugKotlin'.
> Could not resolve all task dependencies for configuration ':main:kapt'.
   > Could not resolve com.squareup.okio:okio:1.16.0.
     Required by:
         project :main > com.ryanharter.auto.value:auto-value-moshi:0.4.7 > com.squareup.moshi:moshi:1.8.0
      > Cannot choose between the following variants of com.squareup.okio:okio:2.3.0:
          - jvm-api
          - jvm-runtime
          - metadata-api
        All of them match the consumer attributes:
          - Variant 'jvm-api' capability com.squareup.okio:okio:2.3.0:
              - Unmatched attributes:
                  - Required artifactType 'processed-jar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'java-api-jars' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.
          - Variant 'jvm-runtime' capability com.squareup.okio:okio:2.3.0:
              - Unmatched attributes:
                  - Required artifactType 'processed-jar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'java-runtime-jars' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.
          - Variant 'metadata-api' capability com.squareup.okio:okio:2.3.0:
              - Unmatched attributes:
                  - Required artifactType 'processed-jar' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'kotlin-api' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'common' but wasn't required.
```

**Comment by Egorand** [comment]
This might be related to an incremental kapt bug: https://youtrack.jetbrains.com/issue/KT-33206

**Comment by plastiv** [comment]
Thank you 🙏 I think it hints into right direction. Managed to compile with next workaround. I'm not that familiar with gradle or mpp to tell if there are any downsides with this approach

```groovy
subprojects { subProject ->
    subProject.configurations.all { configuration ->
        // Workaround for kapt bug with MPP dependencies
        // https://youtrack.jetbrains.com/issue/KT-31641
        // https://youtrack.jetbrains.com/issue/KT-33206
        if (name.contains('kapt')) {
            attributes.attribute(Usage.USAGE_ATTRIBUTE, subProject.objects.named(Usage.class, Usage.JAVA_RUNTIME))
        }
    }
}
```

**Comment by Egorand** [comment]
I suspect that the Kotlin Gradle plugin should be doing something similar internally, that should hopefully get fixed in subsequent releases. The workaround looks good, I'm gonna keep this issue open in case somebody else experiences it.

**Comment by trevjonez** [comment]
just hit this with gradle 6.0 using kotlin 1.3.50, bumping to 1.3.60 and everything works as expected now.

**Comment by Egorand** [comment]
https://youtrack.jetbrains.com/issue/KT-31641 (duplicated by https://youtrack.jetbrains.com/issue/KT-33206 mentioned above) is fixed in 1.3.60. Closing the issue.

**Comment by deepthought-64** [comment]
Sorry to chip in after a the long time this came up. 
But i ran into the same issue as @plastiv but i am neither running `kapt` nor `wire`. 
I translated his fix into kotlin for the `build.gradle.kts` like that
```
    configurations.forEach {
            if (it.name.contains("kapt") || it.name.contains("wire") {
                attributes.attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage::class.java, "java-runtime"))
            }
        }
```
But no configuration has "kapt" or "wire" in the name, so it does not do anything.
(I also tried applying the attributes to all configurations, but to no avail).

I am running gradle 6.1 and kotlin 1.3.61 but despite stating that 1.3.60 fixes the issue, i still seem to experience it.
The only thing that circumvents that error, is when I revert to version 2.2.2. of `okio`

I'd really apprecitate any help or pointers.

**Comment by swankjesse** [comment]
Best workaround is pasting this in the bottom of my root project’s `build.gradle`:

```
subprojects { subProject ->
  // Workaround the Gradle bug resolving multiplatform dependencies.
  // https://github.com/square/okio/issues/647
  configurations.all { configuration ->
    if (name.contains('kapt') || name.contains("wire") || name.contains("proto")) {
      attributes.attribute(Usage.USAGE_ATTRIBUTE, subProject.objects.named(Usage.class, Usage.JAVA_RUNTIME))
    }
  }
}
```

**Comment by jan-xyz** [comment]
We also still have the same issue with `1.3.61`

**Comment by cyc1ingsir** [comment]
If you go to start.spring.io and configure a project with
Gradle Project; Kotlin; Spring Boot 2.3.0; Packaging Jar; Java 11
download the project, unzip it
and add
`implementation("com.squareup.okio:okio:2.6.0")` 
to build.gradle.kts (dependencies)
This error will show up when running `./gradlew clean build`
```
* What went wrong:
Execution failed for task ':bootJar'.
> Could not resolve all files for configuration ':productionRuntimeClasspath'.
   > Could not resolve com.squareup.okio:okio:2.6.0.
     Required by:
         project : > com.squareup.okhttp3:okhttp:4.7.2
      > Cannot choose between the following variants of com.squareup.okio:okio:2.6.0:
          - jvm-api
          - jvm-runtime
          - metadata-api
        All of them match the consumer attributes:
          - Variant 'jvm-api' capability com.squareup.okio:okio:2.6.0:

```
Removing the line with `kotlin("kapt") version "1.3.72"`doesn't change anything.
Generating a  project for SpringBoot version `2.2.7.RELEASE` doesn't show this error.

**Comment by asafm** [comment]
I get this error when adding the following plugin: https://github.com/google/protobuf-gradle-plugin to my gradle file.
The work-around suggested in the comments solved it.
