### ISSUE TITLE
Thread block at AsyncTimeout.cancelScheduledTimeout method

### ISSUE THREAD

**Issue by x00403408** [square/okio#653]
We use okhttp 3.14.0 and okio 1.14.0 to perform put requests in a multi-threads context. The reproduce steps are:
1. Use okhttp client to perform get request to obtain an InputStream;
2. Use okhttp client to perform put request using the InputStream as data source in step 1;
3. Open multi-threads to do the step 2;
4. Call InputStream.close() to close many InputStreams during step 3;
5. Do the step 1-4 repeatly;

The jstack is at https://obstrans.obs.cn-north-1.myhuaweicloud.com/jstask.png

Any suggestion?

**Comment by swankjesse** [comment]
Executable test case please?
