### ISSUE TITLE
JavaDocs Links Result In 404

### ISSUE THREAD

**Issue by commonsguy** [square/okio#656]
(sorry, GitHub decided to submit the issue without giving me a chance to fill it in...)

Links on the home page (`README.md`) like https://square.github.io/okio/2.x/okio/jvm/okio/-source/index.html result in 404's:

![okio-javadocs-bug](https://user-images.githubusercontent.com/103772/64859867-69327c00-d5f9-11e9-959e-045dfeb682f8.png)

I tested on a couple of browsers on a couple of networks and I get consistent results. Let me know if you need additional details!

**Comment by Egorand** [comment]
Thanks for filing! I believe they broke after we've moved files to fit the new Kotlin MPP layout, should be an easy fix.
