### ISSUE TITLE
CRC32

### ISSUE THREAD

**Issue by bnorm** [square/okio#659]
Already in use by `GzipSink` and `GzipSink`, should the CRC32 algorithm be natively supported by Okio?
- `HashingSource.crc32()`
- `HashingSink.crc32()`
- `ByteString.crc32()`
- `Buffer.crc32()`

If yes, are there other checksum algorithms which should be supported by Okio?

**Comment by swankjesse** [comment]
I think we want to treat our hash algorithms as a curated set. Just the core ones.

CRC32 has its uses in 1980s UNIX stuff but most programmers won't need it for application code.

**Comment by bnorm** [comment]
My use-case is creating checksums of data written to a storage device. We use these checksums to test for data corruptions. We currently use MD5 (via `HashingSink`) but I'd like to use something with a little more performance, hence looking at using CRC32 instead.

Very comfortable using `UnsafeCursor` to create something similar to `HashingSink` for my use-case. And very much agree about keeping the list of algorithms curated.

**Comment by swankjesse** [comment]
You sure you don't want something cryptographic?

**Comment by bnorm** [comment]
This particular application I work on is an internal tool and similar in functionality to [FIO](https://fio.readthedocs.io/en/latest/fio_doc.html), [IOzone](http://www.iozone.org/), or [Vdbench](https://www.oracle.com/downloads/server-storage/vdbench-downloads.html). The hashing is only used to validate data integrity and not used for any security purposes. So I don't *need* anything cryptographic but not opposed to using a cryptographic algorithm as long as it is efficient.

**Comment by bnorm** [comment]
Closing as the algorithm set is going to stay limited.
