### ISSUE TITLE
When is the size of the Buffer initialized?

### ISSUE THREAD

**Issue by AndroidLittleWhite** [square/okio#669]
@Nullable Segment head;
  long size;

  public Buffer() {
  }

  /** Returns the number of bytes currently in this buffer. */
  public final long size() {
    return size;
  }

I searched the entire class but didn't find out where the size was initialized.

**Comment by bnorm** [comment]
Primitives are initialized to 0 by default. Object references - like `head` - are initialized to `null` by default.
