### ISSUE TITLE
Domain name validation and Certificate pinning

### ISSUE THREAD

**Issue by n00bm5st3r69** [square/okio#671]
I am currently working on a React-native application and I think okio is being used in Android. We have performed an app scan and received the following vulnerabilities. May I know if it is possible to perform domain name validation and certificate pinning with okio?

Vulnerability Name | Calling Method | Method Signature | Location
-- | -- | -- | --
Missing Domain-name Validation | okio.Okio.sink(java.net.Socket):okio.Sink | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okio\Okio.java:117)
Missing   Domain-name Validation | okio.Okio.source(java.net.Socket):okio.Source | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okio\Okio.java:203)
Lack of Certificate Pinning | okio.Okio.sink(java.net.Socket):okio.Sink | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okio\Okio.java:117)
Lack   of Certificate Pinning | okio.Okio.source(java.net.Socket):okio.Source | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okio\Okio.java:203)

**Comment by JakeWharton** [comment]
Okio is just adapting java.io stream types into okio stream types. It does not make HTTP requests.
