### ISSUE TITLE
[Question] Binary compatibility version

### ISSUE THREAD

**Issue by justintuchek** [square/okio#672]
We're looking at upgrading to Okio 2.x - with a dependency still targeting 1.13.0

Looking at the [changelog for 2.0.0-RC1](https://github.com/square/okio/blob/master/CHANGELOG.md#version-200-rc1) - it looks like it should be compatible back to Okio 1.0

Looking at the [blog post](https://developer.squareup.com/blog/okio-2/) announcing Okio 2.0 looks like it the minimum binary compatible version is 1.15

Just looking for clarification between the two sources

**Comment by swankjesse** [comment]
2.0.0 is a superset of 1.15.0, so anything that you compiled against 1.15.0 (or earlier) should be safe to run against 2.0.0 (or later).
