### ISSUE TITLE
KotlinNullPointerException in okio.Segment.pop 

### ISSUE THREAD

**Issue by Jeff11** [square/okio#673]
After updating to okio 2.4.1 we got reports for this crash from various devices and Android versions:

```
kotlin.KotlinNullPointerException: 
  at okio.Segment.pop (Segment.java:89)
  at okio.Buffer.skip (Buffer.java:1478)
  at okio.Buffer.clear (Buffer.java:1466)
  at okio.RealBufferedSource.close (RealBufferedSource.java:499)
  at okhttp3.internal.http2.Http2Reader.close (Http2Reader.java:314)
  at okhttp3.internal.Util.closeQuietly (Util.java:480)
  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.run (Http2Connection.java:577)
  at java.lang.Thread.run (Thread.java:764)
 ```

**Comment by swankjesse** [comment]
I suspect the bugs you’re running into with Okio aren’t caused by the upgrade to 2.4.1, but instead by unsafe concurrent access to your buffers. Do you ever read and write any Okio streams from multiple threads concurrently? This includes closing sinks that another thread is currently writing.

**Comment by Jeff11** [comment]
I can't rule out that this is happening, okio is mostly used by okhttp. I'm not doing things differently from last version.

Okio was on 2.4.0 before. RxJava 2.2.14, okhttp 4.2.2, gson 2.8.6 also got minor updates. 

Coroutines went from 1.3.2 to 1.3.2-1.3.60-eap-76.

**Comment by Jeff11** [comment]
I made another build with Android gradle plugin 3.6.0-beta03 and don't get those crashes anymore. My guess now is that the version 4.0.0-alpha01 messed something up.

**Comment by Vuthe** [comment]
> After updating to okio 2.4.1 we got reports for this crash from various devices and Android versions:
> 
> ```
> kotlin.KotlinNullPointerException: 
>   at okio.Segment.pop (Segment.java:89)
>   at okio.Buffer.skip (Buffer.java:1478)
>   at okio.Buffer.clear (Buffer.java:1466)
>   at okio.RealBufferedSource.close (RealBufferedSource.java:499)
>   at okhttp3.internal.http2.Http2Reader.close (Http2Reader.java:314)
>   at okhttp3.internal.Util.closeQuietly (Util.java:480)
>   at okhttp3.internal.http2.Http2Connection$ReaderRunnable.run (Http2Connection.java:577)
>   at java.lang.Thread.run (Thread.java:764)
> ```

**Comment by Jeff11** [comment]
I have not seen this crash in newer builds with updated Android Gradle plugin anymore.

**Comment by raghavsatyadev** [comment]
This issue occurred again on Android Studio 4.0 Canary 8 for these dependecies
```
implementation 'com.squareup.retrofit2:retrofit:2.7.1'
implementation 'com.squareup.retrofit2:converter-gson:2.7.1'
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.7.1'
implementation 'com.squareup.okhttp3:logging-interceptor:4.3.0'
```
