### ISSUE TITLE
Okio 2.x gradle sync failed

### ISSUE THREAD

**Issue by rantianhua** [square/okio#678]
My gradle configuration:
```
kotlin {
    targets {
        fromPreset(presets.android, 'android')
        // This preset is for iPhone emulator
        // Switch here to presets.iosArm64 (or iosArm32) to build library for iPhone device
        fromPreset(presets.iosX64, 'ios') {
            compilations.main.outputKinds('FRAMEWORK')
        }
    }
    sourceSets {
        commonMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib-common'
                implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:$coroutines_version"
                implementation "com.squareup.okio:okio-multiplatform:$okio_version"
            }
        }
        androidMain {
            dependencies {
                implementation 'org.jetbrains.kotlin:kotlin-stdlib'
                implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"
            }
        }
        iosMain {
            dependencies {
                implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:$coroutines_version"
            }
        }
    }
}
```
`okio_version` is 2.4.0. Gradle sync failed with the error message: 
```
build.gradle: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.squareup.okio:okio-multiplatform:2.4.0.
```

**Comment by JakeWharton** [comment]
The multiplatform artifact is published as `okio-multiplatform`. `okio` is the JVM-specific version for backwards compatibility.

**Comment by rantianhua** [comment]
But what I use is okio-multiplatform.

**Comment by Egorand** [comment]
The artifact is there (https://repo1.maven.org/maven2/com/squareup/okio/okio-multiplatform/2.4.0/) and your coordinates look correct. Make sure your project is generally able to resolve artifacts from Maven Central. If it still doesn't work, it'd be great if you could provide a test project that reproduces the issue, we can take a closer look.

**Comment by rantianhua** [comment]
@Egorand  I create a new sample project: https://github.com/rantianhua/KotlinMPErroSample. But this time the problem has a little difference that I have written it in README.

**Comment by Egorand** [comment]
@rantianhua I'm able to download and build your project. I've added code calling Okio to `app/src/commonMain/kotlin/sample/Sample.kt` and it compiles properly. If you feel there's an IDE issue, please file a bug against Intellij (https://youtrack.jetbrains.com/newIssue) or Android Studio (https://issuetracker.google.com/issues/new?component=192708&template=840533).

**Comment by rantianhua** [comment]
Thanks!
