### ISSUE TITLE
throw IOException when using okio.Buffer.inputStream() with InputStreamReader

### ISSUE THREAD

**Issue by ClarkGuan** [square/okio#685]
Class **InputStreamReader** does not allow the read method of the underlying **InputStream** to return 0. If the content size of the incoming buffer of **okio.Buffer** is just a multiple of 8192 bytes, the penultimate read call (from okio.Buffer.inputStream()) will return 0.

Reproducible code:

```java
        byte[] target = new byte[8192];  // or 8192 * N
        Buffer buf = new Buffer();
        buf.readFrom(new ByteArrayInputStream(target));
        try (InputStream inputStream = buf.inputStream()) {
            InputStreamReader reader = new InputStreamReader(inputStream);
            char[] buf2 = new char[512];
            int n;
            while ((n = reader.read(buf2)) != -1) {
                // ...
            }
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();       // always here
        }
```

Error stack trace:

```
java.io.IOException: Underlying input stream returned zero bytes
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
        ...
```

Reproducible version：all (**2.4.1**, **1.17.4** tried)

**Comment by cketti** [comment]
`Buffer.readFrom(InputStream)` is what seems to trigger this issue. It will leave the Buffer with two Segments. The last one being completely empty. `Buffer.commonRead()` will "skip" such Segments but return 0 as number of bytes read when encountering one.

The documentation of `InputStream` is relatively clear in which cases the `read(byte[], …)` methods will return 0. The documentation of `BufferedSource.read()` makes no such guarantees. Maybe it should?

**Comment by swankjesse** [comment]
Released!
https://github.com/square/okio/blob/master/CHANGELOG.md#version-242
