### ISSUE TITLE
Where can I find documentation on how to configure Okio using Kotlin?

### ISSUE THREAD

**Issue by chenriquevz** [square/okio#696]
Hello,

I have trying to run some unit tests using Okio.source(), Okio.buffer(), but I get an error like this "Using 'buffer(Source): BufferedSource' is an error. moved to extension function". I am using Okio 2.4.3, also tried 2.3.0 as mentioned in this SO https://stackoverflow.com/questions/57265689/how-to-fix-unresolved-reference-buffer-or-using-buffersource-bufferedso

In the end I am not been successful, also I didn't have find any docs mentioning how to proper configure it using extension/or whatever the new way is. Is there any resource you can point me to?

What I am trying is this:

val inputStream =javaClass.classLoader!!.getResourceAsStream("api-response/$fileName") 
val source = Okio.buffer(Okio.source(inputStream))

Thank you.

**Comment by Egorand** [comment]
[Changelog](https://square.github.io/okio/changelog/#version-200-rc1) has a table of old static methods and extension functions they were refactored to. If you're using Intellij IDEA, you should be able to Alt + Enter on the error and apply the suggestion - it should fix the method invocation automatically for you.

Also, please prefer [Stackoverflow](https://stackoverflow.com/questions/tagged/okio) for usage questions, we use the issue tracker for bug reports and feature requests.
