### ISSUE TITLE
Markdown docs need better line-wrapping

### ISSUE THREAD

**Issue by swankjesse** [square/okio#703]
There should be a break before ‘(native)’:

![Screen Shot 2020-03-04 at 8 46 36 AM](https://user-images.githubusercontent.com/133019/75885551-b6e3b080-5df4-11ea-9f74-5618e6495b70.png)

https://square.github.io/okio/2.x/okio/okio/-byte-string/to-byte-string/

**Comment by Egorand** [comment]
We should file this against either Dokka or MkDocs.

**Comment by swankjesse** [comment]
Fixed by not using Markdown for docs!
