### ISSUE TITLE
How convert BufferedSource in FileReader

### ISSUE THREAD

**Issue by Master-Antonio** [square/okio#712]
Hi, i'm converting my old code with Standard Java API, BufferedReader, FileReader ext ext.
But i have one problem, i need to read a file json and convert in Object, i'm using GSON, in the old my code i did:
```
try (FileReader reader = new FileReader(pathFile + ".json")) {
//Read JSON file
 Gson gson = new Gson();
JsonReader readerJson = new JsonReader(reader);
```

How can i use the BufferedSource in the same way? 
JsonReader want only a FileReader ...
There is some possibility?

Thanks so much for help

**Comment by JakeWharton** [comment]
There's no advantage to using Okio here. You'd just be introducing intermediate copies.

**Comment by Master-Antonio** [comment]
So I don't understand, what are the advantages to use OKIO?
My files are very big, 50-60 mb, 700k strings, and 40 million of characters.
I'm reading line by line ...

**Comment by JakeWharton** [comment]
There's only an advantage when you have lots of intermediate layers and/or a library that understands Okio like Moshi instead of Gson.

**Comment by Master-Antonio** [comment]
I didnt read these things on doc, i through It improve the performance...
