### ISSUE TITLE
SegmentPool blocked

### ISSUE THREAD

**Issue by rewlad** [square/okio#715]
Hello,

I see a strange picture in a running jcmd Thread.print on my server app using okio 2.5.0,
many threads are blocking during parallel decoding:
```
   java.lang.Thread.State: BLOCKED (on object monitor)
     at okio.SegmentPool.recycle(SegmentPool.kt:64)
    - waiting to lock <0x00000002cf4f3c78> (a okio.SegmentPool)
```
In source code for SegmentPool there are ```@ThreadLocal``` and ```synchronized(this)``` at the same time.
So, how does that pool intended to work?

**Comment by swankjesse** [comment]
`@ThreadLocal` is for Kotlin native
`synchronized` is for JVM

I’d like to fix this to avoid this locking; this isn’t good! I think our first step will be an option like a System property to change the segment pool to use CAS instead of synchronized for concurrency.

**Comment by rewlad** [comment]
That's great; Do You need any support/contribution from me here?

So JVM is just ignoring ```@ThreadLocal``` annotation?
Why not to use ThreadLocal for JVM too? 
Is ThreadLocal slower or faster vs CAS?
If the question is tradeoff between 2:
- spend extra 64 KiB of heap per thread and utilize all CPU cores
- minimize memory consumption on low-end device

Then it can be System property to enable the first option,
or just auto-detection based on memory/cpu stats.

**Comment by swankjesse** [comment]
I’m reluctant to do anything with ThreadLocal because it can result in a pretty severe memory leak, depending on how threads are used.

I’m also reluctant to introduce system properties because it increases the complexity of using this library.

Here’s one idea: just not using locks. Would you be interested in trying this to see if it’s a performance improvement in your application? I can release a special build to Maven Central.
https://github.com/square/okio/pull/717

**Comment by rewlad** [comment]
That's great;

I can check performance on Monday.
Anyway it seems to be not 30min task:
The target app directly depends on cone/c4proto framework,
c4proto depends on com.squareup.wire:wire-runtime,
and wire-runtime depends on okio.
For now it's not clear for me how version resolution will work.
And the most straightforward way seems to download jars and make classpath manually just for the test.

**Comment by swankjesse** [comment]
If you change the root project to also depend on the version above, most build tools will prefer the latest version they know about.

**Comment by rewlad** [comment]
Current status:
1) automatic dependency resolution works this time.
2) 'BLOCKED' is no longer in Thread.print for the new version.
3) real server start-up takes 95-105s depending mainly from weather on Mars, and may be from the lib version, but it's not clear. It seems to wait more somewhere else in domain logic.
4) my branch with multiple optimizations is going to be merged and end-to-end tested this week before going to production.

**Comment by rewlad** [comment]
Why firstRef and atomicByteCount are ```var```?
They do not change (```val```), Atomic object content changes.

**Comment by swankjesse** [comment]
@rewlad that's a mistake. Can fix!

**Comment by swankjesse** [comment]
> weather on Mars
?

What are you building?!

**Comment by rewlad** [comment]
| What are you building?!
it's a joke. 

> > weather on Mars
> 
> What are you building?!

"weather on Mars dependency" is a joke/proverb;
A lot of things in this world are just too complex to instantly see their reasons;

I'm building just another open framework (c4proto), that has rule engine, keeps data in-memory, and loads from snapshots on start-up.
Other people are building products for transport companies using the framework.

**Comment by rewlad** [comment]
Current status:

I've made some experimental implementation with ThreadLocal:
https://github.com/conecenter/okio/commit/f3dcd454bc22b110cf8ea5f589714c03b0abb589
And found a synthetic test:
https://github.com/conecenter/c4proto/blob/sk-okio/extra_examples/src/main/scala/ee/cone/c4actor/ProtoBuffTest.scala
ThreadLocal variant seems to behave better with parallel load (encode-time + gc-time):
```
CAS          par 2.5s+0.8s  seq 4s+0.2s
NOOP         par 2.8s+1s    seq 13s+0.5s
THREAD_LOCAL par 0.9s+0.25s seq 4.5s+0.2s
```

Real server still keeps the secret

**Comment by swankjesse** [comment]
How do I interpret these numbers?

I’m really reluctant to do ThreadLocals because they’re a pain to operate. A thread that makes any interaction with Okio has a higher cost! They’ll also perform poorly in producer-consumer situations where buffers are written by one thread and read by another.

**Comment by rewlad** [comment]
These numbers shows hypothetical situation, where 25 cores are making some hard protobuf encoding.
For CAS implementation whole process takes ~2.5s and 0.8s for gc-ing.
For ThreadLocal implementation it takes ~0.9s and 0.25s for gc-ing -- 3 times less.

I agree, that CAS implementation is better for more cases.
It's even not clear yet what implementation is better for most production c4proto cases.
There can become possible options:
- I get that CAS is better and do nothing
- I get that ThreadLocal is better for me and use okio fork
- I contribute configurable solution (with CAS by default)

**Comment by swankjesse** [comment]
Thanks for helping with this, it’s really awesome to have a demanding use case like this so we can get great performance.

I’d like to try another experiment. Our current CAS strategy is quite pessimistic: if it doesn’t win on the first attempt it gives up. I’d like to replace it with a CAS that tries say, 10 times before aborting. I’ll send a PR for this – do you mind benchmarking it?

**Comment by swankjesse** [comment]
Here’s two more strategies that might help! I’d love for you to benchmark each of these. (I can also upload snapshots to Maven central if that helps).

https://github.com/square/okio/pull/723/files
https://github.com/square/okio/pull/724/files

**Comment by rewlad** [comment]
Ok, I'll check it in a day or 2;

Another idea is to group 2 atomics into 1

**Comment by rewlad** [comment]
Span_10 seems to work same as CAS.

Buckets:
I moved counter to Segment and made flexible bucket count, then it seems to behave good: 
https://github.com/square/okio/pull/725

Buckets with CAS behaves same as  buckets with synchronized, at least in my test

**Comment by rewlad** [comment]
That's good.

https://github.com/square/okio/pull/728 just adds a comment to clarify, that ```limit``` can be used in non-obvious way

**Comment by swankjesse** [comment]
Merged!
