### ISSUE TITLE
Missing javadocs

### ISSUE THREAD

**Issue by gmk57** [square/okio#730]
Since version 2.3.0 javadocs for many (not all) classes and methods are missing. This is how "quick documentation" looks like in Android Studio for 2.2.2 and 2.6.0:
![v222](https://user-images.githubusercontent.com/22061463/83552284-2eb79900-a512-11ea-8fa6-96ec9cb2a28d.png)
![v260](https://user-images.githubusercontent.com/22061463/83552362-53137580-a512-11ea-953e-10e9724cb5d5.png)
Viewing docs in IDE is much faster than browsing through the website. Please fix it if possible.

As a minor side note, since v2.0.0 javadoc.jar is in Markdown format, which breaks compatibility with [some third-party sites](https://javadoc.io/doc/com.squareup.okio/okio/2.6.0/index.html). Are there technical reasons for that? Couldn't find any info in changelog.

**Comment by swankjesse** [comment]
Looks like this broke when we introduced multiplatform. If anyone wants to dig in and fix, that’d be great. Otherwise we’ll get to it!

**Comment by gmk57** [comment]
Well, I can copy docs from `commonMain` to `jvmMain`, but is this the right way to go? They may start to diverge after a while. I'm not familiar with multiplatform projects, so not sure how docs should be structured in this case.

**Comment by matejdro** [comment]
It looks like IDE is reading the documentation from the `actual` classes/interfaces.

For example [expect BufferedSource](https://github.com/square/okio/blob/master/okio/src/commonMain/kotlin/okio/BufferedSource.kt) has documentation, while [actual BufferedSource](https://github.com/square/okio/blob/master/okio/src/jvmMain/kotlin/okio/BufferedSource.kt) does not have documentation.

Maybe this is something that should be fixed from the IntelliJ / Jetbrains side? From what I see, only good solution is to copy over documentation to the actual classes and maintain duplicates.

**Comment by matejdro** [comment]
I've created IntelliJ issue for this: https://youtrack.jetbrains.com/issue/IDEA-265567

**Comment by Egorand** [comment]
I also recently noticed that at some point Dokka dropped support for Javadoc publication in multiplatform projects (https://github.com/Kotlin/dokka/issues/1753). Don't recall which version of Dokka Okio uses, but maybe this is the culprit? If yes - switching from `dokkaJavadoc` to `dokkaHtml` might be something to try, if anyone's interested.

**Comment by swankjesse** [comment]
Fixed now.
