### ISSUE TITLE
java.io.IOException: closed

### ISSUE THREAD

**Issue by 15895880466** [square/okio#739]
seems okhttp cache does not work and throws following exception

InputStreamUtil: Got exception when calling available() on an InputStream returned from shouldInterceptRequest. This will cause the related request to fail.
java.io.IOException: closed
        at okio.RealBufferedSource$1.available(RealBufferedSource.java:447)
        at org.chromium.android_webview.InputStreamUtil.available(InputStreamUtil.java:44)

**Comment by swankjesse** [comment]
No action to take here. If you'd like to provide us with an executable test case that demonstrates the problem, please open a new issue.
