### ISSUE TITLE
Implement ByteString platform specific functionality as extensions

### ISSUE THREAD

**Issue by kevincianfarini** [square/okio#742]
While working on #740 I thought ByteString would reach feature parity on every platform. When attempting to refactor out expect/actual, I noticed that there's functions implemented on `actual` classes that are specific to a platform, like JVM. For example:

```kotlin
override fun asByteBuffer(): ByteBuffer = ByteBuffer.wrap(toByteArray()).asReadOnlyBuffer()
```

exists on JVM actual `SegmentedByteString`. 

By implementing these methods as extensions (and deprecating the member functions), we'll be able to move towards having completely common Kotlin implementations of `ByteString` and `SegmentedByteString`. 

As it stands right now, the `actual` implementations of `ByteString` are dominated by calls to `commonXXX` functionality. It's largely boilerplate that could be eliminated.

**Comment by JakeWharton** [comment]
We can never get rid of the member versions or it would be a binary-incompatible change (at least not without changing the package name and doing a major revision). This is the reason we have such an elaborate setup with top-level "common"-prefixed functions that implement most of the functionality against a common stub API.

**Comment by kevincianfarini** [comment]
I figured that would be the case -- I'm not too well versed how to make binary compatible changes. It's a first for me. 

> (at least not without changing the package name and doing a major revision)

Out of curiosity, why would this require both a package rename as well as a major version bump? Wouldn't a major revision be sufficient? 

I don't know the cadence of Okio's update schedule, but I imagine allowing the deprecation warnings to hang out on the `actual` platform specific implementations until the next major version is released. Is that correct?

**Comment by JakeWharton** [comment]
Normally, yes. But Okio is a supremely foundational library (downstream _library_ dependencies number in the tens) such that doing an in-place breaking change would be exceedingly disruptive to the ecosystem. How do you update when OkHttp and Moshi have migrated but Wire and Retrofit have not?

As a result, major version numbers come with new packages: https://jakewharton.com/java-interoperability-policy-for-major-version-updates/. See also: https://jlbp.dev/JLBP-6.

**Comment by kevincianfarini** [comment]
Makes sense! Closing this issue.

**Comment by JakeWharton** [comment]
Another way to think about it is that we bear the burden so that our users don't have to. Major versions should come with major carrots that justify their existence and entice upgrade! Not just major sticks that annoy our users because we wanted to reduce our maintenance burden by 20%. Of course, being a well-funded (in terms of developer time) project we have the "luxury" of bearing this. For small, individual-run projects keeping your own sanity is probably more important.
