### ISSUE TITLE
Code blocks look broken in README.md

### ISSUE THREAD

**Issue by Egorand** [square/okio#775]
Did I break the formatting when improving how they look in MkDocs?

**Comment by swankjesse** [comment]
I don’t think we can have tabs and look good on GitHub.com. One solution might be to move stuff out of README and into say, docs/recipes.md ?

**Comment by Egorand** [comment]
I like how @ShaishavGhandi restructured KotlinPoet's docs ([commit](https://github.com/square/kotlinpoet/commit/8c3fc4b11b28878f80b938ce9eb5da9812b35162)), essentially moving README.md contents under docs/ and just leaving a link to https://squareup.github.io/kotlinpoet behind.

**Comment by swankjesse** [comment]
Also need to fix the 1.x docs which we lost.
https://github.com/square/okio/pull/721/files#diff-92751ca347c279e3b2dd64ace8b706e7L35

**Comment by swankjesse** [comment]
Also need to fix the 1.x docs which we lost.
https://github.com/square/okio/blob/2a2d4f805bde45d89d26acc5bf3992e5b727c20c/deploy_website.sh#L35-L38
