### ISSUE TITLE
Promote HashingSource/HashingSink to common Kotlin

### ISSUE THREAD

**Issue by kevincianfarini** [square/okio#782]
Now that Okio has an internal multiplatform hashing api, Hashing Source/Sink should be available for all compile targets.

**Comment by Egorand** [comment]
Hype!

Is this closed by #802?

**Comment by kevincianfarini** [comment]
Nope :) this is the next thing on my to-do list. 

#802 promotes hashing for just buffer. Right now, Hashing Sink/Source done exist in common, only JVM.
