### ISSUE TITLE
Exception in Android L

### ISSUE THREAD

**Issue by wnsdudril** [square/okio#79]
10-06 12:03:39.450  1327  2243 W System.err: java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
10-06 12:03:39.460  1327  2261 E AndroidRuntime: FATAL EXCEPTION: Thread-324
10-06 12:03:39.460  1327  2261 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.android.okio.OkBuffer.write(OkBuffer.java:574)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.android.okio.OkBuffer.read(OkBuffer.java:610)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:56)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:465)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.android.okhttp.internal.Util.skipAll(Util.java:227)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:235)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:487)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:574)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.touchtype_fluency.util.HttpDownload.b(Unknown Source)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.touchtype_fluency.util.HttpDownload.interrupt(Unknown Source)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at com.touchtype_fluency.util.Downloader$2.run(Unknown Source)
10-06 12:03:39.460  1327  2261 E AndroidRuntime:    at java.lang.Thread.run(Thread.java:818)
10-06 12:03:39.460  1327  2243 W System.err:    at com.android.okio.OkBuffer.write(OkBuffer.java:574)
10-06 12:03:39.460  1327  2243 W System.err:    at com.android.okio.OkBuffer.read(OkBuffer.java:610)
10-06 12:03:39.460  1327  2243 W System.err:    at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:56)
10-06 12:03:39.460  1327  2243 W System.err:    at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:465)
10-06 12:03:39.460  1327  2243 W System.err:    at com.android.okhttp.internal.Util.skipAll(Util.java:227)
10-06 12:03:39.460  1327  2243 W System.err:    at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:235)
10-06 12:03:39.460  1327  2243 W System.err:    at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:487)
10-06 12:03:39.460  1327  2243 W System.err:    at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:204)
10-06 12:03:39.460  1327  2243 W System.err:    at com.android.okio.RealBufferedSource$1.close(RealBufferedSource.java:187)
10-06 12:03:39.460  1327  2243 W System.err:    at java.io.BufferedInputStream.close(BufferedInputStream.java:141)
10-06 12:03:39.460  1327  2243 W System.err:    at org.apache.commons.io.input.ProxyInputStream.close(ProxyInputStream.java:102)
10-06 12:03:39.460  1327  2243 W System.err:    at java.io.FilterInputStream.close(FilterInputStream.java:64)
10-06 12:03:39.460  1327  2243 W System.err:    at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:178)
10-06 12:03:39.460  1327  2243 W System.err:    at com.touchtype_fluency.util.HttpDownload.downloadZip(Unknown Source)
10-06 12:03:39.460  1327  2243 W System.err:    at com.touchtype_fluency.util.b$1.onDownload(Unknown Source)
10-06 12:03:39.460  1327  2243 W System.err:    at com.touchtype_fluency.util.Downloader$1.run(Unknown Source)
10-06 12:03:39.460  1327  2243 W System.err:    at java.lang.Thread.run(Thread.java:818)

**Comment by arthurpalves** [comment]
Hi,

I'm using the newest version **2.5.0**, but I'm still getting this issue on Android L.

```
java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
            at com.android.okio.OkBuffer.write(OkBuffer.java:574)
            at com.android.okio.OkBuffer.read(OkBuffer.java:610)
            at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:56)
            at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:465)
            at com.android.okhttp.internal.Util.skipAll(Util.java:227)
            at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:235)
            at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:487)
            at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
            at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:574)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
            at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
```

Any help?

**Comment by JakeWharton** [comment]
That is not the Okio you are including, but one bundled in the Android
platform itself.

**Comment by arthurpalves** [comment]
Thanks @JakeWharton. I'll continue catching the `NullPointerException`.

**Comment by arthurpalves** [comment]
Thanks @JakeWharton. I'll continue catching the `NullPointerException`.

**Comment by swankjesse** [comment]
@arthurpalves it's likely this NPE is caused by a concurrency problem in your code. For example, using or closing an InputStream from multiple threads.

**Comment by arthurpalves** [comment]
@swankjesse Indeed, but at this time I can't avoid it. Testing with yours **HttpUrlConnectionImpl.java** instead of Android's **HttpUrlConnection.java** (which uses okhttp 2.0.0 on Android L), seems to work fine.

**Comment by swankjesse** [comment]
@arthurpalves who uses Android L? Any device that's running that beta software shouldn't be.

**Comment by arthurpalves** [comment]
@swankjesse 94% of my users (www.qviky.com) :smile:

**Comment by swankjesse** [comment]
@arthurpalves is that for the Android L preview? Or the final Lollipop release? 
https://en.wikipedia.org/wiki/Android_Lollipop

**Comment by arthurpalves** [comment]
@swankjesse You're right, I was referring to the final release (as well as the beta) as Android L. I'm was not talking about the Preview on my question.

**Comment by swankjesse** [comment]
@arthurpalves please open a separate defect if you can reproduce reliably. This defect is specifically for "Android L".

**Comment by zouzhenglu** [comment]
I found the exception in Android 7.0,level 24
`

io.reactivex.exceptions.OnErrorNotImplementedException:Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
--
2 io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
6 com.android.okhttp.okio.Buffer.copyTo(Buffer.java:175)
7 com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:199)
8 com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
9 com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
10 com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
11 com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
12 com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
13 com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
14 com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
15 com.kzl.common.NetworkUtils.getNetIp(NetworkUtils.java)
16 com.kzl.common.NetworkUtils$1.subscribe(NetworkUtils.java)
17 io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java)
18 io.reactivex.Observable.subscribe(Observable.java)
19 io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java)
20 io.reactivex.Scheduler$DisposeTask.run(Scheduler.java)
21 io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java)
22 io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java)
23 java.util.concurrent.FutureTask.run(FutureTask.java:237)
24 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
25 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
26 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
27 java.lang.Thread.run(Thread.java:776)

`

**Comment by swankjesse** [comment]
Typically this happens when you're accessing a steam from multiple threads unsafely.

**Comment by heinzan** [comment]
W/System.err: java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
W/System.err:     at com.android.okhttp.okio.Buffer.write(Buffer.java:1182)
W/System.err:     at com.android.okhttp.okio.Buffer.read(Buffer.java:1221)
W/System.err:     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:55)
W/System.err:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
W/System.err:     at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:944)
W/System.err:     at com.android.okhttp.internal.Util.skipAll(Util.java:159)
W/System.err:     at com.android.okhttp.internal.Util.discard(Util.java:141)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine$2.close(HttpEngine.java:972)
W/System.err:     at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:396)
W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:384)
W/System.err:     at java.io.BufferedInputStream.close(BufferedInputStream.java:472)
W/System.err:     at android.media.MediaHTTPConnection.teardownConnection(MediaHTTPConnection.java:153)
W/System.err:     at android.media.MediaHTTPConnection.disconnect(MediaHTTPConnection.java:144)
W/System.err:     at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:61)
W/System.err:     at android.os.Binder.execTransact(Binder.java:565)
W/System.err:     at android.media.MediaPlayer._release(Native Method)
W/System.err:     at android.media.MediaPlayer.release(MediaPlayer.java:1742)
W/System.err:     at com.halilibo.bettervideoplayer.BetterVideoPlayer.release(BetterVideoPlayer.java:622)
W/System.err:     at com.halilibo.bettervideoplayer.BetterVideoPlayer.onDetachedFromWindow(BetterVideoPlayer.java:969)
W/System.err:     at android.view.View.dispatchDetachedFromWindow(View.java:15600)
W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3230)
W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
W/System.err:     at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3501)
W/System.err:     at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6339)
W/System.err:     at android.view.ViewRootImpl.die(ViewRootImpl.java:6309)
W/System.err:     at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:484)
W/System.err:     at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:415)
W/System.err:     at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:168)
W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4493)
W/System.err:     at android.app.ActivityThread.-wrap6(ActivityThread.java)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:156)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6577)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
I/MediaPlayer: Pid:9572 MediaPlayer destructor

In Android  7.0 how resolve?

**Comment by DavidWiseGroup** [comment]
Also looks like firebase messaging service uses okhttp and crashes...

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
       at com.android.okhttp.okio.Buffer.write + 1182(Buffer.java:1182)
       at com.android.okhttp.okio.Buffer.read + 1221(Buffer.java:1221)
       at com.android.okhttp.okio.RealBufferedSource.read + 65(RealBufferedSource.java:65)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read + 592(Http1xStream.java:592)
       at com.android.okhttp.internal.Util.skipAll + 170(Util.java:170)
       at com.android.okhttp.internal.Util.discard + 152(Util.java:152)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close + 609(Http1xStream.java:609)
       at com.android.okhttp.okio.RealBufferedSource.close + 421(RealBufferedSource.java:421)
       at com.android.okhttp.okio.RealBufferedSource$1.close + 409(RealBufferedSource.java:409)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza + 4(:4)
       at com.google.firebase.messaging.zze.close + 37(:37)
       at com.google.firebase.messaging.zzb.zzas + 51(:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzd + 59(:59)
       at com.google.firebase.iid.zzb.run + 2(:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1162(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 636(ThreadPoolExecutor.java:636)
       at com.google.android.gms.common.util.concurrent.zza.run + 6(:6)
       at java.lang.Thread.run + 764(Thread.java:764)
```

Have significant amount of crashes on application we developed. 
Here is the summary of crashlytics, does not looks like bug for specific Android API version 

![Screen Shot 2019-09-01 at 16 25 51](https://user-images.githubusercontent.com/39942797/64077083-36bd8080-ccd5-11e9-801c-07798c38721d.png)

Tried update all libraries for the app, but yet still receive these crashes. 
Any suggestions?

**Comment by AlexeyGorovoy** [comment]
@DavidWiseGroup have you been able to find the solution? We've found ourselves in a similar situation and literally nothing new on the web on this issue since your post two months ago.
