### ISSUE TITLE
okio-files API

### ISSUE THREAD

**Issue by swankjesse** [square/okio#797]
This is a tracking bug for all the work to implement Okio’s new multiplatform files API.

 * [x] Path.name
 * [x] Path.parent
 * [x] Filesystem.cwd() - current working directory
 * [x] Filesystem.list(Path) - list directory contents
 * [x] Filesystem.source(Path) - read a file
 * [x] Filesystem.sink(Path) - write a file
 * [x] Filesystem.atomicMove(Path, Path) - move a file
 * [x] Filesystem.copy(Path, Path) - move a file
 * [x] Filesystem.delete(Path) - remove a file
 * [x] Filesystem.mkdir(Path) - create a directory
 * [x] Change empty-string relative path to a single dot? (more conventional)
 * [x] Use [object pinning](https://kotlinlang.org/docs/reference/native/c_interop.html#object-pinning) with Buffers
 * [x] Support Windows
 * [x] Something for fsync?
 * [x] FakeFilesystem, a first-party in-memory implementation
 * [x] Support Linux
 * [x] FileMetadata
 * [x] Support Windows-like semantics for FakeFileSystem
 * [x] Implement and test inode-like semantics for FakeFileSystem
 * [x] Support [Windows Paths](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file)
 * [x] Support Windows paths like `C:\foo.txt` in FakeFileSystem
 * [x] appendingSink()
 * [x] Support iOS
 * [x] Explore options for Node.js. Might motivate one-shot suspend functions to load an entire file as a ByteString?
 * [x] JVM methods for interop with `java.io.File`, `java.nio.file.Path`
 * [x] Support Android releases that don’t have java.nio.file
 * [x] Don’t depend on `kotlinx-nodejs`
 * [x] Add an experimental annotation
 * [x] Filesystem.deleteContents, to recursively delete a directory
 * [x] Filesystem.createDirectories, to recursively create a path of directories
 * [x] Filesystem.exists, or some mechanism to differentiate between ‘absent’ and ‘inaccessible’
 * [x] Good story around fault injection for testing
 * [x] FakeFilesystem should make it easier to diagnose resource leaks
 * [x] Fix bug where `FakeFilesystem.appendingSink()` causes the readable file to appear empty
 * [x] Fix bug where calling `FakeFilesystem.createDirectories()` crashes creating roots
 * [x] Path.isRoot
 * [x] Make Path comparable
 * [x] Make Filesystem.list() return paths in sorted order?
 * [x] Require `FakeFilesystem.workingDirectory` is an absolute path
 * [x] Test case for API as used from Java
 * [x] Figure out how to publish when no platforms support both macOS and Windows compilation
 * [x] Move FakeFilesystem to `okio.testing`
 * [x] Decide whether to rename `Filesystem` to `FileSystem`
 * [x] Move JVM-only functions on `Paths` to `Path`, including expect/actual work
 * [x] Final name for `windowsLimitations` parameter on FakeFilesystem
 * [x] Decide whether to rename Path’s `slash` parameter to an enum or boolean like `windowsy`.
 * [x] Decide on names of [write and read](https://github.com/square/okio/pull/871#discussion_r553446413) functions
 * [ ] Concurrent access to FakeFileSystem
 * [ ] Document that FileMetadata.isDirectory is different from whether list() will return results
 * [ ] Support non UTF-8 paths

**Comment by JakeWharton** [comment]
How about a first-party in-memory FS impl too?

**Comment by swankjesse** [comment]
Yes, definitely.

**Comment by ajalt** [comment]
This is looking great so far. Do you plan on supporting JS targets? It should be possible on Node with their blocking apis like [openSync](https://nodejs.org/api/fs.html#fs_fs_opensync_path_flags_mode). For browsers, `PLATFORM_FILESYSTEM` could be something like `FakeFilesystem`, or an implementation that just throws exceptions if you try to use it.

**Comment by JakeWharton** [comment]
For browsers platform should definitely throw.

A separate library built against [the new FS API in Chrome](https://wicg.github.io/file-system-access/) could be built, but the async nature of its APIs will be a problem. I suspect we may need to reconsider the use of synchronous APIs throughout, or at the very least, a separate async interface that works on all platforms will need to be built since the current one will be unsuitable for things that need to run in a browser or in any real node deployment.

**Comment by ajalt** [comment]
> For browsers platform should definitely throw.

I agree. 

If you do decide to implement this for JS, you may run into the problem that browser bundlers like webpack interact badly with NodeJs `require` statements. You might be interested in the [hack I use in Clikt](https://github.com/ajalt/clikt/blob/master/clikt/src/jsMain/kotlin/com/github/ajalt/clikt/mpp/JsCompat.kt) to make webpack ignore my Node imports.

**Comment by swankjesse** [comment]
I’m virtualboxing...

<img width="1680" alt="Screen Shot 2020-11-07 at 23 18 47" src="https://user-images.githubusercontent.com/133019/98456889-d71bfa00-214f-11eb-8acb-02acec253f46.png">
![VirtualBox_Ubuntu_07_11_2020_23_19_58](https://user-images.githubusercontent.com/133019/98456892-dc794480-214f-11eb-884a-4bdb3b2e766e.png)
![VirtualBox_windows_07_11_2020_23_20_11](https://user-images.githubusercontent.com/133019/98456896-dedb9e80-214f-11eb-9882-7db3ec466276.png)

**Comment by swankjesse** [comment]
I’m virtualboxing...
![Mac](https://user-images.githubusercontent.com/133019/98456907-f9ae1300-214f-11eb-87c9-db8a42479656.png)
![Ubuntu](https://user-images.githubusercontent.com/133019/98456908-ff0b5d80-214f-11eb-80c1-068af1a34ac0.png)
![Windows](https://user-images.githubusercontent.com/133019/98456910-03377b00-2150-11eb-94bf-0e0b550909ec.png)

**Comment by swankjesse** [comment]
I found this interesting doc on how paths work in Windows. There’s some surprising stuff, like how the name prefix `\\?\` doesn’t escape anything, which means you can name a file `..` if you like!
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by swankjesse** [comment]
I’ve got a plan for `fsync`. My first idea was to create a boolean option on `sink()` that would force an fsync in `close()`:

```
  abstract fun sink(file: Path, fsyncOnClose: Boolean): Sink
```

I don’t like this because it’s mixing behavior with policy. Especially since the policy can grow pretty complex in aggregate:
 * fsyncOnClose, fsyncOnFlush, fsyncEnclosingDirectory
 * what about createDirectory(), delete(), and atomicMove() ?

It’s a slippery slope to a ton of knobs, and brutal as a caller to remember to flip them all. Especially since the difference is pretty severe if you get it wrong (very bad performance or data loss on power failure). Instead I think the best option is to (eventually) offer an alternate `Filesystem` that has the same behavior but different durability promises. Perhaps this:

```
class FileSystem {
  ...

  /** 
   * Returns a filesystem that operates on the same data as this file system,
   * but whose write operations do not return until they are durable-enough
   * to survive an operating system crash or power loss. Such writes may
   * still be lost in the event of data corruption bug or hardware failure.
   */
  val withForceDurable(): FileSystem
```

**Comment by swankjesse** [comment]
![Uploading Screen Shot 2020-12-15 at 22.05.30.png…]()

**Comment by swankjesse** [comment]
<img width="405" alt="Screen Shot 2020-12-15 at 22 05 30" src="https://user-images.githubusercontent.com/133019/102299993-00cffa00-3f22-11eb-91d1-66b532d284ef.png">

**Comment by sbogolepov** [comment]
Hi! I'm playing around with okio-files and it's already really great :)
Do you plan to add something like Java's [`Files.exists`](https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/nio/file/Files.html#exists(java.nio.file.Path,java.nio.file.LinkOption...)) to `Filesystem`?

**Comment by yschimke** [comment]
A logging decorator for Filesystem would be really useful.  Found out while try to update OkHttp Cache.

**Comment by yschimke** [comment]
deleteIfExists? Awkward without as checking makes the operation non atomic, and catching generic IOException is awkward.

**Comment by yschimke** [comment]
Bit of random feedback, FakeFilesystem is a great test of whether you are correctly closing sinks and sources.  That should be part of the functionality.

**Comment by yschimke** [comment]
Should okio fix windows issues within a single VM? e.g. on Windows, would a safe filesystem that closed files on deletion help?  Same for Cache usage, should the default system filesystem avoid two writers.

**Comment by yschimke** [comment]
path.toString() feels wrong, especially since Response.Body talked me out of using this for anything other than debugging.  file.name keeps biting me though.

**Comment by swankjesse** [comment]
What are you using `path.toString()` for?

**Comment by yschimke** [comment]
```
class ClasspathFilesystem: FileSystem() {
  override fun appendingSink(file: Path): Sink {
    throw IOException("read only")
  }

  override fun atomicMove(source: Path, target: Path) {
    throw IOException("read only")
  }

  override fun canonicalize(path: Path): Path {
    return path
  }

  override fun createDirectory(dir: Path) {
    throw IOException("read only")
  }

  override fun delete(path: Path) {
    throw IOException("read only")
  }

  override fun list(dir: Path): List<Path> {
    throw IOException("not listable")
  }

  override fun metadataOrNull(path: Path): FileMetadata? {
    TODO()
  }

  override fun sink(file: Path): Sink {
    throw IOException("read only")
  }

  override fun source(file: Path): Source {
    val stream: InputStream = this.javaClass.classLoader.getResourceAsStream(file.toString())
      ?: throw FileNotFoundException("file not found: $file")

    return stream.source()
  }
}
```

**Comment by swankjesse** [comment]
All remaining checkboxes have their own associated issues. I’m closing out this big one.
https://github.com/square/okio/issues/1012
https://github.com/square/okio/issues/950
https://github.com/square/okio/issues/887

**Comment by YoussefHachicha** [comment]
no such thing as Filesystem.cwd(), i wans't able to get the cwd

**Comment by stepin** [comment]
Yes, looks like there is no Filesystem.cwd() but there is workaround (i.e. `.` can be used as current working dir):

```
val cwd = FileSystem.SYSTEM.canonicalize(".".toPath())
```
