### ISSUE TITLE
Multiplatform watchOs is missing

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/okio#820]
We are using okio multiplatform. However it misses `watchosArm64` and `watchosX86`:
https://github.com/square/okio/blob/0613e03782cc8ffbe4f1ce0fd8ef21aae276ea04/okio/build.gradle#L25-L32

Is there a reason these are not included yet?

**Comment by swankjesse** [comment]
No reason. Send a pull request?

**Comment by PaulWoitaschek** [comment]
Done :)

**Comment by PaulWoitaschek** [comment]
@swankjesse I was missing arm32 and created another PR for that.
