### ISSUE TITLE
Update kotlin to 1.4.21

### ISSUE THREAD

**Issue by slavonnet** [square/okio#832]

**Comment by Egorand** [comment]
Any specific changes from 1.4.20 that Okio should pick up? Otherwise, what's your use case for this update?

**Comment by slavonnet** [comment]
1.4.21 bugfix release.
okio allready on 1.4.20
https://github.com/square/okio/pull/826

case is one buld library from idea kotlin plugin and packages

**Comment by JakeWharton** [comment]
Feel free to send a PR to upgrade. However, we don't do releases to solely update dependencies unless so required by Kotlin/Native incompatibility. Neither 1.4.20 nor 1.4.21 are such a release.

**Comment by swankjesse** [comment]
No action to take on this specifically.
