### ISSUE TITLE
Snapshots not published due to a Dokka bug

### ISSUE THREAD

**Issue by Egorand** [square/okio#859]
Noticed that the [latest snapshots](https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okio/) date back to December 21st. This seems to be due to failures in the publishing workflow (e.g. see [this run](https://github.com/square/okio/runs/1615326480)), caused by an issue with the `okio:dokkaGfm` task, filed here: https://github.com/Kotlin/dokka/issues/1592. TLDR is that Dokka fails to parse tables in Kdoc, and `Path` has a table in its Kdoc. Until the bug is fixed, here are a few options:

1. Revert to Dokka 0.10.1. This will be painful due to a large number of breaking changes.
2. Screenshot the table and reference an image in the Kdoc. Dokka doesn't provide good support for this, but it can be done, see https://github.com/Kotlin/dokka/issues/177.
3. Replace the table with something else for the time being and revert once the bug is fixed.

**Comment by Egorand** [comment]
@swankjesse LMK what your preference is, I wanna pull the latest snapshot and try the files stuff in a fun project.

**Comment by swankjesse** [comment]
I can do an HTML table in the interim.

**Comment by Egorand** [comment]
That's perfect

**Comment by yschimke** [comment]
Looks like publishing again https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okio/okio-multiplatform/2.10.0-SNAPSHOT/

**Comment by yschimke** [comment]
Missing okio-testing

**Comment by swankjesse** [comment]
No action for us to take on this. Waiting on the Dokka fix.

**Comment by yschimke** [comment]
Fix has landed https://github.com/Kotlin/dokka/pull/1682/files

So probably just waiting for next release.
