### ISSUE TITLE
Safe filesystem

### ISSUE THREAD

**Issue by yschimke** [square/okio#878]
Should okio fix windows issues within a single VM? e.g. on Windows, would a safe filesystem that closed files on deletion help? Same for Cache usage, should a safe wrapper of the system filesystem avoid two writers, make this failure predictable and early rather than manifesting as a corrupt cache.

**Comment by swankjesse** [comment]
Making FakeFileSystem explode on multiple concurrent writers would be nice.

Doing it for the system file system in Okio is trickier. It won't help if concurrent access spans APIs (java.io) or processes.

It'd be interesting if in OkHttp we kept a static Set of open cache Paths, just to detect single-process problems.

**Comment by swankjesse** [comment]
@yschimke anything else to do here, now that we have some safety features in FakeFileSystem?

**Comment by yschimke** [comment]
I like this approach more.  Testing with the worst implementation of a filesystem to flush out issues on various platforms.

But at the time I was suggesting the opposite, ways to make a non fake file system safe when used concurrently from a single process.  It's not clearly a good problem to solve, because two processes will still observe the problem.
