### ISSUE TITLE
Doc page is broken

### ISSUE THREAD

**Issue by oldergod** [square/okio#888]
https://square.github.io/okio/2.x/okio/okio/-timeout/index.md

gives me this

[image](https://user-images.githubusercontent.com/1767669/104976789-078fd800-59cc-11eb-9359-ff8f2836cda4.png)

**Comment by Egorand** [comment]
Where did that URL come from? Here's what should be the correct one which looks fine: https://square.github.io/okio/2.x/okio/okio/-timeout/index.html

**Comment by oldergod** [comment]
I see, this was from OkHttp https://square.github.io/okhttp/4.x/okhttp/okhttp3/-call/timeout/

**Comment by swankjesse** [comment]
I think it’s fixed now?
