### ISSUE TITLE
Should FileSystem expose some uri/naming system?

### ISSUE THREAD

**Issue by yschimke** [square/okio#896]
Similar or compatible with Spring?

https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/html/resources.html

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/231923/107873490-cf849380-6eaa-11eb-99de-03d8a149a8b6.png">

Firstly for allowing config to reference files in this new world without competing conventions emerging.  Secondly to allow errors to describe things more usefully than just as "/conf/server.json".  But which one?

**Comment by swankjesse** [comment]
I think FileSystem is a building block for this, but it shouldn’t attempt this directly. Doing it directly needs fancier abstractions than we have in Okio, like a mechanism to register resource schemes.
