### ISSUE TITLE
JS IR compiler support

### ISSUE THREAD

**Issue by andersio** [square/okio#910]
While JS IR backend is still in alpha, IR compiler support is valuable to prototype and test TypeScript integration. So it would be great if okio can enable `kotlin.js.compiler=both` at some point.

Having said that, when I try to convert square/okio 3.0.0-alpha1 to work with the JS IR compiler, I stumbled upon a compiler bug & filed it as [KT-45542](https://youtrack.jetbrains.com/issue/KT-45542). It is reproducible on both Kotlin 1.4.31 and 1.5.0-M1. Since square/okio uses default parameter values in its expect classes quite a lot, guess we will all have to wait then. :shipit:

**Comment by JakeWharton** [comment]
Thanks! Feel free to fire over a PR when upstream is fixed as well!

**Comment by andersio** [comment]
@JakeWharton Is it acceptable to workaround the issue by dropping default arguments?

e.g.
```diff
-  fun lastIndexOf(other: ByteString, fromIndex: Int = size): Int
+  fun lastIndexOf(other: ByteString, fromIndex: Int): Int
+  fun lastIndexOf(other: ByteString): Int
```

Not sure if this would change the ABI though.

**Comment by swankjesse** [comment]
@andersio that is not a binary-compatible change.
 Too bad!
