### ISSUE TITLE
Node FS should be .js module, not .multiplatform

### ISSUE THREAD

**Issue by JakeWharton** [square/okio#914]

**Comment by swankjesse** [comment]
Can do. What are the consequences of this?

**Comment by JakeWharton** [comment]
Fewer artifacts published. Preventing someone from depending on it from a non-JS module. It's analogous to using the .jvm plugin instead of .multiplatform for something that targets only the JVM.

Here's an example: https://github.com/cashapp/sqldelight/blob/master/drivers/sqljs-driver/build.gradle. The syntax is nearly the same as when doing multiplatform.

**Comment by swankjesse** [comment]
https://github.com/square/okio/pull/990
