### ISSUE TITLE
Document okio-multiplatform artifact

### ISSUE THREAD

**Issue by micHar** [square/okio#915]
The docs never mention `okio-multiplatform` maven config, just the regular one. At least not here https://square.github.io/okio/#releases or here https://square.github.io/okio/multiplatform/.

With okio 3 having FileSystem APIs, more people will probably be using the multiplatform, so it might be worth mentioning that in the docs.

**Comment by micHar** [comment]
For googlers, the error when you try to load regular artifact into multiplatform module looks like this:

```
Unable to build Kotlin project configuration
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find okio-3.0.0-alpha.1-samplessources.jar (com.squareup.okio:okio:3.0.0-alpha.1).
Searched in the following locations:
    https://jcenter.bintray.com/com/squareup/okio/okio/3.0.0-alpha.1/okio-3.0.0-alpha.1-samplessources.jar
...
```

**Comment by occultus73** [comment]
Yes, and can I add to that and ask the documentation state what FileSystem implementations are actually released and what extra artefacts you need to implement to use them. Such as:
- okio-zipfilesystem-multiplatform
- okio-nodefilesystem-multiplatform
- okio-fakefilesystem-multiplatform

FileSystem.SYSTEM isn't a thing in okio-multiplatform, and as of alpha.3, it seems as though _okio-fakefilesystem-multiplatform_ is the only implementation of FileSystem you can actually use for a multiplatform project.

**Comment by JakeWharton** [comment]
New artifacts shouldn't be suffixed with -multiplatform. We should fix that. It should only be for the okio module for backwards compatibility.

**Comment by occultus73** [comment]
I'm getting a lot of "JVM target 1.8 into bytecode that is being built with JVM target 1.6" compile time errors trying to use the Okio multiplatform libraries. They weren't accidentally built with any Java 6 bytecode were they?

**Comment by JakeWharton** [comment]
That sounds like the opposite. Your Kotlin compilation is targeting 1.6 whereas we target 1.8.

**Comment by occultus73** [comment]
That's my working assumption. You wouldn't believe the trouble I'm having trying to find some documentation on how to configure that in a multiplatform Gradle build script. If I keep bashing my head against the wall any longer, I think I might actually die.

**Comment by JakeWharton** [comment]
Here's what we're doing:

CoroutinePresenter

**Comment by occultus73** [comment]
I have this in the Project build gradle (Kotlin DSL):
```
val compileKotlin: org.jetbrains.kotlin.gradle.tasks.KotlinCompile by tasks
compileKotlin.kotlinOptions {
	jvmTarget = "1.8"
}
val compileTestKotlin: org.jetbrains.kotlin.gradle.tasks.KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
	jvmTarget = "1.8"
}
```

**Comment by occultus73** [comment]
Getting this error on Gradle sync since the April 15 update. Have the artifacts been published correctly?
`<ij_msg_gr>Gradle import errors<ij_msg_gr><ij_nav>/home/john/StudioProjects/mocha-android-ml-sdk/bandit/build.gradle.kts<ij_nav><i><b>project ':bandit': Unable to build Kotlin project configuration</b><eol>Details: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find okio-multiplatform-3.0.0-alpha.4-samplessources.jar (com.squareup.okio:okio-multiplatform:3.0.0-alpha.4).<eol>Searched in the following locations:<eol>    https://jcenter.bintray.com/com/squareup/okio/okio-multiplatform/3.0.0-alpha.4/okio-multiplatform-3.0.0-alpha.4-samplessources.jar</i>`

**Comment by swankjesse** [comment]
@occultus73 no, just an error on my end when publishing. Our Windows release process is pretty cumbersome because I can’t build both Mac and Windows artifacts in the same step. Will publish Windows with the next alpha.

**Comment by swankjesse** [comment]
Since fixed.
