### ISSUE TITLE
okio artifact for windows not found

### ISSUE THREAD

**Issue by jmfayard** [square/okio#934]
It seems to be unable to find the okio artifact for windows. It finds only `alpha.1` while the artifact okio-multiplatform has `alpha.5`

```
Execution failed for task ':compileKotlinNative'.
> Could not resolve all files for configuration ':nativeCompileKlibraries'.
   > Could not find com.squareup.okio:okio-mingwx64:3.0.0-alpha.5.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/squareup/okio/okio-mingwx64/3.0.0-alpha.5/okio-mingwx64-3.0.0-alpha.5.pom
         project : > com.squareup.okio:okio-multiplatform:3.0.0-alpha.5
```

<img width="718" alt="Central_Repository__com_squareup_okio_okio-mingwx64_and_Comdirect_Konto_1_" src="https://user-images.githubusercontent.com/459464/118510210-0760d880-b731-11eb-860b-124e8b6735bf.png">

What's weird is that it used to be there, and now no more.

**Comment by swankjesse** [comment]
That's my fault. Can fix for alpha.6.

**Comment by swankjesse** [comment]
Fixed.

**Comment by jmfayard** [comment]
I can confirm that the release 3.0.0.alpha.6 works on all platforms, thanks!
