### ISSUE TITLE
Multiplatform abstraction over ProcessBuilder / child-process / popen-fgets-pclose

### ISSUE THREAD

**Issue by jmfayard** [square/okio#935]
Hello,
I wonder if it would be inside or outside the scope for okio to provide a Kotlin Multiplatform common API for executing an external command and capturing its output

As a starting point, I implemented such a command in my starter project for command-line tools

See `fun executeCommandAndCaptureOutput()`
https://github.com/jmfayard/kotlin-cli-starter/search?q=executeCommandAndCaptureOutput

It uses `ProcessBuilder`on the JVM, `child-process` on Node and `popen-fgets-pclose` on POSIX. Unfortunately I have no clue how to implement it on windows

**Comment by swankjesse** [comment]
I think this is a good idea, but I don’t think we’re going to have need / capacity for it.
