### ISSUE TITLE
Different buffer pool implementations suitable for server use?

### ISSUE THREAD

**Issue by tinkerware** [square/okio#94]
Hi,

Would you be willing to accept changes for a pluggable segment pool to make Okio more suitable for use in server environments with lots of concurrent buffer use?

**Comment by swankjesse** [comment]
Though I haven't done much on this lately, I think we're going to need it. Here's more benchmarks, this time from Guava. https://github.com/google/guava/pull/2112

**Comment by swankjesse** [comment]
Fixed recently.
https://github.com/square/okio/pull/717
