### ISSUE TITLE
v2 and v1 API Docs are broken. Return 404

### ISSUE THREAD

**Issue by Blubbaz** [square/okio#952]
For at least a week both API docs for okio are broken and return a broken 404 page.

https://square.github.io/okio/2.x/okio/okio/index.html
https://square.github.io/okio/1.x/okio/

**Comment by yogurtearl** [comment]
Getting the same. :/

**Comment by jeremyolsen** [comment]
Plz fix.  This is kind of a pain as searching through source code for documentation is not exactly efficient.

**Comment by swankjesse** [comment]
Fixed! Sorry about that.
