### ISSUE TITLE
Feature Request: provide functional methods such as forEachBlock() in kotlin stdlib

### ISSUE THREAD

**Issue by FlandiaYingman** [square/okio#955]

**Comment by swankjesse** [comment]
I don't follow? This is an IO library.

**Comment by FlandiaYingman** [comment]
@swankjesse Sorry, It's my fault not to describe it clearly.
There's a method in kotlin stdlib called [FIle.forEachBlock {}](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/for-each-block.html). It reads file by byte blocks and call actions for each block. 
I wonder if we could provide same methods for okio classes such as Source or Buffer. 
Reading and process a huge file (or whatever) block by block is a common case, we can't read them all into memory in once.

**Comment by swankjesse** [comment]
You shouldn’t need such a function with Okio because it streams data automatically, in 8 KiB blocks transparently behind the scenes. Just read the data at your pace and as long as you aren’t reading everything at once, Okio won’t either.

That said, if you do need a forEachBlock() function you can do it like so:

```
  @Test
  fun forEachBlockEmpty() {
    val buffer = Buffer().writeUtf8("")
    val blocks = buffer.forEachBlock(4) {
      "[${readUtf8()}]"
    }
    assertEquals(blocks, listOf())
  }

  @Test
  fun forEachBlockNonEmpty() {
    val buffer = Buffer().writeUtf8("abcdefghijklmno")
    val blocks = buffer.forEachBlock(4) {
      "[${readUtf8()}]"
    }
    assertEquals(blocks, listOf("[abcd]", "[efgh]", "[ijkl]", "[mno]"))
  }

  fun <T> BufferedSource.forEachBlock(blockSize: Long, operator: Buffer.() -> T): List<T> {
    val result = mutableListOf<T>()
    val blockBuffer = Buffer()
    while (true) {
      request(blockSize)
      if (exhausted()) break
      blockBuffer.write(this, minOf(blockSize, buffer.size))
      result += blockBuffer.operator()
    }
    return result
  }
```
