### ISSUE TITLE
Unable to Build okio with latest (7.1) Gradle

### ISSUE THREAD

**Issue by CaymanTurtleBeach** [square/okio#972]
I am attempting to build okio in a local cloned repository using Netbeans 12.4, which defaults to Gradle 7.0 (the OS is Windows 10Pro, Java is Zulu Open JDK 11).
There are several problems for which I would appreciate guidance. Though I have experience with Netbeans and maven, I am far from knowledgeable about Gradle (and by extension, how exactly it interacts with Netbeans).
(1) The build scripts report "Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0". Given multiple statements on the okio and okhttp3 sites about keeping things updated, I find this concerning (and I am unable to determine what version of Gradle the scripts expect).
(2) more troubling, something buried in the Gradle scripts is trying to create a .gradle directory in Program Files\Netbeans-12.4, whereas I think it really should be attempting to create the directory in the <user>\AppData\Roaming\Netbeans\12.4 folder. But again, with the myriad nested paths that Gradle seems to be using, do even know what exactly is trying to create the folder (and the failure to create the folder prevents the build from completing).
Any guidance or suggestions would be appreciated. I would like to explore the utility of okio and okhttp3 for websockets.
Thanks
Jack

**Comment by swankjesse** [comment]
Is this a request for us to upgrade our Gradle version? You'll have the most success building Okio with with whatever Gradle version we're already using.

**Comment by swankjesse** [comment]
(thanks to the Gradle wrapper, you can just call `./gradlew tasks` to use our supported Gradle version.)
