### ISSUE TITLE
okio 3.0.0-alpha.8 fails to write to file on iOS

### ISSUE THREAD

**Issue by bryansills** [square/okio#973]
My iOS app crashes when I try to write to a file. Android works fine. Here is a repo that reproduces the bug: https://github.com/bryansills/OkioBug

I am not an iOS dev, so I am not 100% sure if I am doing the right thing on the iOS side, but my initial non-KMP code worked just fine: https://github.com/bryansills/OkioBug/commit/f359b89077a59754e039e11ee0ceafaaba9f4da6#diff-e85a7f19a93fa94f7deb73a026344fb78d6092d684c9d062bb37e4bd62b87187R12-R28

**Comment by swankjesse** [comment]
I believe our iOS FileSystem is pretty well exercised at this point. Not sure what action to take here, if any.
