### ISSUE TITLE
Multiplatform Home Directory

### ISSUE THREAD

**Issue by abueide** [square/okio#987]
Is there a multiplatform way to get the home directory?
Windows: C:/Users/Username/
Linux: /home/Username
Mac: /Users/Username
Android: whatever the app's sandboxed directory temp path is

If not could we add one?

Thanks in advance!

**Comment by yrezgui** [comment]
While the idea is nice, I don't think it should fit on the library as you may have different use cases (you mentioned temporary sandboxed temp path in Android, which is different from the other listed OS folders which are user folders) and can be different depending on the OS version. What do you think @swankjesse ?

**Comment by swankjesse** [comment]
I'm on the fence.

This is most useful on desktop operating systems like Windows and macOS. But it's not sufficient there? Knowing `/Users/jesse` on its own is useful for say `.ssh`, but most often you'll need more. For example, on macOS you'll probably want a specific subdirectory like Documents, Downloads, or Library.

It's not necessary for cloud or mobile. In both cases thr current working directory should be sufficient.

**Comment by yschimke** [comment]
@swankjesse I think you convinced me with Downloads! It would be great if the OS specific directories like that were available with full fidelity. 

In an App, building on Okio, building on Kotlin MP, where should this logic live? In Java it's some magic system properties or utilities in commons-io.

https://commons.apache.org/proper/commons-io/apidocs/src-html/org/apache/commons/io/FileUtils.html#line.1481

**Comment by AngeloFilaseta** [comment]
I would also find this feature VERY useful. I need to create a software system that works on all the major OS (Linux Windows and macOS). I would want users to specify some additional configurations using YAML files (you can see this as the "configuration" in the classic "convention over configuration" paradigm). The home folder could be the best place, since any user on the system could create his personal file without impacting other partitions.

I think that the `FileSystem`  object could be a good starting point.

**Comment by swankjesse** [comment]
I recommend building your own API for this. Perhaps with expect/actual and perhaps with a different mechanism for platform detection.

The thing I’m really anxious about for Okio is that if we get it wrong, it’s practically impossible for us to fix it without potentially orphaning a users’ files when we ship a bug fix. For example, we might start with `/home/$USER` and then switch to `$HOME`. If those directories are different, anything we write to the first will disappear when we switch to the second. I don’t expect we’ll make this mistake in particular, but we might misidentify Linux as Android, or treat Windows as Cygwin.

If anyone would like to try write one of these, please link the `.kt` file here!
