### ISSUE TITLE
I find a problem in the 270 line of the Buffer.java ？

### ISSUE THREAD

**Issue by wo883721** [square/okio#988]
**version**: `1.17.5`

At the `270` line of the `Buffer.java`, Regardless of whether forever is true, `byteCount -= bytesRead`。
I don't think `byteCount -= bytesRead` is necessary when forever is true.

**Comment by swankjesse** [comment]
Relevant code:
https://github.com/square/okio/blob/okio-parent-1.17.5/okio/src/main/java/okio/Buffer.java#L270

```
  private void readFrom(InputStream in, long byteCount, boolean forever) throws IOException {
    if (in == null) throw new IllegalArgumentException("in == null");
    while (byteCount > 0 || forever) {
      Segment tail = writableSegment(1);
      int maxToCopy = (int) Math.min(byteCount, Segment.SIZE - tail.limit);
      int bytesRead = in.read(tail.data, tail.limit, maxToCopy);
      if (bytesRead == -1) {
        if (tail.pos == tail.limit) {
          // We allocated a tail segment, but didn't end up needing it. Recycle!
          head = tail.pop();
          SegmentPool.recycle(tail);
        }
        if (forever) return;
        throw new EOFException();
      }
      tail.limit += bytesRead;
      size += bytesRead;
      byteCount -= bytesRead;
    }
  }
```

**Comment by swankjesse** [comment]
You're right that decrementing byteCount is not necessary. But it is also not harmful either; the initial value is Long.MAX_VALUE when forever=true; and there is no computer hardware that can read that many bytes without first throwing an OutOfMemoryError.

This unnecessary operation is performed as an optimization: an always-on decrement is cheaper than a branch. This is especially true in the non-forever case, where the branch be constant.
