### ISSUE TITLE
Allow access to `FileSystem.SYSTEM` in common source set

### ISSUE THREAD

**Issue by ScottPierce** [square/okio#994]
Was it intentional that inside the common API there is no access to `FileSystem.SYSTEM` ? This seems like something that could be accessible from the common source set.

**Comment by JakeWharton** [comment]
There is no system FS in the browser.

**Comment by swankjesse** [comment]
Closing for now but I’m open to ideas on this.

**Comment by ScottPierce** [comment]
What  is  the use case of okio in the browser? I guess I assumed okio wasn't actually compiling for js browser.

**Comment by swankjesse** [comment]
Any encoder or decoder thing, like Wire, is nice to run in-browser.

**Comment by ScottPierce** [comment]
> but I’m open to ideas on this.

I mean - the obvious solution is to extract them into separate artifacts. That's obvious though, and I'm assuming you've considered that and there is a reason why you aren't.

**Comment by swankjesse** [comment]
We do have a standalone artifact for our NodeJS filesystem. Unlike browsers, NodeJS has a filesystem.

When you say ‘separate artifacts’, what were you thinking? A single artifact with Filesystem.SYSTEM that doesn't support browsers at all? To be honest I haven’t considered that.

**Comment by ScottPierce** [comment]
Why are any of the other specific File APIs exposed in the common layer for the browser at all? Is the thought that the browser can use the in-memory file system?

**Comment by swankjesse** [comment]
@ScottPierce yeah. Or a filesystem backed by HTTP calls. Really I just want the common Okio API to be as close to the JVM API as possible.

**Comment by JakeWharton** [comment]
Only the in-memory FS will work in the browser. Anything based on the new JS file system API or backed by HTTP calls will be promise-based and unable to meet the synchronous contract of the existing API.

One of the motivating factors for a separate node artifact is that it uses the synchronous Node file system API which is only used in small apps and command-line tools. Anything large written with Node and interacting with the file system will use Node's non-blocking file system API and thus cannot use Okio.

**Comment by swankjesse** [comment]
I haven't used webworkers, but they are also potentially viable users of this API.
